// @flow

export const effectActionsConstants = {
    ASSIGN_VALUE: 'ASSIGN',
    HIDE_FIELD: 'HIDEFIELD',
    SHOW_ERROR: 'SHOWERROR',
    SHOW_WARNING: 'SHOWWARNING',
    SHOW_ERROR_ONCOMPLETE: 'ERRORONCOMPLETE',
    SHOW_WARNING_ONCOMPLETE: 'WARNINGONCOMPLETE',
    HIDE_SECTION: 'HIDESECTION',
    MAKE_COMPULSORY: 'SETMANDATORYFIELD',
    DISPLAY_TEXT: 'DISPLAYTEXT',
    DISPLAY_KEY_VALUE_PAIR: 'DISPLAYKEYVALUEPAIR',
    HIDE_OPTION_GROUP: 'HIDEOPTIONGROUP',
    HIDE_OPTION: 'HIDEOPTION',
    SHOW_OPTION_GROUP: 'SHOWOPTIONGROUP',
};
