name: 'Get instance version'
description: 'Get the instance version based on the url'
inputs:
  instance-url:
    description: 'The url to the instance'
    required: true
  username:
    description: 'The username for authentication'
    required: true
  password:
    description: 'The password for authentication'
    required: true
outputs:
  version:
    description: 'The instance version'
runs:
  using: 'node16'
  main: 'dist/index.js'