// flow-typed signature: addb2ca817a4423ff8e8f558213a163b
// flow-typed version: <<STUB>>/autosuggest-highlight_v^3.1.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autosuggest-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autosuggest-highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autosuggest-highlight/match' {
  declare module.exports: any;
}

declare module 'autosuggest-highlight/parse' {
  declare module.exports: any;
}

declare module 'autosuggest-highlight/umd/match' {
  declare module.exports: any;
}

declare module 'autosuggest-highlight/umd/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autosuggest-highlight/match/index' {
  declare module.exports: $Exports<'autosuggest-highlight/match'>;
}
declare module 'autosuggest-highlight/match/index.js' {
  declare module.exports: $Exports<'autosuggest-highlight/match'>;
}
declare module 'autosuggest-highlight/parse/index' {
  declare module.exports: $Exports<'autosuggest-highlight/parse'>;
}
declare module 'autosuggest-highlight/parse/index.js' {
  declare module.exports: $Exports<'autosuggest-highlight/parse'>;
}
declare module 'autosuggest-highlight/umd/match/index' {
  declare module.exports: $Exports<'autosuggest-highlight/umd/match'>;
}
declare module 'autosuggest-highlight/umd/match/index.js' {
  declare module.exports: $Exports<'autosuggest-highlight/umd/match'>;
}
declare module 'autosuggest-highlight/umd/parse/index' {
  declare module.exports: $Exports<'autosuggest-highlight/umd/parse'>;
}
declare module 'autosuggest-highlight/umd/parse/index.js' {
  declare module.exports: $Exports<'autosuggest-highlight/umd/parse'>;
}
