// flow-typed signature: 7ac831d49285311e9a65d90627005fff
// flow-typed version: <<STUB>>/d2-manifest_v^1.0.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd2-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd2-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd2-manifest/d2-manifest' {
  declare module.exports: any;
}

declare module 'd2-manifest/src/interactive' {
  declare module.exports: any;
}

declare module 'd2-manifest/src/Manifest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd2-manifest/d2-manifest.js' {
  declare module.exports: $Exports<'d2-manifest/d2-manifest'>;
}
declare module 'd2-manifest/src/interactive.js' {
  declare module.exports: $Exports<'d2-manifest/src/interactive'>;
}
declare module 'd2-manifest/src/Manifest.js' {
  declare module.exports: $Exports<'d2-manifest/src/Manifest'>;
}
