// flow-typed signature: 2a74471c57a52d1b025fabe617de58d7
// flow-typed version: <<STUB>>/d2-utilizr_v^0.2.15/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd2-utilizr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd2-utilizr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd2-utilizr/lib/arrayClean' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayContains' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayDifference' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayFrom' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayInsert' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayMax' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayMin' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayPluck' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayRepeat' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayReplace' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arraySort' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayTo' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/arrayUnique' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/camelCaseToUnderscores' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/clone' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isArray' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isArrayOfStrings' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isBoolean' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isDefined' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isEmpty' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isFunction' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isIE' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isInteger' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isIterable' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isNumber' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isNumeric' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isObject' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isPrimitive' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/isString' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/noop' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/numberConstrain' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/numberDecimals' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/numberIsFinite' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/numberToFixed' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/objectApplyIf' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/objectClean' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/stringReplaceAll' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/stringTrim' {
  declare module.exports: any;
}

declare module 'd2-utilizr/lib/uuid' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayClean' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayContains' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayDifference' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayFrom' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayInsert' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayMax' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayMin' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayPluck' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayRepeat' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayReplace' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arraySort' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayTo' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/arrayUnique' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/camelCaseToUnderscores' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/clone' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isArray' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isArrayOfStrings' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isBoolean' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isDefined' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isEmpty' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isFunction' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isIE' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isInteger' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isIterable' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isNumber' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isNumeric' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isObject' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isPrimitive' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/isString' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/noop' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/numberConstrain' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/numberDecimals' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/numberIsFinite' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/numberToFixed' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/objectApplyIf' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/objectClean' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/stringReplaceAll' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/stringTrim' {
  declare module.exports: any;
}

declare module 'd2-utilizr/src/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd2-utilizr/lib/arrayClean.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayClean'>;
}
declare module 'd2-utilizr/lib/arrayContains.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayContains'>;
}
declare module 'd2-utilizr/lib/arrayDifference.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayDifference'>;
}
declare module 'd2-utilizr/lib/arrayFrom.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayFrom'>;
}
declare module 'd2-utilizr/lib/arrayInsert.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayInsert'>;
}
declare module 'd2-utilizr/lib/arrayMax.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayMax'>;
}
declare module 'd2-utilizr/lib/arrayMin.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayMin'>;
}
declare module 'd2-utilizr/lib/arrayPluck.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayPluck'>;
}
declare module 'd2-utilizr/lib/arrayRepeat.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayRepeat'>;
}
declare module 'd2-utilizr/lib/arrayReplace.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayReplace'>;
}
declare module 'd2-utilizr/lib/arraySort.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arraySort'>;
}
declare module 'd2-utilizr/lib/arrayTo.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayTo'>;
}
declare module 'd2-utilizr/lib/arrayUnique.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/arrayUnique'>;
}
declare module 'd2-utilizr/lib/camelCaseToUnderscores.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/camelCaseToUnderscores'>;
}
declare module 'd2-utilizr/lib/clone.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/clone'>;
}
declare module 'd2-utilizr/lib/index' {
  declare module.exports: $Exports<'d2-utilizr/lib'>;
}
declare module 'd2-utilizr/lib/index.js' {
  declare module.exports: $Exports<'d2-utilizr/lib'>;
}
declare module 'd2-utilizr/lib/isArray.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isArray'>;
}
declare module 'd2-utilizr/lib/isArrayOfStrings.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isArrayOfStrings'>;
}
declare module 'd2-utilizr/lib/isBoolean.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isBoolean'>;
}
declare module 'd2-utilizr/lib/isDefined.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isDefined'>;
}
declare module 'd2-utilizr/lib/isEmpty.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isEmpty'>;
}
declare module 'd2-utilizr/lib/isFunction.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isFunction'>;
}
declare module 'd2-utilizr/lib/isIE.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isIE'>;
}
declare module 'd2-utilizr/lib/isInteger.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isInteger'>;
}
declare module 'd2-utilizr/lib/isIterable.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isIterable'>;
}
declare module 'd2-utilizr/lib/isNumber.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isNumber'>;
}
declare module 'd2-utilizr/lib/isNumeric.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isNumeric'>;
}
declare module 'd2-utilizr/lib/isObject.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isObject'>;
}
declare module 'd2-utilizr/lib/isPrimitive.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isPrimitive'>;
}
declare module 'd2-utilizr/lib/isString.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/isString'>;
}
declare module 'd2-utilizr/lib/noop.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/noop'>;
}
declare module 'd2-utilizr/lib/numberConstrain.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/numberConstrain'>;
}
declare module 'd2-utilizr/lib/numberDecimals.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/numberDecimals'>;
}
declare module 'd2-utilizr/lib/numberIsFinite.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/numberIsFinite'>;
}
declare module 'd2-utilizr/lib/numberToFixed.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/numberToFixed'>;
}
declare module 'd2-utilizr/lib/objectApplyIf.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/objectApplyIf'>;
}
declare module 'd2-utilizr/lib/objectClean.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/objectClean'>;
}
declare module 'd2-utilizr/lib/stringReplaceAll.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/stringReplaceAll'>;
}
declare module 'd2-utilizr/lib/stringTrim.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/stringTrim'>;
}
declare module 'd2-utilizr/lib/uuid.js' {
  declare module.exports: $Exports<'d2-utilizr/lib/uuid'>;
}
declare module 'd2-utilizr/src/arrayClean.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayClean'>;
}
declare module 'd2-utilizr/src/arrayContains.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayContains'>;
}
declare module 'd2-utilizr/src/arrayDifference.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayDifference'>;
}
declare module 'd2-utilizr/src/arrayFrom.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayFrom'>;
}
declare module 'd2-utilizr/src/arrayInsert.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayInsert'>;
}
declare module 'd2-utilizr/src/arrayMax.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayMax'>;
}
declare module 'd2-utilizr/src/arrayMin.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayMin'>;
}
declare module 'd2-utilizr/src/arrayPluck.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayPluck'>;
}
declare module 'd2-utilizr/src/arrayRepeat.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayRepeat'>;
}
declare module 'd2-utilizr/src/arrayReplace.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayReplace'>;
}
declare module 'd2-utilizr/src/arraySort.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arraySort'>;
}
declare module 'd2-utilizr/src/arrayTo.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayTo'>;
}
declare module 'd2-utilizr/src/arrayUnique.js' {
  declare module.exports: $Exports<'d2-utilizr/src/arrayUnique'>;
}
declare module 'd2-utilizr/src/camelCaseToUnderscores.js' {
  declare module.exports: $Exports<'d2-utilizr/src/camelCaseToUnderscores'>;
}
declare module 'd2-utilizr/src/clone.js' {
  declare module.exports: $Exports<'d2-utilizr/src/clone'>;
}
declare module 'd2-utilizr/src/index' {
  declare module.exports: $Exports<'d2-utilizr/src'>;
}
declare module 'd2-utilizr/src/index.js' {
  declare module.exports: $Exports<'d2-utilizr/src'>;
}
declare module 'd2-utilizr/src/isArray.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isArray'>;
}
declare module 'd2-utilizr/src/isArrayOfStrings.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isArrayOfStrings'>;
}
declare module 'd2-utilizr/src/isBoolean.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isBoolean'>;
}
declare module 'd2-utilizr/src/isDefined.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isDefined'>;
}
declare module 'd2-utilizr/src/isEmpty.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isEmpty'>;
}
declare module 'd2-utilizr/src/isFunction.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isFunction'>;
}
declare module 'd2-utilizr/src/isIE.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isIE'>;
}
declare module 'd2-utilizr/src/isInteger.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isInteger'>;
}
declare module 'd2-utilizr/src/isIterable.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isIterable'>;
}
declare module 'd2-utilizr/src/isNumber.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isNumber'>;
}
declare module 'd2-utilizr/src/isNumeric.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isNumeric'>;
}
declare module 'd2-utilizr/src/isObject.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isObject'>;
}
declare module 'd2-utilizr/src/isPrimitive.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isPrimitive'>;
}
declare module 'd2-utilizr/src/isString.js' {
  declare module.exports: $Exports<'d2-utilizr/src/isString'>;
}
declare module 'd2-utilizr/src/noop.js' {
  declare module.exports: $Exports<'d2-utilizr/src/noop'>;
}
declare module 'd2-utilizr/src/numberConstrain.js' {
  declare module.exports: $Exports<'d2-utilizr/src/numberConstrain'>;
}
declare module 'd2-utilizr/src/numberDecimals.js' {
  declare module.exports: $Exports<'d2-utilizr/src/numberDecimals'>;
}
declare module 'd2-utilizr/src/numberIsFinite.js' {
  declare module.exports: $Exports<'d2-utilizr/src/numberIsFinite'>;
}
declare module 'd2-utilizr/src/numberToFixed.js' {
  declare module.exports: $Exports<'d2-utilizr/src/numberToFixed'>;
}
declare module 'd2-utilizr/src/objectApplyIf.js' {
  declare module.exports: $Exports<'d2-utilizr/src/objectApplyIf'>;
}
declare module 'd2-utilizr/src/objectClean.js' {
  declare module.exports: $Exports<'d2-utilizr/src/objectClean'>;
}
declare module 'd2-utilizr/src/stringReplaceAll.js' {
  declare module.exports: $Exports<'d2-utilizr/src/stringReplaceAll'>;
}
declare module 'd2-utilizr/src/stringTrim.js' {
  declare module.exports: $Exports<'d2-utilizr/src/stringTrim'>;
}
declare module 'd2-utilizr/src/uuid.js' {
  declare module.exports: $Exports<'d2-utilizr/src/uuid'>;
}
