// flow-typed signature: f59a6bb50094907a673552a0f3274186
// flow-typed version: <<STUB>>/d2_v^31/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd2/lib/analytics/Analytics' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsAggregate' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsBase' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsEvents' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsRequest' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsRequestBase' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsRequestDimensionsMixin' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsRequestFiltersMixin' {
  declare module.exports: any;
}

declare module 'd2/lib/analytics/AnalyticsRequestPropertiesMixin' {
  declare module.exports: any;
}

declare module 'd2/lib/api/Api' {
  declare module.exports: any;
}

declare module 'd2/lib/config' {
  declare module.exports: any;
}

declare module 'd2/lib/current-user/CurrentUser' {
  declare module.exports: any;
}

declare module 'd2/lib/current-user/UserAuthorities' {
  declare module.exports: any;
}

declare module 'd2/lib/current-user/UserSettings' {
  declare module.exports: any;
}

declare module 'd2/lib/d2-browser' {
  declare module.exports: any;
}

declare module 'd2/lib/d2-browser.min' {
  declare module.exports: any;
}

declare module 'd2/lib/d2' {
  declare module.exports: any;
}

declare module 'd2/lib/datastore/BaseStore' {
  declare module.exports: any;
}

declare module 'd2/lib/datastore/BaseStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/lib/datastore/DataStore' {
  declare module.exports: any;
}

declare module 'd2/lib/datastore/DataStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/lib/datastore/UserDataStore' {
  declare module.exports: any;
}

declare module 'd2/lib/datastore/UserDataStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/lib/defaultConfig' {
  declare module.exports: any;
}

declare module 'd2/lib/geofeatures/GeoFeatures' {
  declare module.exports: any;
}

declare module 'd2/lib/i18n/I18n' {
  declare module.exports: any;
}

declare module 'd2/lib/lib/check' {
  declare module.exports: any;
}

declare module 'd2/lib/lib/SchemaTypes' {
  declare module.exports: any;
}

declare module 'd2/lib/lib/utils' {
  declare module.exports: any;
}

declare module 'd2/lib/logger/Logger' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/category' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/categoryOptionGroupSet' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/dataElement' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/dataElementGroupSet' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/dataSet' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/externalMapLayer' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/organisationUnitGroupSet' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/program' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/programNotificationTemplate' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/validationNotificationTemplate' {
  declare module.exports: any;
}

declare module 'd2/lib/model/config/model-defaults/validationRule' {
  declare module.exports: any;
}

declare module 'd2/lib/model/Filter' {
  declare module.exports: any;
}

declare module 'd2/lib/model/Filters' {
  declare module.exports: any;
}

declare module 'd2/lib/model/helpers/attibutes' {
  declare module.exports: any;
}

declare module 'd2/lib/model/helpers/json' {
  declare module.exports: any;
}

declare module 'd2/lib/model/helpers/models' {
  declare module.exports: any;
}

declare module 'd2/lib/model' {
  declare module.exports: any;
}

declare module 'd2/lib/model/Model' {
  declare module.exports: any;
}

declare module 'd2/lib/model/ModelBase' {
  declare module.exports: any;
}

declare module 'd2/lib/model/ModelCollection' {
  declare module.exports: any;
}

declare module 'd2/lib/model/ModelCollectionProperty' {
  declare module.exports: any;
}

declare module 'd2/lib/model/ModelDefinition' {
  declare module.exports: any;
}

declare module 'd2/lib/model/ModelDefinitions' {
  declare module.exports: any;
}

declare module 'd2/lib/model/ModelValidation' {
  declare module.exports: any;
}

declare module 'd2/lib/pager/Pager' {
  declare module.exports: any;
}

declare module 'd2/lib/period/formatters' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/bi-monthly' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/daily' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/financial-april' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/financial-july' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/financial-october' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/monthly' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/quarterly' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/six-monthly-april' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/six-monthly' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/weekly' {
  declare module.exports: any;
}

declare module 'd2/lib/period/generators/yearly' {
  declare module.exports: any;
}

declare module 'd2/lib/period/helpers' {
  declare module.exports: any;
}

declare module 'd2/lib/period/parser' {
  declare module.exports: any;
}

declare module 'd2/lib/system/System' {
  declare module.exports: any;
}

declare module 'd2/lib/system/SystemConfiguration' {
  declare module.exports: any;
}

declare module 'd2/lib/system/SystemSettings' {
  declare module.exports: any;
}

declare module 'd2/lib/uid' {
  declare module.exports: any;
}

declare module 'd2/src/d2' {
  declare module.exports: any;
}

declare module 'd2/webpack.config' {
  declare module.exports: any;
}

declare module 'd2/webpack.config.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd2/lib/analytics/Analytics.js' {
  declare module.exports: $Exports<'d2/lib/analytics/Analytics'>;
}
declare module 'd2/lib/analytics/AnalyticsAggregate.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsAggregate'>;
}
declare module 'd2/lib/analytics/AnalyticsBase.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsBase'>;
}
declare module 'd2/lib/analytics/AnalyticsEvents.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsEvents'>;
}
declare module 'd2/lib/analytics/AnalyticsRequest.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsRequest'>;
}
declare module 'd2/lib/analytics/AnalyticsRequestBase.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsRequestBase'>;
}
declare module 'd2/lib/analytics/AnalyticsRequestDimensionsMixin.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsRequestDimensionsMixin'>;
}
declare module 'd2/lib/analytics/AnalyticsRequestFiltersMixin.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsRequestFiltersMixin'>;
}
declare module 'd2/lib/analytics/AnalyticsRequestPropertiesMixin.js' {
  declare module.exports: $Exports<'d2/lib/analytics/AnalyticsRequestPropertiesMixin'>;
}
declare module 'd2/lib/api/Api.js' {
  declare module.exports: $Exports<'d2/lib/api/Api'>;
}
declare module 'd2/lib/config.js' {
  declare module.exports: $Exports<'d2/lib/config'>;
}
declare module 'd2/lib/current-user/CurrentUser.js' {
  declare module.exports: $Exports<'d2/lib/current-user/CurrentUser'>;
}
declare module 'd2/lib/current-user/UserAuthorities.js' {
  declare module.exports: $Exports<'d2/lib/current-user/UserAuthorities'>;
}
declare module 'd2/lib/current-user/UserSettings.js' {
  declare module.exports: $Exports<'d2/lib/current-user/UserSettings'>;
}
declare module 'd2/lib/d2-browser.js' {
  declare module.exports: $Exports<'d2/lib/d2-browser'>;
}
declare module 'd2/lib/d2-browser.min.js' {
  declare module.exports: $Exports<'d2/lib/d2-browser.min'>;
}
declare module 'd2/lib/d2.js' {
  declare module.exports: $Exports<'d2/lib/d2'>;
}
declare module 'd2/lib/datastore/BaseStore.js' {
  declare module.exports: $Exports<'d2/lib/datastore/BaseStore'>;
}
declare module 'd2/lib/datastore/BaseStoreNamespace.js' {
  declare module.exports: $Exports<'d2/lib/datastore/BaseStoreNamespace'>;
}
declare module 'd2/lib/datastore/DataStore.js' {
  declare module.exports: $Exports<'d2/lib/datastore/DataStore'>;
}
declare module 'd2/lib/datastore/DataStoreNamespace.js' {
  declare module.exports: $Exports<'d2/lib/datastore/DataStoreNamespace'>;
}
declare module 'd2/lib/datastore/UserDataStore.js' {
  declare module.exports: $Exports<'d2/lib/datastore/UserDataStore'>;
}
declare module 'd2/lib/datastore/UserDataStoreNamespace.js' {
  declare module.exports: $Exports<'d2/lib/datastore/UserDataStoreNamespace'>;
}
declare module 'd2/lib/defaultConfig.js' {
  declare module.exports: $Exports<'d2/lib/defaultConfig'>;
}
declare module 'd2/lib/geofeatures/GeoFeatures.js' {
  declare module.exports: $Exports<'d2/lib/geofeatures/GeoFeatures'>;
}
declare module 'd2/lib/i18n/I18n.js' {
  declare module.exports: $Exports<'d2/lib/i18n/I18n'>;
}
declare module 'd2/lib/lib/check.js' {
  declare module.exports: $Exports<'d2/lib/lib/check'>;
}
declare module 'd2/lib/lib/SchemaTypes.js' {
  declare module.exports: $Exports<'d2/lib/lib/SchemaTypes'>;
}
declare module 'd2/lib/lib/utils.js' {
  declare module.exports: $Exports<'d2/lib/lib/utils'>;
}
declare module 'd2/lib/logger/Logger.js' {
  declare module.exports: $Exports<'d2/lib/logger/Logger'>;
}
declare module 'd2/lib/model/config/index' {
  declare module.exports: $Exports<'d2/lib/model/config'>;
}
declare module 'd2/lib/model/config/index.js' {
  declare module.exports: $Exports<'d2/lib/model/config'>;
}
declare module 'd2/lib/model/config/model-defaults/category.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/category'>;
}
declare module 'd2/lib/model/config/model-defaults/categoryOptionGroupSet.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/categoryOptionGroupSet'>;
}
declare module 'd2/lib/model/config/model-defaults/dataElement.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/dataElement'>;
}
declare module 'd2/lib/model/config/model-defaults/dataElementGroupSet.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/dataElementGroupSet'>;
}
declare module 'd2/lib/model/config/model-defaults/dataSet.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/dataSet'>;
}
declare module 'd2/lib/model/config/model-defaults/externalMapLayer.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/externalMapLayer'>;
}
declare module 'd2/lib/model/config/model-defaults/organisationUnitGroupSet.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/organisationUnitGroupSet'>;
}
declare module 'd2/lib/model/config/model-defaults/program.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/program'>;
}
declare module 'd2/lib/model/config/model-defaults/programNotificationTemplate.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/programNotificationTemplate'>;
}
declare module 'd2/lib/model/config/model-defaults/validationNotificationTemplate.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/validationNotificationTemplate'>;
}
declare module 'd2/lib/model/config/model-defaults/validationRule.js' {
  declare module.exports: $Exports<'d2/lib/model/config/model-defaults/validationRule'>;
}
declare module 'd2/lib/model/Filter.js' {
  declare module.exports: $Exports<'d2/lib/model/Filter'>;
}
declare module 'd2/lib/model/Filters.js' {
  declare module.exports: $Exports<'d2/lib/model/Filters'>;
}
declare module 'd2/lib/model/helpers/attibutes.js' {
  declare module.exports: $Exports<'d2/lib/model/helpers/attibutes'>;
}
declare module 'd2/lib/model/helpers/json.js' {
  declare module.exports: $Exports<'d2/lib/model/helpers/json'>;
}
declare module 'd2/lib/model/helpers/models.js' {
  declare module.exports: $Exports<'d2/lib/model/helpers/models'>;
}
declare module 'd2/lib/model/index' {
  declare module.exports: $Exports<'d2/lib/model'>;
}
declare module 'd2/lib/model/index.js' {
  declare module.exports: $Exports<'d2/lib/model'>;
}
declare module 'd2/lib/model/Model.js' {
  declare module.exports: $Exports<'d2/lib/model/Model'>;
}
declare module 'd2/lib/model/ModelBase.js' {
  declare module.exports: $Exports<'d2/lib/model/ModelBase'>;
}
declare module 'd2/lib/model/ModelCollection.js' {
  declare module.exports: $Exports<'d2/lib/model/ModelCollection'>;
}
declare module 'd2/lib/model/ModelCollectionProperty.js' {
  declare module.exports: $Exports<'d2/lib/model/ModelCollectionProperty'>;
}
declare module 'd2/lib/model/ModelDefinition.js' {
  declare module.exports: $Exports<'d2/lib/model/ModelDefinition'>;
}
declare module 'd2/lib/model/ModelDefinitions.js' {
  declare module.exports: $Exports<'d2/lib/model/ModelDefinitions'>;
}
declare module 'd2/lib/model/ModelValidation.js' {
  declare module.exports: $Exports<'d2/lib/model/ModelValidation'>;
}
declare module 'd2/lib/pager/Pager.js' {
  declare module.exports: $Exports<'d2/lib/pager/Pager'>;
}
declare module 'd2/lib/period/formatters.js' {
  declare module.exports: $Exports<'d2/lib/period/formatters'>;
}
declare module 'd2/lib/period/generators/bi-monthly.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/bi-monthly'>;
}
declare module 'd2/lib/period/generators/daily.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/daily'>;
}
declare module 'd2/lib/period/generators/financial-april.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/financial-april'>;
}
declare module 'd2/lib/period/generators/financial-july.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/financial-july'>;
}
declare module 'd2/lib/period/generators/financial-october.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/financial-october'>;
}
declare module 'd2/lib/period/generators/index' {
  declare module.exports: $Exports<'d2/lib/period/generators'>;
}
declare module 'd2/lib/period/generators/index.js' {
  declare module.exports: $Exports<'d2/lib/period/generators'>;
}
declare module 'd2/lib/period/generators/monthly.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/monthly'>;
}
declare module 'd2/lib/period/generators/quarterly.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/quarterly'>;
}
declare module 'd2/lib/period/generators/six-monthly-april.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/six-monthly-april'>;
}
declare module 'd2/lib/period/generators/six-monthly.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/six-monthly'>;
}
declare module 'd2/lib/period/generators/weekly.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/weekly'>;
}
declare module 'd2/lib/period/generators/yearly.js' {
  declare module.exports: $Exports<'d2/lib/period/generators/yearly'>;
}
declare module 'd2/lib/period/helpers.js' {
  declare module.exports: $Exports<'d2/lib/period/helpers'>;
}
declare module 'd2/lib/period/parser.js' {
  declare module.exports: $Exports<'d2/lib/period/parser'>;
}
declare module 'd2/lib/system/System.js' {
  declare module.exports: $Exports<'d2/lib/system/System'>;
}
declare module 'd2/lib/system/SystemConfiguration.js' {
  declare module.exports: $Exports<'d2/lib/system/SystemConfiguration'>;
}
declare module 'd2/lib/system/SystemSettings.js' {
  declare module.exports: $Exports<'d2/lib/system/SystemSettings'>;
}
declare module 'd2/lib/uid.js' {
  declare module.exports: $Exports<'d2/lib/uid'>;
}
declare module 'd2/src/d2.js' {
  declare module.exports: $Exports<'d2/src/d2'>;
}
declare module 'd2/webpack.config.js' {
  declare module.exports: $Exports<'d2/webpack.config'>;
}
declare module 'd2/webpack.config.min.js' {
  declare module.exports: $Exports<'d2/webpack.config.min'>;
}
