// flow-typed signature: e0668ad3e1dec6a0658cb4c73e7a9da1
// flow-typed version: <<STUB>>/d2_v^31/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd2/analytics/Analytics' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsAggregate' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsBase' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsEvents' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsRequest' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsRequestBase' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsRequestDimensionsMixin' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsRequestFiltersMixin' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsRequestPropertiesMixin' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsResponse' {
  declare module.exports: any;
}

declare module 'd2/analytics/AnalyticsResponseHeader' {
  declare module.exports: any;
}

declare module 'd2/api/Api' {
  declare module.exports: any;
}

declare module 'd2/config' {
  declare module.exports: any;
}

declare module 'd2/current-user/CurrentUser' {
  declare module.exports: any;
}

declare module 'd2/current-user/UserAuthorities' {
  declare module.exports: any;
}

declare module 'd2/current-user/UserSettings' {
  declare module.exports: any;
}

declare module 'd2/d2-browser' {
  declare module.exports: any;
}

declare module 'd2/d2-browser.min' {
  declare module.exports: any;
}

declare module 'd2/d2' {
  declare module.exports: any;
}

declare module 'd2/datastore/BaseStore' {
  declare module.exports: any;
}

declare module 'd2/datastore/BaseStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/datastore/DataStore' {
  declare module.exports: any;
}

declare module 'd2/datastore/DataStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/datastore/UserDataStore' {
  declare module.exports: any;
}

declare module 'd2/datastore/UserDataStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/defaultConfig' {
  declare module.exports: any;
}

declare module 'd2/docs/scripts/collapse' {
  declare module.exports: any;
}

declare module 'd2/docs/scripts/jquery-3.1.1.min' {
  declare module.exports: any;
}

declare module 'd2/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'd2/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'd2/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'd2/docs/scripts/search' {
  declare module.exports: any;
}

declare module 'd2/geofeatures/GeoFeatures' {
  declare module.exports: any;
}

declare module 'd2/i18n/I18n' {
  declare module.exports: any;
}

declare module 'd2/lib/check' {
  declare module.exports: any;
}

declare module 'd2/lib/SchemaTypes' {
  declare module.exports: any;
}

declare module 'd2/lib/utils' {
  declare module.exports: any;
}

declare module 'd2/logger/Logger' {
  declare module.exports: any;
}

declare module 'd2/model/config' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/category' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/categoryOptionGroupSet' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/dataElement' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/dataElementGroupSet' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/dataSet' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/externalMapLayer' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/organisationUnitGroupSet' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/program' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/programNotificationTemplate' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/validationNotificationTemplate' {
  declare module.exports: any;
}

declare module 'd2/model/config/model-defaults/validationRule' {
  declare module.exports: any;
}

declare module 'd2/model/Filter' {
  declare module.exports: any;
}

declare module 'd2/model/Filters' {
  declare module.exports: any;
}

declare module 'd2/model/helpers/attibutes' {
  declare module.exports: any;
}

declare module 'd2/model/helpers/json' {
  declare module.exports: any;
}

declare module 'd2/model/helpers/models' {
  declare module.exports: any;
}

declare module 'd2/model' {
  declare module.exports: any;
}

declare module 'd2/model/Model' {
  declare module.exports: any;
}

declare module 'd2/model/ModelBase' {
  declare module.exports: any;
}

declare module 'd2/model/ModelCollection' {
  declare module.exports: any;
}

declare module 'd2/model/ModelCollectionProperty' {
  declare module.exports: any;
}

declare module 'd2/model/ModelDefinition' {
  declare module.exports: any;
}

declare module 'd2/model/ModelDefinitions' {
  declare module.exports: any;
}

declare module 'd2/model/ModelValidation' {
  declare module.exports: any;
}

declare module 'd2/pager/Pager' {
  declare module.exports: any;
}

declare module 'd2/period/formatters' {
  declare module.exports: any;
}

declare module 'd2/period/generators/bi-monthly' {
  declare module.exports: any;
}

declare module 'd2/period/generators/daily' {
  declare module.exports: any;
}

declare module 'd2/period/generators/financial-april' {
  declare module.exports: any;
}

declare module 'd2/period/generators/financial-july' {
  declare module.exports: any;
}

declare module 'd2/period/generators/financial-october' {
  declare module.exports: any;
}

declare module 'd2/period/generators' {
  declare module.exports: any;
}

declare module 'd2/period/generators/monthly' {
  declare module.exports: any;
}

declare module 'd2/period/generators/quarterly' {
  declare module.exports: any;
}

declare module 'd2/period/generators/six-monthly-april' {
  declare module.exports: any;
}

declare module 'd2/period/generators/six-monthly' {
  declare module.exports: any;
}

declare module 'd2/period/generators/weekly' {
  declare module.exports: any;
}

declare module 'd2/period/generators/yearly' {
  declare module.exports: any;
}

declare module 'd2/period/helpers' {
  declare module.exports: any;
}

declare module 'd2/period/parser' {
  declare module.exports: any;
}

declare module 'd2/src/__fixtures__/fixtures' {
  declare module.exports: any;
}

declare module 'd2/src/__tests__/config.spec' {
  declare module.exports: any;
}

declare module 'd2/src/__tests__/d2.spec' {
  declare module.exports: any;
}

declare module 'd2/src/__tests__/uid.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/Analytics.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsAggregate.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsBase.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsEvents.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsRequest.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsRequestBase.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsResponse.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/__tests__/AnalyticsResponseHeader.spec' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/Analytics' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsAggregate' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsBase' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsEvents' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsRequest' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsRequestBase' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsRequestDimensionsMixin' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsRequestFiltersMixin' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsRequestPropertiesMixin' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsResponse' {
  declare module.exports: any;
}

declare module 'd2/src/analytics/AnalyticsResponseHeader' {
  declare module.exports: any;
}

declare module 'd2/src/api/__mocks__/Api' {
  declare module.exports: any;
}

declare module 'd2/src/api/__tests__/Api.spec' {
  declare module.exports: any;
}

declare module 'd2/src/api/Api' {
  declare module.exports: any;
}

declare module 'd2/src/config' {
  declare module.exports: any;
}

declare module 'd2/src/current-user/__tests__/CurrentUser.spec' {
  declare module.exports: any;
}

declare module 'd2/src/current-user/__tests__/UserAuthorities.spec' {
  declare module.exports: any;
}

declare module 'd2/src/current-user/__tests__/UserSettings.spec' {
  declare module.exports: any;
}

declare module 'd2/src/current-user/CurrentUser' {
  declare module.exports: any;
}

declare module 'd2/src/current-user/UserAuthorities' {
  declare module.exports: any;
}

declare module 'd2/src/current-user/UserSettings' {
  declare module.exports: any;
}

declare module 'd2/src/d2' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/__tests__/BaseStore.spec' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/__tests__/BaseStoreNamespace.spec' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/__tests__/DataStore.spec' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/__tests__/DatastoreNamespace.spec' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/__tests__/UserDataStore.spec' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/__tests__/UserDatastoreNamespace.spec' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/BaseStore' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/BaseStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/DataStore' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/DataStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/UserDataStore' {
  declare module.exports: any;
}

declare module 'd2/src/datastore/UserDataStoreNamespace' {
  declare module.exports: any;
}

declare module 'd2/src/defaultConfig' {
  declare module.exports: any;
}

declare module 'd2/src/geofeatures/__tests__/GeoFeatures.spec' {
  declare module.exports: any;
}

declare module 'd2/src/geofeatures/GeoFeatures' {
  declare module.exports: any;
}

declare module 'd2/src/i18n/__tests__/I18n.spec' {
  declare module.exports: any;
}

declare module 'd2/src/i18n/I18n' {
  declare module.exports: any;
}

declare module 'd2/src/lib/__tests__/check.spec' {
  declare module.exports: any;
}

declare module 'd2/src/lib/__tests__/utils.spec' {
  declare module.exports: any;
}

declare module 'd2/src/lib/check' {
  declare module.exports: any;
}

declare module 'd2/src/lib/SchemaTypes' {
  declare module.exports: any;
}

declare module 'd2/src/lib/utils' {
  declare module.exports: any;
}

declare module 'd2/src/logger/__tests__/Logger.spec' {
  declare module.exports: any;
}

declare module 'd2/src/logger/Logger' {
  declare module.exports: any;
}

declare module 'd2/src/model/__mocks__/Model' {
  declare module.exports: any;
}

declare module 'd2/src/model/__mocks__/ModelCollection' {
  declare module.exports: any;
}

declare module 'd2/src/model/__mocks__/ModelCollectionProperty' {
  declare module.exports: any;
}

declare module 'd2/src/model/__mocks__/ModelValidation' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/Filter.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/Filters.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/Model.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/ModelBase.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/ModelCollection.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/ModelCollectionProperty.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/ModelDefinition.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/ModelDefinitions.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/__tests__/ModelValidation.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/config' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/__tests__/program.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/__tests__/programNotificationTemplate.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/__tests__/validationRule.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/category' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/categoryOptionGroupSet' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/dataElement' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/dataElementGroupSet' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/dataSet' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/externalMapLayer' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/organisationUnitGroupSet' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/program' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/programNotificationTemplate' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/validationNotificationTemplate' {
  declare module.exports: any;
}

declare module 'd2/src/model/config/model-defaults/validationRule' {
  declare module.exports: any;
}

declare module 'd2/src/model/Filter' {
  declare module.exports: any;
}

declare module 'd2/src/model/Filters' {
  declare module.exports: any;
}

declare module 'd2/src/model/helpers/__tests__/json.spec' {
  declare module.exports: any;
}

declare module 'd2/src/model/helpers/attibutes' {
  declare module.exports: any;
}

declare module 'd2/src/model/helpers/json' {
  declare module.exports: any;
}

declare module 'd2/src/model/helpers/models' {
  declare module.exports: any;
}

declare module 'd2/src/model' {
  declare module.exports: any;
}

declare module 'd2/src/model/Model' {
  declare module.exports: any;
}

declare module 'd2/src/model/ModelBase' {
  declare module.exports: any;
}

declare module 'd2/src/model/ModelCollection' {
  declare module.exports: any;
}

declare module 'd2/src/model/ModelCollectionProperty' {
  declare module.exports: any;
}

declare module 'd2/src/model/ModelDefinition' {
  declare module.exports: any;
}

declare module 'd2/src/model/ModelDefinitions' {
  declare module.exports: any;
}

declare module 'd2/src/model/ModelValidation' {
  declare module.exports: any;
}

declare module 'd2/src/pager/__tests__/Pager.spec' {
  declare module.exports: any;
}

declare module 'd2/src/pager/Pager' {
  declare module.exports: any;
}

declare module 'd2/src/period/__tests__/helpers.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/__tests__/parser.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/formatters' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/bi-monthly.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/daily.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/financial-april.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/financial-july.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/financial-october.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/monthly.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/quarterly.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/six-monthly-april.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/six-monthly.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/weekly.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/__tests__/yearly.spec' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/bi-monthly' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/daily' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/financial-april' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/financial-july' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/financial-october' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/monthly' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/quarterly' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/six-monthly-april' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/six-monthly' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/weekly' {
  declare module.exports: any;
}

declare module 'd2/src/period/generators/yearly' {
  declare module.exports: any;
}

declare module 'd2/src/period/helpers' {
  declare module.exports: any;
}

declare module 'd2/src/period/parser' {
  declare module.exports: any;
}

declare module 'd2/src/system/__tests__/System.spec' {
  declare module.exports: any;
}

declare module 'd2/src/system/__tests__/SystemConfiguration.spec' {
  declare module.exports: any;
}

declare module 'd2/src/system/__tests__/SystemSettings.spec' {
  declare module.exports: any;
}

declare module 'd2/src/system/System' {
  declare module.exports: any;
}

declare module 'd2/src/system/SystemConfiguration' {
  declare module.exports: any;
}

declare module 'd2/src/system/SystemSettings' {
  declare module.exports: any;
}

declare module 'd2/src/uid' {
  declare module.exports: any;
}

declare module 'd2/system/System' {
  declare module.exports: any;
}

declare module 'd2/system/SystemConfiguration' {
  declare module.exports: any;
}

declare module 'd2/system/SystemSettings' {
  declare module.exports: any;
}

declare module 'd2/uid' {
  declare module.exports: any;
}

declare module 'd2/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'd2/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd2/analytics/Analytics.js' {
  declare module.exports: $Exports<'d2/analytics/Analytics'>;
}
declare module 'd2/analytics/AnalyticsAggregate.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsAggregate'>;
}
declare module 'd2/analytics/AnalyticsBase.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsBase'>;
}
declare module 'd2/analytics/AnalyticsEvents.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsEvents'>;
}
declare module 'd2/analytics/AnalyticsRequest.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsRequest'>;
}
declare module 'd2/analytics/AnalyticsRequestBase.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsRequestBase'>;
}
declare module 'd2/analytics/AnalyticsRequestDimensionsMixin.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsRequestDimensionsMixin'>;
}
declare module 'd2/analytics/AnalyticsRequestFiltersMixin.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsRequestFiltersMixin'>;
}
declare module 'd2/analytics/AnalyticsRequestPropertiesMixin.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsRequestPropertiesMixin'>;
}
declare module 'd2/analytics/AnalyticsResponse.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsResponse'>;
}
declare module 'd2/analytics/AnalyticsResponseHeader.js' {
  declare module.exports: $Exports<'d2/analytics/AnalyticsResponseHeader'>;
}
declare module 'd2/api/Api.js' {
  declare module.exports: $Exports<'d2/api/Api'>;
}
declare module 'd2/config.js' {
  declare module.exports: $Exports<'d2/config'>;
}
declare module 'd2/current-user/CurrentUser.js' {
  declare module.exports: $Exports<'d2/current-user/CurrentUser'>;
}
declare module 'd2/current-user/UserAuthorities.js' {
  declare module.exports: $Exports<'d2/current-user/UserAuthorities'>;
}
declare module 'd2/current-user/UserSettings.js' {
  declare module.exports: $Exports<'d2/current-user/UserSettings'>;
}
declare module 'd2/d2-browser.js' {
  declare module.exports: $Exports<'d2/d2-browser'>;
}
declare module 'd2/d2-browser.min.js' {
  declare module.exports: $Exports<'d2/d2-browser.min'>;
}
declare module 'd2/d2.js' {
  declare module.exports: $Exports<'d2/d2'>;
}
declare module 'd2/datastore/BaseStore.js' {
  declare module.exports: $Exports<'d2/datastore/BaseStore'>;
}
declare module 'd2/datastore/BaseStoreNamespace.js' {
  declare module.exports: $Exports<'d2/datastore/BaseStoreNamespace'>;
}
declare module 'd2/datastore/DataStore.js' {
  declare module.exports: $Exports<'d2/datastore/DataStore'>;
}
declare module 'd2/datastore/DataStoreNamespace.js' {
  declare module.exports: $Exports<'d2/datastore/DataStoreNamespace'>;
}
declare module 'd2/datastore/UserDataStore.js' {
  declare module.exports: $Exports<'d2/datastore/UserDataStore'>;
}
declare module 'd2/datastore/UserDataStoreNamespace.js' {
  declare module.exports: $Exports<'d2/datastore/UserDataStoreNamespace'>;
}
declare module 'd2/defaultConfig.js' {
  declare module.exports: $Exports<'d2/defaultConfig'>;
}
declare module 'd2/docs/scripts/collapse.js' {
  declare module.exports: $Exports<'d2/docs/scripts/collapse'>;
}
declare module 'd2/docs/scripts/jquery-3.1.1.min.js' {
  declare module.exports: $Exports<'d2/docs/scripts/jquery-3.1.1.min'>;
}
declare module 'd2/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'d2/docs/scripts/linenumber'>;
}
declare module 'd2/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'d2/docs/scripts/prettify/lang-css'>;
}
declare module 'd2/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'d2/docs/scripts/prettify/prettify'>;
}
declare module 'd2/docs/scripts/search.js' {
  declare module.exports: $Exports<'d2/docs/scripts/search'>;
}
declare module 'd2/geofeatures/GeoFeatures.js' {
  declare module.exports: $Exports<'d2/geofeatures/GeoFeatures'>;
}
declare module 'd2/i18n/I18n.js' {
  declare module.exports: $Exports<'d2/i18n/I18n'>;
}
declare module 'd2/lib/check.js' {
  declare module.exports: $Exports<'d2/lib/check'>;
}
declare module 'd2/lib/SchemaTypes.js' {
  declare module.exports: $Exports<'d2/lib/SchemaTypes'>;
}
declare module 'd2/lib/utils.js' {
  declare module.exports: $Exports<'d2/lib/utils'>;
}
declare module 'd2/logger/Logger.js' {
  declare module.exports: $Exports<'d2/logger/Logger'>;
}
declare module 'd2/model/config/index' {
  declare module.exports: $Exports<'d2/model/config'>;
}
declare module 'd2/model/config/index.js' {
  declare module.exports: $Exports<'d2/model/config'>;
}
declare module 'd2/model/config/model-defaults/category.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/category'>;
}
declare module 'd2/model/config/model-defaults/categoryOptionGroupSet.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/categoryOptionGroupSet'>;
}
declare module 'd2/model/config/model-defaults/dataElement.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/dataElement'>;
}
declare module 'd2/model/config/model-defaults/dataElementGroupSet.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/dataElementGroupSet'>;
}
declare module 'd2/model/config/model-defaults/dataSet.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/dataSet'>;
}
declare module 'd2/model/config/model-defaults/externalMapLayer.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/externalMapLayer'>;
}
declare module 'd2/model/config/model-defaults/organisationUnitGroupSet.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/organisationUnitGroupSet'>;
}
declare module 'd2/model/config/model-defaults/program.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/program'>;
}
declare module 'd2/model/config/model-defaults/programNotificationTemplate.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/programNotificationTemplate'>;
}
declare module 'd2/model/config/model-defaults/validationNotificationTemplate.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/validationNotificationTemplate'>;
}
declare module 'd2/model/config/model-defaults/validationRule.js' {
  declare module.exports: $Exports<'d2/model/config/model-defaults/validationRule'>;
}
declare module 'd2/model/Filter.js' {
  declare module.exports: $Exports<'d2/model/Filter'>;
}
declare module 'd2/model/Filters.js' {
  declare module.exports: $Exports<'d2/model/Filters'>;
}
declare module 'd2/model/helpers/attibutes.js' {
  declare module.exports: $Exports<'d2/model/helpers/attibutes'>;
}
declare module 'd2/model/helpers/json.js' {
  declare module.exports: $Exports<'d2/model/helpers/json'>;
}
declare module 'd2/model/helpers/models.js' {
  declare module.exports: $Exports<'d2/model/helpers/models'>;
}
declare module 'd2/model/index' {
  declare module.exports: $Exports<'d2/model'>;
}
declare module 'd2/model/index.js' {
  declare module.exports: $Exports<'d2/model'>;
}
declare module 'd2/model/Model.js' {
  declare module.exports: $Exports<'d2/model/Model'>;
}
declare module 'd2/model/ModelBase.js' {
  declare module.exports: $Exports<'d2/model/ModelBase'>;
}
declare module 'd2/model/ModelCollection.js' {
  declare module.exports: $Exports<'d2/model/ModelCollection'>;
}
declare module 'd2/model/ModelCollectionProperty.js' {
  declare module.exports: $Exports<'d2/model/ModelCollectionProperty'>;
}
declare module 'd2/model/ModelDefinition.js' {
  declare module.exports: $Exports<'d2/model/ModelDefinition'>;
}
declare module 'd2/model/ModelDefinitions.js' {
  declare module.exports: $Exports<'d2/model/ModelDefinitions'>;
}
declare module 'd2/model/ModelValidation.js' {
  declare module.exports: $Exports<'d2/model/ModelValidation'>;
}
declare module 'd2/pager/Pager.js' {
  declare module.exports: $Exports<'d2/pager/Pager'>;
}
declare module 'd2/period/formatters.js' {
  declare module.exports: $Exports<'d2/period/formatters'>;
}
declare module 'd2/period/generators/bi-monthly.js' {
  declare module.exports: $Exports<'d2/period/generators/bi-monthly'>;
}
declare module 'd2/period/generators/daily.js' {
  declare module.exports: $Exports<'d2/period/generators/daily'>;
}
declare module 'd2/period/generators/financial-april.js' {
  declare module.exports: $Exports<'d2/period/generators/financial-april'>;
}
declare module 'd2/period/generators/financial-july.js' {
  declare module.exports: $Exports<'d2/period/generators/financial-july'>;
}
declare module 'd2/period/generators/financial-october.js' {
  declare module.exports: $Exports<'d2/period/generators/financial-october'>;
}
declare module 'd2/period/generators/index' {
  declare module.exports: $Exports<'d2/period/generators'>;
}
declare module 'd2/period/generators/index.js' {
  declare module.exports: $Exports<'d2/period/generators'>;
}
declare module 'd2/period/generators/monthly.js' {
  declare module.exports: $Exports<'d2/period/generators/monthly'>;
}
declare module 'd2/period/generators/quarterly.js' {
  declare module.exports: $Exports<'d2/period/generators/quarterly'>;
}
declare module 'd2/period/generators/six-monthly-april.js' {
  declare module.exports: $Exports<'d2/period/generators/six-monthly-april'>;
}
declare module 'd2/period/generators/six-monthly.js' {
  declare module.exports: $Exports<'d2/period/generators/six-monthly'>;
}
declare module 'd2/period/generators/weekly.js' {
  declare module.exports: $Exports<'d2/period/generators/weekly'>;
}
declare module 'd2/period/generators/yearly.js' {
  declare module.exports: $Exports<'d2/period/generators/yearly'>;
}
declare module 'd2/period/helpers.js' {
  declare module.exports: $Exports<'d2/period/helpers'>;
}
declare module 'd2/period/parser.js' {
  declare module.exports: $Exports<'d2/period/parser'>;
}
declare module 'd2/src/__fixtures__/fixtures.js' {
  declare module.exports: $Exports<'d2/src/__fixtures__/fixtures'>;
}
declare module 'd2/src/__tests__/config.spec.js' {
  declare module.exports: $Exports<'d2/src/__tests__/config.spec'>;
}
declare module 'd2/src/__tests__/d2.spec.js' {
  declare module.exports: $Exports<'d2/src/__tests__/d2.spec'>;
}
declare module 'd2/src/__tests__/uid.spec.js' {
  declare module.exports: $Exports<'d2/src/__tests__/uid.spec'>;
}
declare module 'd2/src/analytics/__tests__/Analytics.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/Analytics.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsAggregate.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsAggregate.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsBase.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsBase.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsEvents.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsEvents.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsRequest.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsRequest.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsRequestBase.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsRequestBase.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsResponse.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsResponse.spec'>;
}
declare module 'd2/src/analytics/__tests__/AnalyticsResponseHeader.spec.js' {
  declare module.exports: $Exports<'d2/src/analytics/__tests__/AnalyticsResponseHeader.spec'>;
}
declare module 'd2/src/analytics/Analytics.js' {
  declare module.exports: $Exports<'d2/src/analytics/Analytics'>;
}
declare module 'd2/src/analytics/AnalyticsAggregate.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsAggregate'>;
}
declare module 'd2/src/analytics/AnalyticsBase.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsBase'>;
}
declare module 'd2/src/analytics/AnalyticsEvents.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsEvents'>;
}
declare module 'd2/src/analytics/AnalyticsRequest.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsRequest'>;
}
declare module 'd2/src/analytics/AnalyticsRequestBase.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsRequestBase'>;
}
declare module 'd2/src/analytics/AnalyticsRequestDimensionsMixin.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsRequestDimensionsMixin'>;
}
declare module 'd2/src/analytics/AnalyticsRequestFiltersMixin.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsRequestFiltersMixin'>;
}
declare module 'd2/src/analytics/AnalyticsRequestPropertiesMixin.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsRequestPropertiesMixin'>;
}
declare module 'd2/src/analytics/AnalyticsResponse.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsResponse'>;
}
declare module 'd2/src/analytics/AnalyticsResponseHeader.js' {
  declare module.exports: $Exports<'d2/src/analytics/AnalyticsResponseHeader'>;
}
declare module 'd2/src/api/__mocks__/Api.js' {
  declare module.exports: $Exports<'d2/src/api/__mocks__/Api'>;
}
declare module 'd2/src/api/__tests__/Api.spec.js' {
  declare module.exports: $Exports<'d2/src/api/__tests__/Api.spec'>;
}
declare module 'd2/src/api/Api.js' {
  declare module.exports: $Exports<'d2/src/api/Api'>;
}
declare module 'd2/src/config.js' {
  declare module.exports: $Exports<'d2/src/config'>;
}
declare module 'd2/src/current-user/__tests__/CurrentUser.spec.js' {
  declare module.exports: $Exports<'d2/src/current-user/__tests__/CurrentUser.spec'>;
}
declare module 'd2/src/current-user/__tests__/UserAuthorities.spec.js' {
  declare module.exports: $Exports<'d2/src/current-user/__tests__/UserAuthorities.spec'>;
}
declare module 'd2/src/current-user/__tests__/UserSettings.spec.js' {
  declare module.exports: $Exports<'d2/src/current-user/__tests__/UserSettings.spec'>;
}
declare module 'd2/src/current-user/CurrentUser.js' {
  declare module.exports: $Exports<'d2/src/current-user/CurrentUser'>;
}
declare module 'd2/src/current-user/UserAuthorities.js' {
  declare module.exports: $Exports<'d2/src/current-user/UserAuthorities'>;
}
declare module 'd2/src/current-user/UserSettings.js' {
  declare module.exports: $Exports<'d2/src/current-user/UserSettings'>;
}
declare module 'd2/src/d2.js' {
  declare module.exports: $Exports<'d2/src/d2'>;
}
declare module 'd2/src/datastore/__tests__/BaseStore.spec.js' {
  declare module.exports: $Exports<'d2/src/datastore/__tests__/BaseStore.spec'>;
}
declare module 'd2/src/datastore/__tests__/BaseStoreNamespace.spec.js' {
  declare module.exports: $Exports<'d2/src/datastore/__tests__/BaseStoreNamespace.spec'>;
}
declare module 'd2/src/datastore/__tests__/DataStore.spec.js' {
  declare module.exports: $Exports<'d2/src/datastore/__tests__/DataStore.spec'>;
}
declare module 'd2/src/datastore/__tests__/DatastoreNamespace.spec.js' {
  declare module.exports: $Exports<'d2/src/datastore/__tests__/DatastoreNamespace.spec'>;
}
declare module 'd2/src/datastore/__tests__/UserDataStore.spec.js' {
  declare module.exports: $Exports<'d2/src/datastore/__tests__/UserDataStore.spec'>;
}
declare module 'd2/src/datastore/__tests__/UserDatastoreNamespace.spec.js' {
  declare module.exports: $Exports<'d2/src/datastore/__tests__/UserDatastoreNamespace.spec'>;
}
declare module 'd2/src/datastore/BaseStore.js' {
  declare module.exports: $Exports<'d2/src/datastore/BaseStore'>;
}
declare module 'd2/src/datastore/BaseStoreNamespace.js' {
  declare module.exports: $Exports<'d2/src/datastore/BaseStoreNamespace'>;
}
declare module 'd2/src/datastore/DataStore.js' {
  declare module.exports: $Exports<'d2/src/datastore/DataStore'>;
}
declare module 'd2/src/datastore/DataStoreNamespace.js' {
  declare module.exports: $Exports<'d2/src/datastore/DataStoreNamespace'>;
}
declare module 'd2/src/datastore/UserDataStore.js' {
  declare module.exports: $Exports<'d2/src/datastore/UserDataStore'>;
}
declare module 'd2/src/datastore/UserDataStoreNamespace.js' {
  declare module.exports: $Exports<'d2/src/datastore/UserDataStoreNamespace'>;
}
declare module 'd2/src/defaultConfig.js' {
  declare module.exports: $Exports<'d2/src/defaultConfig'>;
}
declare module 'd2/src/geofeatures/__tests__/GeoFeatures.spec.js' {
  declare module.exports: $Exports<'d2/src/geofeatures/__tests__/GeoFeatures.spec'>;
}
declare module 'd2/src/geofeatures/GeoFeatures.js' {
  declare module.exports: $Exports<'d2/src/geofeatures/GeoFeatures'>;
}
declare module 'd2/src/i18n/__tests__/I18n.spec.js' {
  declare module.exports: $Exports<'d2/src/i18n/__tests__/I18n.spec'>;
}
declare module 'd2/src/i18n/I18n.js' {
  declare module.exports: $Exports<'d2/src/i18n/I18n'>;
}
declare module 'd2/src/lib/__tests__/check.spec.js' {
  declare module.exports: $Exports<'d2/src/lib/__tests__/check.spec'>;
}
declare module 'd2/src/lib/__tests__/utils.spec.js' {
  declare module.exports: $Exports<'d2/src/lib/__tests__/utils.spec'>;
}
declare module 'd2/src/lib/check.js' {
  declare module.exports: $Exports<'d2/src/lib/check'>;
}
declare module 'd2/src/lib/SchemaTypes.js' {
  declare module.exports: $Exports<'d2/src/lib/SchemaTypes'>;
}
declare module 'd2/src/lib/utils.js' {
  declare module.exports: $Exports<'d2/src/lib/utils'>;
}
declare module 'd2/src/logger/__tests__/Logger.spec.js' {
  declare module.exports: $Exports<'d2/src/logger/__tests__/Logger.spec'>;
}
declare module 'd2/src/logger/Logger.js' {
  declare module.exports: $Exports<'d2/src/logger/Logger'>;
}
declare module 'd2/src/model/__mocks__/Model.js' {
  declare module.exports: $Exports<'d2/src/model/__mocks__/Model'>;
}
declare module 'd2/src/model/__mocks__/ModelCollection.js' {
  declare module.exports: $Exports<'d2/src/model/__mocks__/ModelCollection'>;
}
declare module 'd2/src/model/__mocks__/ModelCollectionProperty.js' {
  declare module.exports: $Exports<'d2/src/model/__mocks__/ModelCollectionProperty'>;
}
declare module 'd2/src/model/__mocks__/ModelValidation.js' {
  declare module.exports: $Exports<'d2/src/model/__mocks__/ModelValidation'>;
}
declare module 'd2/src/model/__tests__/Filter.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/Filter.spec'>;
}
declare module 'd2/src/model/__tests__/Filters.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/Filters.spec'>;
}
declare module 'd2/src/model/__tests__/Model.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/Model.spec'>;
}
declare module 'd2/src/model/__tests__/ModelBase.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/ModelBase.spec'>;
}
declare module 'd2/src/model/__tests__/ModelCollection.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/ModelCollection.spec'>;
}
declare module 'd2/src/model/__tests__/ModelCollectionProperty.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/ModelCollectionProperty.spec'>;
}
declare module 'd2/src/model/__tests__/ModelDefinition.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/ModelDefinition.spec'>;
}
declare module 'd2/src/model/__tests__/ModelDefinitions.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/ModelDefinitions.spec'>;
}
declare module 'd2/src/model/__tests__/ModelValidation.spec.js' {
  declare module.exports: $Exports<'d2/src/model/__tests__/ModelValidation.spec'>;
}
declare module 'd2/src/model/config/index' {
  declare module.exports: $Exports<'d2/src/model/config'>;
}
declare module 'd2/src/model/config/index.js' {
  declare module.exports: $Exports<'d2/src/model/config'>;
}
declare module 'd2/src/model/config/model-defaults/__tests__/program.spec.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/__tests__/program.spec'>;
}
declare module 'd2/src/model/config/model-defaults/__tests__/programNotificationTemplate.spec.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/__tests__/programNotificationTemplate.spec'>;
}
declare module 'd2/src/model/config/model-defaults/__tests__/validationRule.spec.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/__tests__/validationRule.spec'>;
}
declare module 'd2/src/model/config/model-defaults/category.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/category'>;
}
declare module 'd2/src/model/config/model-defaults/categoryOptionGroupSet.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/categoryOptionGroupSet'>;
}
declare module 'd2/src/model/config/model-defaults/dataElement.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/dataElement'>;
}
declare module 'd2/src/model/config/model-defaults/dataElementGroupSet.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/dataElementGroupSet'>;
}
declare module 'd2/src/model/config/model-defaults/dataSet.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/dataSet'>;
}
declare module 'd2/src/model/config/model-defaults/externalMapLayer.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/externalMapLayer'>;
}
declare module 'd2/src/model/config/model-defaults/organisationUnitGroupSet.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/organisationUnitGroupSet'>;
}
declare module 'd2/src/model/config/model-defaults/program.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/program'>;
}
declare module 'd2/src/model/config/model-defaults/programNotificationTemplate.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/programNotificationTemplate'>;
}
declare module 'd2/src/model/config/model-defaults/validationNotificationTemplate.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/validationNotificationTemplate'>;
}
declare module 'd2/src/model/config/model-defaults/validationRule.js' {
  declare module.exports: $Exports<'d2/src/model/config/model-defaults/validationRule'>;
}
declare module 'd2/src/model/Filter.js' {
  declare module.exports: $Exports<'d2/src/model/Filter'>;
}
declare module 'd2/src/model/Filters.js' {
  declare module.exports: $Exports<'d2/src/model/Filters'>;
}
declare module 'd2/src/model/helpers/__tests__/json.spec.js' {
  declare module.exports: $Exports<'d2/src/model/helpers/__tests__/json.spec'>;
}
declare module 'd2/src/model/helpers/attibutes.js' {
  declare module.exports: $Exports<'d2/src/model/helpers/attibutes'>;
}
declare module 'd2/src/model/helpers/json.js' {
  declare module.exports: $Exports<'d2/src/model/helpers/json'>;
}
declare module 'd2/src/model/helpers/models.js' {
  declare module.exports: $Exports<'d2/src/model/helpers/models'>;
}
declare module 'd2/src/model/index' {
  declare module.exports: $Exports<'d2/src/model'>;
}
declare module 'd2/src/model/index.js' {
  declare module.exports: $Exports<'d2/src/model'>;
}
declare module 'd2/src/model/Model.js' {
  declare module.exports: $Exports<'d2/src/model/Model'>;
}
declare module 'd2/src/model/ModelBase.js' {
  declare module.exports: $Exports<'d2/src/model/ModelBase'>;
}
declare module 'd2/src/model/ModelCollection.js' {
  declare module.exports: $Exports<'d2/src/model/ModelCollection'>;
}
declare module 'd2/src/model/ModelCollectionProperty.js' {
  declare module.exports: $Exports<'d2/src/model/ModelCollectionProperty'>;
}
declare module 'd2/src/model/ModelDefinition.js' {
  declare module.exports: $Exports<'d2/src/model/ModelDefinition'>;
}
declare module 'd2/src/model/ModelDefinitions.js' {
  declare module.exports: $Exports<'d2/src/model/ModelDefinitions'>;
}
declare module 'd2/src/model/ModelValidation.js' {
  declare module.exports: $Exports<'d2/src/model/ModelValidation'>;
}
declare module 'd2/src/pager/__tests__/Pager.spec.js' {
  declare module.exports: $Exports<'d2/src/pager/__tests__/Pager.spec'>;
}
declare module 'd2/src/pager/Pager.js' {
  declare module.exports: $Exports<'d2/src/pager/Pager'>;
}
declare module 'd2/src/period/__tests__/helpers.spec.js' {
  declare module.exports: $Exports<'d2/src/period/__tests__/helpers.spec'>;
}
declare module 'd2/src/period/__tests__/parser.spec.js' {
  declare module.exports: $Exports<'d2/src/period/__tests__/parser.spec'>;
}
declare module 'd2/src/period/formatters.js' {
  declare module.exports: $Exports<'d2/src/period/formatters'>;
}
declare module 'd2/src/period/generators/__tests__/bi-monthly.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/bi-monthly.spec'>;
}
declare module 'd2/src/period/generators/__tests__/daily.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/daily.spec'>;
}
declare module 'd2/src/period/generators/__tests__/financial-april.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/financial-april.spec'>;
}
declare module 'd2/src/period/generators/__tests__/financial-july.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/financial-july.spec'>;
}
declare module 'd2/src/period/generators/__tests__/financial-october.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/financial-october.spec'>;
}
declare module 'd2/src/period/generators/__tests__/index.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/index.spec'>;
}
declare module 'd2/src/period/generators/__tests__/monthly.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/monthly.spec'>;
}
declare module 'd2/src/period/generators/__tests__/quarterly.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/quarterly.spec'>;
}
declare module 'd2/src/period/generators/__tests__/six-monthly-april.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/six-monthly-april.spec'>;
}
declare module 'd2/src/period/generators/__tests__/six-monthly.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/six-monthly.spec'>;
}
declare module 'd2/src/period/generators/__tests__/weekly.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/weekly.spec'>;
}
declare module 'd2/src/period/generators/__tests__/yearly.spec.js' {
  declare module.exports: $Exports<'d2/src/period/generators/__tests__/yearly.spec'>;
}
declare module 'd2/src/period/generators/bi-monthly.js' {
  declare module.exports: $Exports<'d2/src/period/generators/bi-monthly'>;
}
declare module 'd2/src/period/generators/daily.js' {
  declare module.exports: $Exports<'d2/src/period/generators/daily'>;
}
declare module 'd2/src/period/generators/financial-april.js' {
  declare module.exports: $Exports<'d2/src/period/generators/financial-april'>;
}
declare module 'd2/src/period/generators/financial-july.js' {
  declare module.exports: $Exports<'d2/src/period/generators/financial-july'>;
}
declare module 'd2/src/period/generators/financial-october.js' {
  declare module.exports: $Exports<'d2/src/period/generators/financial-october'>;
}
declare module 'd2/src/period/generators/index' {
  declare module.exports: $Exports<'d2/src/period/generators'>;
}
declare module 'd2/src/period/generators/index.js' {
  declare module.exports: $Exports<'d2/src/period/generators'>;
}
declare module 'd2/src/period/generators/monthly.js' {
  declare module.exports: $Exports<'d2/src/period/generators/monthly'>;
}
declare module 'd2/src/period/generators/quarterly.js' {
  declare module.exports: $Exports<'d2/src/period/generators/quarterly'>;
}
declare module 'd2/src/period/generators/six-monthly-april.js' {
  declare module.exports: $Exports<'d2/src/period/generators/six-monthly-april'>;
}
declare module 'd2/src/period/generators/six-monthly.js' {
  declare module.exports: $Exports<'d2/src/period/generators/six-monthly'>;
}
declare module 'd2/src/period/generators/weekly.js' {
  declare module.exports: $Exports<'d2/src/period/generators/weekly'>;
}
declare module 'd2/src/period/generators/yearly.js' {
  declare module.exports: $Exports<'d2/src/period/generators/yearly'>;
}
declare module 'd2/src/period/helpers.js' {
  declare module.exports: $Exports<'d2/src/period/helpers'>;
}
declare module 'd2/src/period/parser.js' {
  declare module.exports: $Exports<'d2/src/period/parser'>;
}
declare module 'd2/src/system/__tests__/System.spec.js' {
  declare module.exports: $Exports<'d2/src/system/__tests__/System.spec'>;
}
declare module 'd2/src/system/__tests__/SystemConfiguration.spec.js' {
  declare module.exports: $Exports<'d2/src/system/__tests__/SystemConfiguration.spec'>;
}
declare module 'd2/src/system/__tests__/SystemSettings.spec.js' {
  declare module.exports: $Exports<'d2/src/system/__tests__/SystemSettings.spec'>;
}
declare module 'd2/src/system/System.js' {
  declare module.exports: $Exports<'d2/src/system/System'>;
}
declare module 'd2/src/system/SystemConfiguration.js' {
  declare module.exports: $Exports<'d2/src/system/SystemConfiguration'>;
}
declare module 'd2/src/system/SystemSettings.js' {
  declare module.exports: $Exports<'d2/src/system/SystemSettings'>;
}
declare module 'd2/src/uid.js' {
  declare module.exports: $Exports<'d2/src/uid'>;
}
declare module 'd2/system/System.js' {
  declare module.exports: $Exports<'d2/system/System'>;
}
declare module 'd2/system/SystemConfiguration.js' {
  declare module.exports: $Exports<'d2/system/SystemConfiguration'>;
}
declare module 'd2/system/SystemSettings.js' {
  declare module.exports: $Exports<'d2/system/SystemSettings'>;
}
declare module 'd2/uid.js' {
  declare module.exports: $Exports<'d2/uid'>;
}
declare module 'd2/webpack.config.dev.js' {
  declare module.exports: $Exports<'d2/webpack.config.dev'>;
}
declare module 'd2/webpack.config.prod.js' {
  declare module.exports: $Exports<'d2/webpack.config.prod'>;
}
