// flow-typed signature: c3c851442f1d82044dca830a910432c5
// flow-typed version: <<STUB>>/docdash_v^1.2.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docdash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docdash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docdash/publish' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/collapse' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/nav' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/polyfill' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'docdash/static/scripts/search' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docdash/publish.js' {
  declare module.exports: $Exports<'docdash/publish'>;
}
declare module 'docdash/static/scripts/collapse.js' {
  declare module.exports: $Exports<'docdash/static/scripts/collapse'>;
}
declare module 'docdash/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'docdash/static/scripts/linenumber'>;
}
declare module 'docdash/static/scripts/nav.js' {
  declare module.exports: $Exports<'docdash/static/scripts/nav'>;
}
declare module 'docdash/static/scripts/polyfill.js' {
  declare module.exports: $Exports<'docdash/static/scripts/polyfill'>;
}
declare module 'docdash/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'docdash/static/scripts/prettify/lang-css'>;
}
declare module 'docdash/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'docdash/static/scripts/prettify/prettify'>;
}
declare module 'docdash/static/scripts/search.js' {
  declare module.exports: $Exports<'docdash/static/scripts/search'>;
}
