// flow-typed signature: 21d519d20b7336f6f92023b8c2ef6fcd
// flow-typed version: <<STUB>>/eslint-config-dhis2_v^3.0.7/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-dhis2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-dhis2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-dhis2/bin/lintchangedfiles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-dhis2/bin/lintchangedfiles.js' {
  declare module.exports: $Exports<'eslint-config-dhis2/bin/lintchangedfiles'>;
}
declare module 'eslint-config-dhis2/index' {
  declare module.exports: $Exports<'eslint-config-dhis2'>;
}
declare module 'eslint-config-dhis2/index.js' {
  declare module.exports: $Exports<'eslint-config-dhis2'>;
}
