// flow-typed signature: 670721547672cc4e52253972bc3cc05a
// flow-typed version: <<STUB>>/jest-localstorage-mock_v^2.4.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-localstorage-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-localstorage-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-localstorage-mock/__setups__/localstorage' {
  declare module.exports: any;
}

declare module 'jest-localstorage-mock/dist/setup' {
  declare module.exports: any;
}

declare module 'jest-localstorage-mock/src/localstorage' {
  declare module.exports: any;
}

declare module 'jest-localstorage-mock/src/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-localstorage-mock/__setups__/localstorage.js' {
  declare module.exports: $Exports<'jest-localstorage-mock/__setups__/localstorage'>;
}
declare module 'jest-localstorage-mock/dist/setup.js' {
  declare module.exports: $Exports<'jest-localstorage-mock/dist/setup'>;
}
declare module 'jest-localstorage-mock/src/localstorage.js' {
  declare module.exports: $Exports<'jest-localstorage-mock/src/localstorage'>;
}
declare module 'jest-localstorage-mock/src/setup.js' {
  declare module.exports: $Exports<'jest-localstorage-mock/src/setup'>;
}
