// flow-typed signature: afd9f1b3f2168e740c84640947afb71a
// flow-typed version: <<STUB>>/jsdoc-babel_v^0.5.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-babel/lib/countCharInRange' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/lib' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/lib/preserveLineNumbers' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/lib/shouldProcessFile' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/lib/stripWhitespace' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/lib/transformFile' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src/countCharInRange' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src/preserveLineNumbers' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src/shouldProcessFile' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src/stripWhitespace' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src/transformFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-babel/lib/countCharInRange.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib/countCharInRange'>;
}
declare module 'jsdoc-babel/lib/index' {
  declare module.exports: $Exports<'jsdoc-babel/lib'>;
}
declare module 'jsdoc-babel/lib/index.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib'>;
}
declare module 'jsdoc-babel/lib/preserveLineNumbers.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib/preserveLineNumbers'>;
}
declare module 'jsdoc-babel/lib/shouldProcessFile.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib/shouldProcessFile'>;
}
declare module 'jsdoc-babel/lib/stripWhitespace.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib/stripWhitespace'>;
}
declare module 'jsdoc-babel/lib/transformFile.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib/transformFile'>;
}
declare module 'jsdoc-babel/src/countCharInRange.js' {
  declare module.exports: $Exports<'jsdoc-babel/src/countCharInRange'>;
}
declare module 'jsdoc-babel/src/index' {
  declare module.exports: $Exports<'jsdoc-babel/src'>;
}
declare module 'jsdoc-babel/src/index.js' {
  declare module.exports: $Exports<'jsdoc-babel/src'>;
}
declare module 'jsdoc-babel/src/preserveLineNumbers.js' {
  declare module.exports: $Exports<'jsdoc-babel/src/preserveLineNumbers'>;
}
declare module 'jsdoc-babel/src/shouldProcessFile.js' {
  declare module.exports: $Exports<'jsdoc-babel/src/shouldProcessFile'>;
}
declare module 'jsdoc-babel/src/stripWhitespace.js' {
  declare module.exports: $Exports<'jsdoc-babel/src/stripWhitespace'>;
}
declare module 'jsdoc-babel/src/transformFile.js' {
  declare module.exports: $Exports<'jsdoc-babel/src/transformFile'>;
}
