// flow-typed signature: 77b43d67a68e19058aa1f793b23643a5
// flow-typed version: <<STUB>>/jsdoc-export-default-interop_v^0.3.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-export-default-interop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-export-default-interop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-export-default-interop/babel.config' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/dist' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/lib' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/out/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/out/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/out/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/test/code/exports' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/test/code/source-default' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/test/code/source-mixed' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/test/code/source-named' {
  declare module.exports: any;
}

declare module 'jsdoc-export-default-interop/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-export-default-interop/babel.config.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/babel.config'>;
}
declare module 'jsdoc-export-default-interop/dist/index' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/dist'>;
}
declare module 'jsdoc-export-default-interop/dist/index.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/dist'>;
}
declare module 'jsdoc-export-default-interop/lib/index' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/lib'>;
}
declare module 'jsdoc-export-default-interop/lib/index.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/lib'>;
}
declare module 'jsdoc-export-default-interop/out/scripts/linenumber.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/out/scripts/linenumber'>;
}
declare module 'jsdoc-export-default-interop/out/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/out/scripts/prettify/lang-css'>;
}
declare module 'jsdoc-export-default-interop/out/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/out/scripts/prettify/prettify'>;
}
declare module 'jsdoc-export-default-interop/test/code/exports.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/test/code/exports'>;
}
declare module 'jsdoc-export-default-interop/test/code/source-default.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/test/code/source-default'>;
}
declare module 'jsdoc-export-default-interop/test/code/source-mixed.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/test/code/source-mixed'>;
}
declare module 'jsdoc-export-default-interop/test/code/source-named.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/test/code/source-named'>;
}
declare module 'jsdoc-export-default-interop/test/index' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/test'>;
}
declare module 'jsdoc-export-default-interop/test/index.js' {
  declare module.exports: $Exports<'jsdoc-export-default-interop/test'>;
}
