// flow-typed signature: 558634a73b095151607384e5b335c3fc
// flow-typed version: <<STUB>>/leaflet-draw_v^1.0.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-draw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-draw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-draw/dist/leaflet.draw-src' {
  declare module.exports: any;
}

declare module 'leaflet-draw/dist/leaflet.draw' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples-0.7.x/libs/leaflet-src' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples-0.7.x/libs/Leaflet.draw.drag-src' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples-0.7.x/libs/leaflet.geometryutil' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples-0.7.x/libs/leaflet.snap' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples-0.7.x/libs/spectrum' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples/libs/leaflet-src' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples/libs/Leaflet.draw.drag-src' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples/libs/leaflet.geometryutil' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples/libs/leaflet.snap' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/examples/libs/spectrum' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/highlight/highlight.pack' {
  declare module.exports: any;
}

declare module 'leaflet-draw/docs/js/docs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-draw/dist/leaflet.draw-src.js' {
  declare module.exports: $Exports<'leaflet-draw/dist/leaflet.draw-src'>;
}
declare module 'leaflet-draw/dist/leaflet.draw.js' {
  declare module.exports: $Exports<'leaflet-draw/dist/leaflet.draw'>;
}
declare module 'leaflet-draw/docs/examples-0.7.x/libs/leaflet-src.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples-0.7.x/libs/leaflet-src'>;
}
declare module 'leaflet-draw/docs/examples-0.7.x/libs/Leaflet.draw.drag-src.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples-0.7.x/libs/Leaflet.draw.drag-src'>;
}
declare module 'leaflet-draw/docs/examples-0.7.x/libs/leaflet.geometryutil.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples-0.7.x/libs/leaflet.geometryutil'>;
}
declare module 'leaflet-draw/docs/examples-0.7.x/libs/leaflet.snap.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples-0.7.x/libs/leaflet.snap'>;
}
declare module 'leaflet-draw/docs/examples-0.7.x/libs/spectrum.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples-0.7.x/libs/spectrum'>;
}
declare module 'leaflet-draw/docs/examples/libs/leaflet-src.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples/libs/leaflet-src'>;
}
declare module 'leaflet-draw/docs/examples/libs/Leaflet.draw.drag-src.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples/libs/Leaflet.draw.drag-src'>;
}
declare module 'leaflet-draw/docs/examples/libs/leaflet.geometryutil.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples/libs/leaflet.geometryutil'>;
}
declare module 'leaflet-draw/docs/examples/libs/leaflet.snap.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples/libs/leaflet.snap'>;
}
declare module 'leaflet-draw/docs/examples/libs/spectrum.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/examples/libs/spectrum'>;
}
declare module 'leaflet-draw/docs/highlight/highlight.pack.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/highlight/highlight.pack'>;
}
declare module 'leaflet-draw/docs/js/docs.js' {
  declare module.exports: $Exports<'leaflet-draw/docs/js/docs'>;
}
