// flow-typed signature: 1bb1c5cd33740e00acb02886cb5613c2
// flow-typed version: <<STUB>>/react-infinite-calendar_v^2.3.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-infinite-calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-infinite-calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-infinite-calendar/es/Calendar' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Calendar/withDateSelection' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Calendar/withKeyboardSupport' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Calendar/withMultipleDates' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Calendar/withRange' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Day' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Header/defaultSelectionRenderer' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Header' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Header/Slider' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Header/withMultipleDates' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Header/withRange' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Month' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/MonthList' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Today' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/utils/animate' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/utils/defaultDisplayOptions' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/utils/defaultLocale' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/utils/defaultTheme' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/utils' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Weekdays' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/es/Years' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Calendar' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Calendar/withDateSelection' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Calendar/withKeyboardSupport' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Calendar/withMultipleDates' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Calendar/withRange' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Day' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Header/defaultSelectionRenderer' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Header' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Header/Slider' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Header/withMultipleDates' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Header/withRange' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Month' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/MonthList' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Today' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/utils/animate' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/utils/defaultDisplayOptions' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/utils/defaultLocale' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/utils/defaultTheme' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/utils' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Weekdays' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/lib/Years' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/umd/react-infinite-calendar' {
  declare module.exports: any;
}

declare module 'react-infinite-calendar/umd/react-infinite-calendar.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-infinite-calendar/es/Calendar/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Calendar'>;
}
declare module 'react-infinite-calendar/es/Calendar/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Calendar'>;
}
declare module 'react-infinite-calendar/es/Calendar/withDateSelection.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Calendar/withDateSelection'>;
}
declare module 'react-infinite-calendar/es/Calendar/withKeyboardSupport.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Calendar/withKeyboardSupport'>;
}
declare module 'react-infinite-calendar/es/Calendar/withMultipleDates.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Calendar/withMultipleDates'>;
}
declare module 'react-infinite-calendar/es/Calendar/withRange.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Calendar/withRange'>;
}
declare module 'react-infinite-calendar/es/Day/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Day'>;
}
declare module 'react-infinite-calendar/es/Day/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Day'>;
}
declare module 'react-infinite-calendar/es/Header/defaultSelectionRenderer.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header/defaultSelectionRenderer'>;
}
declare module 'react-infinite-calendar/es/Header/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header'>;
}
declare module 'react-infinite-calendar/es/Header/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header'>;
}
declare module 'react-infinite-calendar/es/Header/Slider/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header/Slider'>;
}
declare module 'react-infinite-calendar/es/Header/Slider/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header/Slider'>;
}
declare module 'react-infinite-calendar/es/Header/withMultipleDates.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header/withMultipleDates'>;
}
declare module 'react-infinite-calendar/es/Header/withRange.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Header/withRange'>;
}
declare module 'react-infinite-calendar/es/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es'>;
}
declare module 'react-infinite-calendar/es/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es'>;
}
declare module 'react-infinite-calendar/es/Month/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Month'>;
}
declare module 'react-infinite-calendar/es/Month/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Month'>;
}
declare module 'react-infinite-calendar/es/MonthList/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/MonthList'>;
}
declare module 'react-infinite-calendar/es/MonthList/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/MonthList'>;
}
declare module 'react-infinite-calendar/es/Today/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Today'>;
}
declare module 'react-infinite-calendar/es/Today/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Today'>;
}
declare module 'react-infinite-calendar/es/utils/animate.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/utils/animate'>;
}
declare module 'react-infinite-calendar/es/utils/defaultDisplayOptions.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/utils/defaultDisplayOptions'>;
}
declare module 'react-infinite-calendar/es/utils/defaultLocale.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/utils/defaultLocale'>;
}
declare module 'react-infinite-calendar/es/utils/defaultTheme.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/utils/defaultTheme'>;
}
declare module 'react-infinite-calendar/es/utils/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/utils'>;
}
declare module 'react-infinite-calendar/es/utils/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/utils'>;
}
declare module 'react-infinite-calendar/es/Weekdays/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Weekdays'>;
}
declare module 'react-infinite-calendar/es/Weekdays/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Weekdays'>;
}
declare module 'react-infinite-calendar/es/Years/index' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Years'>;
}
declare module 'react-infinite-calendar/es/Years/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/es/Years'>;
}
declare module 'react-infinite-calendar/lib/Calendar/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Calendar'>;
}
declare module 'react-infinite-calendar/lib/Calendar/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Calendar'>;
}
declare module 'react-infinite-calendar/lib/Calendar/withDateSelection.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Calendar/withDateSelection'>;
}
declare module 'react-infinite-calendar/lib/Calendar/withKeyboardSupport.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Calendar/withKeyboardSupport'>;
}
declare module 'react-infinite-calendar/lib/Calendar/withMultipleDates.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Calendar/withMultipleDates'>;
}
declare module 'react-infinite-calendar/lib/Calendar/withRange.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Calendar/withRange'>;
}
declare module 'react-infinite-calendar/lib/Day/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Day'>;
}
declare module 'react-infinite-calendar/lib/Day/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Day'>;
}
declare module 'react-infinite-calendar/lib/Header/defaultSelectionRenderer.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header/defaultSelectionRenderer'>;
}
declare module 'react-infinite-calendar/lib/Header/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header'>;
}
declare module 'react-infinite-calendar/lib/Header/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header'>;
}
declare module 'react-infinite-calendar/lib/Header/Slider/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header/Slider'>;
}
declare module 'react-infinite-calendar/lib/Header/Slider/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header/Slider'>;
}
declare module 'react-infinite-calendar/lib/Header/withMultipleDates.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header/withMultipleDates'>;
}
declare module 'react-infinite-calendar/lib/Header/withRange.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Header/withRange'>;
}
declare module 'react-infinite-calendar/lib/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib'>;
}
declare module 'react-infinite-calendar/lib/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib'>;
}
declare module 'react-infinite-calendar/lib/Month/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Month'>;
}
declare module 'react-infinite-calendar/lib/Month/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Month'>;
}
declare module 'react-infinite-calendar/lib/MonthList/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/MonthList'>;
}
declare module 'react-infinite-calendar/lib/MonthList/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/MonthList'>;
}
declare module 'react-infinite-calendar/lib/Today/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Today'>;
}
declare module 'react-infinite-calendar/lib/Today/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Today'>;
}
declare module 'react-infinite-calendar/lib/utils/animate.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/utils/animate'>;
}
declare module 'react-infinite-calendar/lib/utils/defaultDisplayOptions.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/utils/defaultDisplayOptions'>;
}
declare module 'react-infinite-calendar/lib/utils/defaultLocale.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/utils/defaultLocale'>;
}
declare module 'react-infinite-calendar/lib/utils/defaultTheme.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/utils/defaultTheme'>;
}
declare module 'react-infinite-calendar/lib/utils/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/utils'>;
}
declare module 'react-infinite-calendar/lib/utils/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/utils'>;
}
declare module 'react-infinite-calendar/lib/Weekdays/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Weekdays'>;
}
declare module 'react-infinite-calendar/lib/Weekdays/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Weekdays'>;
}
declare module 'react-infinite-calendar/lib/Years/index' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Years'>;
}
declare module 'react-infinite-calendar/lib/Years/index.js' {
  declare module.exports: $Exports<'react-infinite-calendar/lib/Years'>;
}
declare module 'react-infinite-calendar/umd/react-infinite-calendar.js' {
  declare module.exports: $Exports<'react-infinite-calendar/umd/react-infinite-calendar'>;
}
declare module 'react-infinite-calendar/umd/react-infinite-calendar.min.js' {
  declare module.exports: $Exports<'react-infinite-calendar/umd/react-infinite-calendar.min'>;
}
