// flow-typed signature: e2df9125ff42f48bce85d967637adfcd
// flow-typed version: <<STUB>>/react-autosuggest_v^10.0.2/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-autosuggest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-autosuggest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-autosuggest/dist/Autosuggest' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/Autowhatever' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/compareObjects' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/demo/standalone/compiled.app' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/dist/standalone/autosuggest' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/dist/standalone/autosuggest.min' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/Item' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/ItemList' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/SectionTitle' {
  declare module.exports: any;
}

declare module 'react-autosuggest/dist/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-autosuggest/dist/Autosuggest.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/Autosuggest'>;
}
declare module 'react-autosuggest/dist/Autowhatever.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/Autowhatever'>;
}
declare module 'react-autosuggest/dist/compareObjects.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/compareObjects'>;
}
declare module 'react-autosuggest/dist/demo/standalone/compiled.app.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/demo/standalone/compiled.app'>;
}
declare module 'react-autosuggest/dist/dist/standalone/autosuggest.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/dist/standalone/autosuggest'>;
}
declare module 'react-autosuggest/dist/dist/standalone/autosuggest.min.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/dist/standalone/autosuggest.min'>;
}
declare module 'react-autosuggest/dist/index' {
  declare module.exports: $Exports<'react-autosuggest/dist'>;
}
declare module 'react-autosuggest/dist/index.js' {
  declare module.exports: $Exports<'react-autosuggest/dist'>;
}
declare module 'react-autosuggest/dist/Item.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/Item'>;
}
declare module 'react-autosuggest/dist/ItemList.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/ItemList'>;
}
declare module 'react-autosuggest/dist/SectionTitle.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/SectionTitle'>;
}
declare module 'react-autosuggest/dist/theme.js' {
  declare module.exports: $Exports<'react-autosuggest/dist/theme'>;
}
