// flow-typed signature: 6da3b1f80a79c4b1aa0dc56309ffe600
// flow-typed version: <<STUB>>/react-leaflet-draw_v^0.19.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-draw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-draw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-draw/dist/esm/EditControl' {
  declare module.exports: any;
}

declare module 'react-leaflet-draw/dist/esm' {
  declare module.exports: any;
}

declare module 'react-leaflet-draw/dist/react-leaflet-draw' {
  declare module.exports: any;
}

declare module 'react-leaflet-draw/dist/react-leaflet-draw.min' {
  declare module.exports: any;
}

declare module 'react-leaflet-draw/src/EditControl' {
  declare module.exports: any;
}

declare module 'react-leaflet-draw/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-draw/dist/esm/EditControl.js' {
  declare module.exports: $Exports<'react-leaflet-draw/dist/esm/EditControl'>;
}
declare module 'react-leaflet-draw/dist/esm/index' {
  declare module.exports: $Exports<'react-leaflet-draw/dist/esm'>;
}
declare module 'react-leaflet-draw/dist/esm/index.js' {
  declare module.exports: $Exports<'react-leaflet-draw/dist/esm'>;
}
declare module 'react-leaflet-draw/dist/react-leaflet-draw.js' {
  declare module.exports: $Exports<'react-leaflet-draw/dist/react-leaflet-draw'>;
}
declare module 'react-leaflet-draw/dist/react-leaflet-draw.min.js' {
  declare module.exports: $Exports<'react-leaflet-draw/dist/react-leaflet-draw.min'>;
}
declare module 'react-leaflet-draw/src/EditControl.js' {
  declare module.exports: $Exports<'react-leaflet-draw/src/EditControl'>;
}
declare module 'react-leaflet-draw/src/index' {
  declare module.exports: $Exports<'react-leaflet-draw/src'>;
}
declare module 'react-leaflet-draw/src/index.js' {
  declare module.exports: $Exports<'react-leaflet-draw/src'>;
}
