// flow-typed signature: ce5de1caf0c604bd9a3fc2f88e9708bd
// flow-typed version: <<STUB>>/react-leaflet-search-unpolyfilled_v^0.1.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-search-unpolyfilled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-search-unpolyfilled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-search-unpolyfilled/lib/ExtendedMarker' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/lib' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/lib/InputBox' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/lib/Providers/BingMap' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/lib/Providers' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/lib/Providers/OpenStreetMap' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/lib/React-Leaflet-Search' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src/ExtendedMarker' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src/InputBox' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src/Providers/BingMap' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src/Providers' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src/Providers/OpenStreetMap' {
  declare module.exports: any;
}

declare module 'react-leaflet-search-unpolyfilled/src/React-Leaflet-Search' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-search-unpolyfilled/lib/ExtendedMarker.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/ExtendedMarker'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/index' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/index.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/InputBox.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/InputBox'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/Providers/BingMap.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/Providers/BingMap'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/Providers/index' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/Providers'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/Providers/index.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/Providers'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/Providers/OpenStreetMap.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/Providers/OpenStreetMap'>;
}
declare module 'react-leaflet-search-unpolyfilled/lib/React-Leaflet-Search.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/lib/React-Leaflet-Search'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/ExtendedMarker.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/ExtendedMarker'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/index' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/index.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/InputBox.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/InputBox'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/Providers/BingMap.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/Providers/BingMap'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/Providers/index' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/Providers'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/Providers/index.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/Providers'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/Providers/OpenStreetMap.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/Providers/OpenStreetMap'>;
}
declare module 'react-leaflet-search-unpolyfilled/src/React-Leaflet-Search.js' {
  declare module.exports: $Exports<'react-leaflet-search-unpolyfilled/src/React-Leaflet-Search'>;
}
