// flow-typed signature: a25c7e01c11a9046be3d52e5c113e8ae
// flow-typed version: <<STUB>>/react-dnd_v^8.0.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd/lib/common/DndContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DndProvider' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DragPreviewImage' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DragSourceMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/DropTargetMonitorImpl' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/registration' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/SourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/TargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/common/wrapConnectorHooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/disposables' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragDropContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorators/utils' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/drag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/drop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useCollector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useDragDropManager' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/internal/useMonitorOutput' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrag' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/hooks/useDrop' {
  declare module.exports: any;
}

declare module 'react-dnd/lib' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/connectors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/hooksApi' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/monitors' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces/options' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/isRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/js_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd/lib/common/DndContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DndContext'>;
}
declare module 'react-dnd/lib/common/DndProvider.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DndProvider'>;
}
declare module 'react-dnd/lib/common/DragPreviewImage.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DragPreviewImage'>;
}
declare module 'react-dnd/lib/common/DragSourceMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DragSourceMonitorImpl'>;
}
declare module 'react-dnd/lib/common/DropTargetMonitorImpl.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/DropTargetMonitorImpl'>;
}
declare module 'react-dnd/lib/common/index' {
  declare module.exports: $Exports<'react-dnd/lib/common'>;
}
declare module 'react-dnd/lib/common/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/common'>;
}
declare module 'react-dnd/lib/common/registration.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/registration'>;
}
declare module 'react-dnd/lib/common/SourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/SourceConnector'>;
}
declare module 'react-dnd/lib/common/TargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/TargetConnector'>;
}
declare module 'react-dnd/lib/common/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/lib/common/wrapConnectorHooks'>;
}
declare module 'react-dnd/lib/decorators/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/createSourceFactory'>;
}
declare module 'react-dnd/lib/decorators/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/createTargetFactory'>;
}
declare module 'react-dnd/lib/decorators/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/decorateHandler'>;
}
declare module 'react-dnd/lib/decorators/disposables.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/disposables'>;
}
declare module 'react-dnd/lib/decorators/DragDropContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragDropContext'>;
}
declare module 'react-dnd/lib/decorators/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragLayer'>;
}
declare module 'react-dnd/lib/decorators/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DragSource'>;
}
declare module 'react-dnd/lib/decorators/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/DropTarget'>;
}
declare module 'react-dnd/lib/decorators/index' {
  declare module.exports: $Exports<'react-dnd/lib/decorators'>;
}
declare module 'react-dnd/lib/decorators/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators'>;
}
declare module 'react-dnd/lib/decorators/interfaces.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/interfaces'>;
}
declare module 'react-dnd/lib/decorators/utils.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorators/utils'>;
}
declare module 'react-dnd/lib/hooks/index' {
  declare module.exports: $Exports<'react-dnd/lib/hooks'>;
}
declare module 'react-dnd/lib/hooks/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks'>;
}
declare module 'react-dnd/lib/hooks/internal/drag.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/drag'>;
}
declare module 'react-dnd/lib/hooks/internal/drop.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/drop'>;
}
declare module 'react-dnd/lib/hooks/internal/useCollector.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useCollector'>;
}
declare module 'react-dnd/lib/hooks/internal/useDragDropManager.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useDragDropManager'>;
}
declare module 'react-dnd/lib/hooks/internal/useMonitorOutput.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/internal/useMonitorOutput'>;
}
declare module 'react-dnd/lib/hooks/useDrag.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrag'>;
}
declare module 'react-dnd/lib/hooks/useDragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDragLayer'>;
}
declare module 'react-dnd/lib/hooks/useDrop.js' {
  declare module.exports: $Exports<'react-dnd/lib/hooks/useDrop'>;
}
declare module 'react-dnd/lib/index' {
  declare module.exports: $Exports<'react-dnd/lib'>;
}
declare module 'react-dnd/lib/index.js' {
  declare module.exports: $Exports<'react-dnd/lib'>;
}
declare module 'react-dnd/lib/interfaces/connectors.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/connectors'>;
}
declare module 'react-dnd/lib/interfaces/hooksApi.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/hooksApi'>;
}
declare module 'react-dnd/lib/interfaces/index' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces'>;
}
declare module 'react-dnd/lib/interfaces/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces'>;
}
declare module 'react-dnd/lib/interfaces/monitors.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/monitors'>;
}
declare module 'react-dnd/lib/interfaces/options.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces/options'>;
}
declare module 'react-dnd/lib/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/cloneWithRef'>;
}
declare module 'react-dnd/lib/utils/isRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/isRef'>;
}
declare module 'react-dnd/lib/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/isValidType'>;
}
declare module 'react-dnd/lib/utils/js_utils.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/js_utils'>;
}
