// flow-typed signature: 752914a2a7a65992ab2ab0a092129293
// flow-typed version: <<STUB>>/react-html-parser-ultimate_v^1.0.7/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html-parser-ultimate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html-parser-ultimate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html-parser-ultimate/lib/convertersForTypes' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/convertersForTypes/StyleElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/convertersForTypes/TagElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/convertersForTypes/TextElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/convertersForTypes/UnsupportedElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/convertNodeToElement' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/dom/attributes/BooleanAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/dom/attributes/ReactAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/dom/elements/VoidElements' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/parseHtml' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/processNodes' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/utils/generatePropsFromAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/utils/htmlAttributesToReact' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/utils/inlineStyleToObject' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/utils/isEmptyTextNode' {
  declare module.exports: any;
}

declare module 'react-html-parser-ultimate/lib/utils/isValidTagOrAttributeName' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html-parser-ultimate/lib/convertersForTypes/index' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertersForTypes'>;
}
declare module 'react-html-parser-ultimate/lib/convertersForTypes/index.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertersForTypes'>;
}
declare module 'react-html-parser-ultimate/lib/convertersForTypes/StyleElementType.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertersForTypes/StyleElementType'>;
}
declare module 'react-html-parser-ultimate/lib/convertersForTypes/TagElementType.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertersForTypes/TagElementType'>;
}
declare module 'react-html-parser-ultimate/lib/convertersForTypes/TextElementType.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertersForTypes/TextElementType'>;
}
declare module 'react-html-parser-ultimate/lib/convertersForTypes/UnsupportedElementType.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertersForTypes/UnsupportedElementType'>;
}
declare module 'react-html-parser-ultimate/lib/convertNodeToElement.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/convertNodeToElement'>;
}
declare module 'react-html-parser-ultimate/lib/dom/attributes/BooleanAttributes.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/dom/attributes/BooleanAttributes'>;
}
declare module 'react-html-parser-ultimate/lib/dom/attributes/ReactAttributes.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/dom/attributes/ReactAttributes'>;
}
declare module 'react-html-parser-ultimate/lib/dom/elements/VoidElements.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/dom/elements/VoidElements'>;
}
declare module 'react-html-parser-ultimate/lib/index' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib'>;
}
declare module 'react-html-parser-ultimate/lib/index.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib'>;
}
declare module 'react-html-parser-ultimate/lib/parseHtml.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/parseHtml'>;
}
declare module 'react-html-parser-ultimate/lib/processNodes.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/processNodes'>;
}
declare module 'react-html-parser-ultimate/lib/utils/generatePropsFromAttributes.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/utils/generatePropsFromAttributes'>;
}
declare module 'react-html-parser-ultimate/lib/utils/htmlAttributesToReact.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/utils/htmlAttributesToReact'>;
}
declare module 'react-html-parser-ultimate/lib/utils/inlineStyleToObject.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/utils/inlineStyleToObject'>;
}
declare module 'react-html-parser-ultimate/lib/utils/isEmptyTextNode.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/utils/isEmptyTextNode'>;
}
declare module 'react-html-parser-ultimate/lib/utils/isValidTagOrAttributeName.js' {
  declare module.exports: $Exports<'react-html-parser-ultimate/lib/utils/isValidTagOrAttributeName'>;
}
