// flow-typed signature: a4bfadf8b22f002a0c37f1bf8e63d729
// flow-typed version: <<STUB>>/rules-engine_v1.1.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rules-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rules-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rules-engine/build/cjs/commonUtils' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/commonUtils/normalizeRuleVariable' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/commonUtils/numberToString' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/commonUtils/trimQuotes' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants/effectActions.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants/environmentTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants/idNames.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants/targetDataTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants/typeKeys.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/constants/typeToInterfaceFnName.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/d2Functions/getD2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/d2Functions/getD2Functions.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/d2Functions/gs1DataMatrixFuntions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/d2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/d2Functions/zScoreFunctions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/errorCreator/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/helpers/OptionSetHelper' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/processors/rulesEffectsProcessor/rulesEffectsProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/processors/ValueProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/RulesEngine' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/rulesEngine.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/expressionService/common/getInjectionValue' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/expressionService/common' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/expressionService/executeExpression' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/expressionService/executeExpression.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/expressionService' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/expressionService/injectVariableValues' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/constants/eventStatuses' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/helpers' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/helpers/structureEvents' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/variablePrefixes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/build/cjs/services/VariableService/variableService.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/commonUtils' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/commonUtils/normalizeRuleVariable' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/commonUtils/numberToString' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/commonUtils/trimQuotes' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants/effectActions.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants/environmentTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants/idNames.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants/targetDataTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants/typeKeys.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/constants/typeToInterfaceFnName.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/d2Functions/getD2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/d2Functions/getD2Functions.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/d2Functions/gs1DataMatrixFuntions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/d2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/d2Functions/zScoreFunctions' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/errorCreator/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/helpers/OptionSetHelper' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/processors/rulesEffectsProcessor/rulesEffectsProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/processors/ValueProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/RulesEngine' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/rulesEngine.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/expressionService/common/getInjectionValue' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/expressionService/common' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/expressionService/executeExpression' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/expressionService/executeExpression.types' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/expressionService' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/expressionService/injectVariableValues' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/constants/eventStatuses' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/helpers' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/helpers/structureEvents' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/variablePrefixes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/build/es/services/VariableService/variableService.types' {
  declare module.exports: any;
}

declare module 'rules-engine/d2.config' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/@typescript-eslint/eslint-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/d2-utilizr_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint-friendly-formatter_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/gen-flow-files_vx.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/flow-typed/npm/loglevel_v1.x.x' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils/normalizeRuleVariable' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils/numberToString' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils/trimQuotes' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/effectActions.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/environmentTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/idNames.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/targetDataTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/typeKeys.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/typeToInterfaceFnName.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/getD2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/getD2Functions.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/gs1DataMatrixFuntions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/zScoreFunctions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/errorCreator/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/src/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/src/helpers/OptionSetHelper' {
  declare module.exports: any;
}

declare module 'rules-engine/src' {
  declare module.exports: any;
}

declare module 'rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/src/processors/ValueProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/src/RulesEngine' {
  declare module.exports: any;
}

declare module 'rules-engine/src/rulesEngine.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/common/getInjectionValue' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/common' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/executeExpression' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/executeExpression.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/injectVariableValues' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/constants/eventStatuses' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/helpers' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/helpers/structureEvents' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/variablePrefixes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/variableService.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rules-engine/build/cjs/commonUtils/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/commonUtils'>;
}
declare module 'rules-engine/build/cjs/commonUtils/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/commonUtils'>;
}
declare module 'rules-engine/build/cjs/commonUtils/normalizeRuleVariable.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/commonUtils/normalizeRuleVariable'>;
}
declare module 'rules-engine/build/cjs/commonUtils/numberToString.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/commonUtils/numberToString'>;
}
declare module 'rules-engine/build/cjs/commonUtils/trimQuotes.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/commonUtils/trimQuotes'>;
}
declare module 'rules-engine/build/cjs/constants/effectActions.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants/effectActions.const'>;
}
declare module 'rules-engine/build/cjs/constants/environmentTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants/environmentTypes.const'>;
}
declare module 'rules-engine/build/cjs/constants/idNames.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants/idNames.const'>;
}
declare module 'rules-engine/build/cjs/constants/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants'>;
}
declare module 'rules-engine/build/cjs/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants'>;
}
declare module 'rules-engine/build/cjs/constants/targetDataTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants/targetDataTypes.const'>;
}
declare module 'rules-engine/build/cjs/constants/typeKeys.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants/typeKeys.const'>;
}
declare module 'rules-engine/build/cjs/constants/typeToInterfaceFnName.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/constants/typeToInterfaceFnName.const'>;
}
declare module 'rules-engine/build/cjs/d2Functions/getD2Functions.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/d2Functions/getD2Functions'>;
}
declare module 'rules-engine/build/cjs/d2Functions/getD2Functions.types.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/d2Functions/getD2Functions.types'>;
}
declare module 'rules-engine/build/cjs/d2Functions/gs1DataMatrixFuntions.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/d2Functions/gs1DataMatrixFuntions'>;
}
declare module 'rules-engine/build/cjs/d2Functions/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/d2Functions'>;
}
declare module 'rules-engine/build/cjs/d2Functions/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/d2Functions'>;
}
declare module 'rules-engine/build/cjs/d2Functions/zScoreFunctions.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/d2Functions/zScoreFunctions'>;
}
declare module 'rules-engine/build/cjs/errorCreator/errorCreator.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/errorCreator/errorCreator'>;
}
declare module 'rules-engine/build/cjs/errorCreator/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/errorCreator'>;
}
declare module 'rules-engine/build/cjs/errorCreator/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/errorCreator'>;
}
declare module 'rules-engine/build/cjs/helpers/OptionSetHelper.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/helpers/OptionSetHelper'>;
}
declare module 'rules-engine/build/cjs/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs'>;
}
declare module 'rules-engine/build/cjs/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs'>;
}
declare module 'rules-engine/build/cjs/processors/rulesEffectsProcessor/rulesEffectsProcessor.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/processors/rulesEffectsProcessor/rulesEffectsProcessor'>;
}
declare module 'rules-engine/build/cjs/processors/ValueProcessor.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/processors/ValueProcessor'>;
}
declare module 'rules-engine/build/cjs/RulesEngine.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/RulesEngine'>;
}
declare module 'rules-engine/build/cjs/rulesEngine.types.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/rulesEngine.types'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/common/getInjectionValue.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService/common/getInjectionValue'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/common/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService/common'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/common/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService/common'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/executeExpression.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService/executeExpression'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/executeExpression.types.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService/executeExpression.types'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService'>;
}
declare module 'rules-engine/build/cjs/services/expressionService/injectVariableValues.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/expressionService/injectVariableValues'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/constants/eventStatuses.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/constants/eventStatuses'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/constants/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/constants'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/constants'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/helpers/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/helpers'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/helpers/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/helpers'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/helpers/structureEvents.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/helpers/structureEvents'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/index' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/index.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/variablePrefixes.const.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/variablePrefixes.const'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/VariableService.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/VariableService'>;
}
declare module 'rules-engine/build/cjs/services/VariableService/variableService.types.js' {
  declare module.exports: $Exports<'rules-engine/build/cjs/services/VariableService/variableService.types'>;
}
declare module 'rules-engine/build/es/commonUtils/index' {
  declare module.exports: $Exports<'rules-engine/build/es/commonUtils'>;
}
declare module 'rules-engine/build/es/commonUtils/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/commonUtils'>;
}
declare module 'rules-engine/build/es/commonUtils/normalizeRuleVariable.js' {
  declare module.exports: $Exports<'rules-engine/build/es/commonUtils/normalizeRuleVariable'>;
}
declare module 'rules-engine/build/es/commonUtils/numberToString.js' {
  declare module.exports: $Exports<'rules-engine/build/es/commonUtils/numberToString'>;
}
declare module 'rules-engine/build/es/commonUtils/trimQuotes.js' {
  declare module.exports: $Exports<'rules-engine/build/es/commonUtils/trimQuotes'>;
}
declare module 'rules-engine/build/es/constants/effectActions.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants/effectActions.const'>;
}
declare module 'rules-engine/build/es/constants/environmentTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants/environmentTypes.const'>;
}
declare module 'rules-engine/build/es/constants/idNames.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants/idNames.const'>;
}
declare module 'rules-engine/build/es/constants/index' {
  declare module.exports: $Exports<'rules-engine/build/es/constants'>;
}
declare module 'rules-engine/build/es/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants'>;
}
declare module 'rules-engine/build/es/constants/targetDataTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants/targetDataTypes.const'>;
}
declare module 'rules-engine/build/es/constants/typeKeys.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants/typeKeys.const'>;
}
declare module 'rules-engine/build/es/constants/typeToInterfaceFnName.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/constants/typeToInterfaceFnName.const'>;
}
declare module 'rules-engine/build/es/d2Functions/getD2Functions.js' {
  declare module.exports: $Exports<'rules-engine/build/es/d2Functions/getD2Functions'>;
}
declare module 'rules-engine/build/es/d2Functions/getD2Functions.types.js' {
  declare module.exports: $Exports<'rules-engine/build/es/d2Functions/getD2Functions.types'>;
}
declare module 'rules-engine/build/es/d2Functions/gs1DataMatrixFuntions.js' {
  declare module.exports: $Exports<'rules-engine/build/es/d2Functions/gs1DataMatrixFuntions'>;
}
declare module 'rules-engine/build/es/d2Functions/index' {
  declare module.exports: $Exports<'rules-engine/build/es/d2Functions'>;
}
declare module 'rules-engine/build/es/d2Functions/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/d2Functions'>;
}
declare module 'rules-engine/build/es/d2Functions/zScoreFunctions.js' {
  declare module.exports: $Exports<'rules-engine/build/es/d2Functions/zScoreFunctions'>;
}
declare module 'rules-engine/build/es/errorCreator/errorCreator.js' {
  declare module.exports: $Exports<'rules-engine/build/es/errorCreator/errorCreator'>;
}
declare module 'rules-engine/build/es/errorCreator/index' {
  declare module.exports: $Exports<'rules-engine/build/es/errorCreator'>;
}
declare module 'rules-engine/build/es/errorCreator/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/errorCreator'>;
}
declare module 'rules-engine/build/es/helpers/OptionSetHelper.js' {
  declare module.exports: $Exports<'rules-engine/build/es/helpers/OptionSetHelper'>;
}
declare module 'rules-engine/build/es/index' {
  declare module.exports: $Exports<'rules-engine/build/es'>;
}
declare module 'rules-engine/build/es/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es'>;
}
declare module 'rules-engine/build/es/processors/rulesEffectsProcessor/rulesEffectsProcessor.js' {
  declare module.exports: $Exports<'rules-engine/build/es/processors/rulesEffectsProcessor/rulesEffectsProcessor'>;
}
declare module 'rules-engine/build/es/processors/ValueProcessor.js' {
  declare module.exports: $Exports<'rules-engine/build/es/processors/ValueProcessor'>;
}
declare module 'rules-engine/build/es/RulesEngine.js' {
  declare module.exports: $Exports<'rules-engine/build/es/RulesEngine'>;
}
declare module 'rules-engine/build/es/rulesEngine.types.js' {
  declare module.exports: $Exports<'rules-engine/build/es/rulesEngine.types'>;
}
declare module 'rules-engine/build/es/services/expressionService/common/getInjectionValue.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService/common/getInjectionValue'>;
}
declare module 'rules-engine/build/es/services/expressionService/common/index' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService/common'>;
}
declare module 'rules-engine/build/es/services/expressionService/common/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService/common'>;
}
declare module 'rules-engine/build/es/services/expressionService/executeExpression.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService/executeExpression'>;
}
declare module 'rules-engine/build/es/services/expressionService/executeExpression.types.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService/executeExpression.types'>;
}
declare module 'rules-engine/build/es/services/expressionService/index' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService'>;
}
declare module 'rules-engine/build/es/services/expressionService/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService'>;
}
declare module 'rules-engine/build/es/services/expressionService/injectVariableValues.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/expressionService/injectVariableValues'>;
}
declare module 'rules-engine/build/es/services/VariableService/constants/eventStatuses.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/constants/eventStatuses'>;
}
declare module 'rules-engine/build/es/services/VariableService/constants/index' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/constants'>;
}
declare module 'rules-engine/build/es/services/VariableService/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/constants'>;
}
declare module 'rules-engine/build/es/services/VariableService/helpers/index' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/helpers'>;
}
declare module 'rules-engine/build/es/services/VariableService/helpers/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/helpers'>;
}
declare module 'rules-engine/build/es/services/VariableService/helpers/structureEvents.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/helpers/structureEvents'>;
}
declare module 'rules-engine/build/es/services/VariableService/index' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService'>;
}
declare module 'rules-engine/build/es/services/VariableService/index.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService'>;
}
declare module 'rules-engine/build/es/services/VariableService/variablePrefixes.const.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/variablePrefixes.const'>;
}
declare module 'rules-engine/build/es/services/VariableService/VariableService.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/VariableService'>;
}
declare module 'rules-engine/build/es/services/VariableService/variableService.types.js' {
  declare module.exports: $Exports<'rules-engine/build/es/services/VariableService/variableService.types'>;
}
declare module 'rules-engine/d2.config.js' {
  declare module.exports: $Exports<'rules-engine/d2.config'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/preset-env_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@babel/preset-flow_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/@typescript-eslint/eslint-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/@typescript-eslint/eslint-plugin_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/d2-utilizr_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/d2-utilizr_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint-friendly-formatter_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint-friendly-formatter_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/gen-flow-files_vx.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/gen-flow-files_vx.x.x'>;
}
declare module 'rules-engine/flow-typed/npm/loglevel_v1.x.x.js' {
  declare module.exports: $Exports<'rules-engine/flow-typed/npm/loglevel_v1.x.x'>;
}
declare module 'rules-engine/src/commonUtils/index' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils'>;
}
declare module 'rules-engine/src/commonUtils/index.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils'>;
}
declare module 'rules-engine/src/commonUtils/normalizeRuleVariable.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils/normalizeRuleVariable'>;
}
declare module 'rules-engine/src/commonUtils/numberToString.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils/numberToString'>;
}
declare module 'rules-engine/src/commonUtils/trimQuotes.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils/trimQuotes'>;
}
declare module 'rules-engine/src/constants/effectActions.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/effectActions.const'>;
}
declare module 'rules-engine/src/constants/environmentTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/environmentTypes.const'>;
}
declare module 'rules-engine/src/constants/idNames.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/idNames.const'>;
}
declare module 'rules-engine/src/constants/index' {
  declare module.exports: $Exports<'rules-engine/src/constants'>;
}
declare module 'rules-engine/src/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/src/constants'>;
}
declare module 'rules-engine/src/constants/targetDataTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/targetDataTypes.const'>;
}
declare module 'rules-engine/src/constants/typeKeys.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/typeKeys.const'>;
}
declare module 'rules-engine/src/constants/typeToInterfaceFnName.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/typeToInterfaceFnName.const'>;
}
declare module 'rules-engine/src/d2Functions/getD2Functions.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/getD2Functions'>;
}
declare module 'rules-engine/src/d2Functions/getD2Functions.types.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/getD2Functions.types'>;
}
declare module 'rules-engine/src/d2Functions/gs1DataMatrixFuntions.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/gs1DataMatrixFuntions'>;
}
declare module 'rules-engine/src/d2Functions/index' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions'>;
}
declare module 'rules-engine/src/d2Functions/index.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions'>;
}
declare module 'rules-engine/src/d2Functions/zScoreFunctions.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/zScoreFunctions'>;
}
declare module 'rules-engine/src/errorCreator/errorCreator.js' {
  declare module.exports: $Exports<'rules-engine/src/errorCreator/errorCreator'>;
}
declare module 'rules-engine/src/errorCreator/index' {
  declare module.exports: $Exports<'rules-engine/src/errorCreator'>;
}
declare module 'rules-engine/src/errorCreator/index.js' {
  declare module.exports: $Exports<'rules-engine/src/errorCreator'>;
}
declare module 'rules-engine/src/helpers/OptionSetHelper.js' {
  declare module.exports: $Exports<'rules-engine/src/helpers/OptionSetHelper'>;
}
declare module 'rules-engine/src/index' {
  declare module.exports: $Exports<'rules-engine/src'>;
}
declare module 'rules-engine/src/index.js' {
  declare module.exports: $Exports<'rules-engine/src'>;
}
declare module 'rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor.js' {
  declare module.exports: $Exports<'rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor'>;
}
declare module 'rules-engine/src/processors/ValueProcessor.js' {
  declare module.exports: $Exports<'rules-engine/src/processors/ValueProcessor'>;
}
declare module 'rules-engine/src/RulesEngine.js' {
  declare module.exports: $Exports<'rules-engine/src/RulesEngine'>;
}
declare module 'rules-engine/src/rulesEngine.types.js' {
  declare module.exports: $Exports<'rules-engine/src/rulesEngine.types'>;
}
declare module 'rules-engine/src/services/expressionService/common/getInjectionValue.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/common/getInjectionValue'>;
}
declare module 'rules-engine/src/services/expressionService/common/index' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/common'>;
}
declare module 'rules-engine/src/services/expressionService/common/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/common'>;
}
declare module 'rules-engine/src/services/expressionService/executeExpression.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/executeExpression'>;
}
declare module 'rules-engine/src/services/expressionService/executeExpression.types.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/executeExpression.types'>;
}
declare module 'rules-engine/src/services/expressionService/index' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService'>;
}
declare module 'rules-engine/src/services/expressionService/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService'>;
}
declare module 'rules-engine/src/services/expressionService/injectVariableValues.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/injectVariableValues'>;
}
declare module 'rules-engine/src/services/VariableService/constants/eventStatuses.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/constants/eventStatuses'>;
}
declare module 'rules-engine/src/services/VariableService/constants/index' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/constants'>;
}
declare module 'rules-engine/src/services/VariableService/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/constants'>;
}
declare module 'rules-engine/src/services/VariableService/helpers/index' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/helpers'>;
}
declare module 'rules-engine/src/services/VariableService/helpers/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/helpers'>;
}
declare module 'rules-engine/src/services/VariableService/helpers/structureEvents.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/helpers/structureEvents'>;
}
declare module 'rules-engine/src/services/VariableService/index' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService'>;
}
declare module 'rules-engine/src/services/VariableService/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService'>;
}
declare module 'rules-engine/src/services/VariableService/variablePrefixes.const.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/variablePrefixes.const'>;
}
declare module 'rules-engine/src/services/VariableService/VariableService.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/VariableService'>;
}
declare module 'rules-engine/src/services/VariableService/variableService.types.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/variableService.types'>;
}
