// flow-typed signature: 1ec53571f93771512712dabb1f96e65d
// flow-typed version: <<STUB>>/rules-engine_v1.1.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rules-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rules-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rules-engine/lib/commonUtils' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/commonUtils/normalizeRuleVariable' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/commonUtils/numberToString' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/commonUtils/trimQuotes' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants/effectActions.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants/environmentTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants/idNames.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants/targetDataTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants/typeKeys.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/constants/typeToInterfaceFnName.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/d2Functions/getD2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/d2Functions/getD2Functions.types' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/d2Functions/gs1DataMatrixFuntions' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/d2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/d2Functions/zScoreFunctions' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/errorCreator/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/helpers/OptionSetHelper' {
  declare module.exports: any;
}

declare module 'rules-engine/lib' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/processors/rulesEffectsProcessor/rulesEffectsProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/processors/ValueProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/RulesEngine' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/rulesEngine.types' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/expressionService/common/getInjectionValue' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/expressionService/common' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/expressionService/executeExpression' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/expressionService/executeExpression.types' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/expressionService' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/expressionService/injectVariableValues' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/constants/eventStatuses' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/helpers' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/helpers/structureEvents' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/variablePrefixes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/lib/services/VariableService/variableService.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils/normalizeRuleVariable' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils/numberToString' {
  declare module.exports: any;
}

declare module 'rules-engine/src/commonUtils/trimQuotes' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/effectActions.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/environmentTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/idNames.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/targetDataTypes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/typeKeys.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/constants/typeToInterfaceFnName.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/getD2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/getD2Functions.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/gs1DataMatrixFuntions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/d2Functions/zScoreFunctions' {
  declare module.exports: any;
}

declare module 'rules-engine/src/errorCreator/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/src/errorCreator' {
  declare module.exports: any;
}

declare module 'rules-engine/src/helpers/OptionSetHelper' {
  declare module.exports: any;
}

declare module 'rules-engine/src' {
  declare module.exports: any;
}

declare module 'rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/src/processors/ValueProcessor' {
  declare module.exports: any;
}

declare module 'rules-engine/src/RulesEngine' {
  declare module.exports: any;
}

declare module 'rules-engine/src/rulesEngine.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/common/getInjectionValue' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/common' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/executeExpression' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/executeExpression.types' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/expressionService/injectVariableValues' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/constants/eventStatuses' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/constants' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/helpers' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/helpers/structureEvents' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/variablePrefixes.const' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/VariableService' {
  declare module.exports: any;
}

declare module 'rules-engine/src/services/VariableService/variableService.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rules-engine/lib/commonUtils/index' {
  declare module.exports: $Exports<'rules-engine/lib/commonUtils'>;
}
declare module 'rules-engine/lib/commonUtils/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/commonUtils'>;
}
declare module 'rules-engine/lib/commonUtils/normalizeRuleVariable.js' {
  declare module.exports: $Exports<'rules-engine/lib/commonUtils/normalizeRuleVariable'>;
}
declare module 'rules-engine/lib/commonUtils/numberToString.js' {
  declare module.exports: $Exports<'rules-engine/lib/commonUtils/numberToString'>;
}
declare module 'rules-engine/lib/commonUtils/trimQuotes.js' {
  declare module.exports: $Exports<'rules-engine/lib/commonUtils/trimQuotes'>;
}
declare module 'rules-engine/lib/constants/effectActions.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants/effectActions.const'>;
}
declare module 'rules-engine/lib/constants/environmentTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants/environmentTypes.const'>;
}
declare module 'rules-engine/lib/constants/idNames.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants/idNames.const'>;
}
declare module 'rules-engine/lib/constants/index' {
  declare module.exports: $Exports<'rules-engine/lib/constants'>;
}
declare module 'rules-engine/lib/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants'>;
}
declare module 'rules-engine/lib/constants/targetDataTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants/targetDataTypes.const'>;
}
declare module 'rules-engine/lib/constants/typeKeys.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants/typeKeys.const'>;
}
declare module 'rules-engine/lib/constants/typeToInterfaceFnName.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/constants/typeToInterfaceFnName.const'>;
}
declare module 'rules-engine/lib/d2Functions/getD2Functions.js' {
  declare module.exports: $Exports<'rules-engine/lib/d2Functions/getD2Functions'>;
}
declare module 'rules-engine/lib/d2Functions/getD2Functions.types.js' {
  declare module.exports: $Exports<'rules-engine/lib/d2Functions/getD2Functions.types'>;
}
declare module 'rules-engine/lib/d2Functions/gs1DataMatrixFuntions.js' {
  declare module.exports: $Exports<'rules-engine/lib/d2Functions/gs1DataMatrixFuntions'>;
}
declare module 'rules-engine/lib/d2Functions/index' {
  declare module.exports: $Exports<'rules-engine/lib/d2Functions'>;
}
declare module 'rules-engine/lib/d2Functions/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/d2Functions'>;
}
declare module 'rules-engine/lib/d2Functions/zScoreFunctions.js' {
  declare module.exports: $Exports<'rules-engine/lib/d2Functions/zScoreFunctions'>;
}
declare module 'rules-engine/lib/errorCreator/errorCreator.js' {
  declare module.exports: $Exports<'rules-engine/lib/errorCreator/errorCreator'>;
}
declare module 'rules-engine/lib/errorCreator/index' {
  declare module.exports: $Exports<'rules-engine/lib/errorCreator'>;
}
declare module 'rules-engine/lib/errorCreator/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/errorCreator'>;
}
declare module 'rules-engine/lib/helpers/OptionSetHelper.js' {
  declare module.exports: $Exports<'rules-engine/lib/helpers/OptionSetHelper'>;
}
declare module 'rules-engine/lib/index' {
  declare module.exports: $Exports<'rules-engine/lib'>;
}
declare module 'rules-engine/lib/index.js' {
  declare module.exports: $Exports<'rules-engine/lib'>;
}
declare module 'rules-engine/lib/processors/rulesEffectsProcessor/rulesEffectsProcessor.js' {
  declare module.exports: $Exports<'rules-engine/lib/processors/rulesEffectsProcessor/rulesEffectsProcessor'>;
}
declare module 'rules-engine/lib/processors/ValueProcessor.js' {
  declare module.exports: $Exports<'rules-engine/lib/processors/ValueProcessor'>;
}
declare module 'rules-engine/lib/RulesEngine.js' {
  declare module.exports: $Exports<'rules-engine/lib/RulesEngine'>;
}
declare module 'rules-engine/lib/rulesEngine.types.js' {
  declare module.exports: $Exports<'rules-engine/lib/rulesEngine.types'>;
}
declare module 'rules-engine/lib/services/expressionService/common/getInjectionValue.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService/common/getInjectionValue'>;
}
declare module 'rules-engine/lib/services/expressionService/common/index' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService/common'>;
}
declare module 'rules-engine/lib/services/expressionService/common/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService/common'>;
}
declare module 'rules-engine/lib/services/expressionService/executeExpression.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService/executeExpression'>;
}
declare module 'rules-engine/lib/services/expressionService/executeExpression.types.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService/executeExpression.types'>;
}
declare module 'rules-engine/lib/services/expressionService/index' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService'>;
}
declare module 'rules-engine/lib/services/expressionService/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService'>;
}
declare module 'rules-engine/lib/services/expressionService/injectVariableValues.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/expressionService/injectVariableValues'>;
}
declare module 'rules-engine/lib/services/VariableService/constants/eventStatuses.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/constants/eventStatuses'>;
}
declare module 'rules-engine/lib/services/VariableService/constants/index' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/constants'>;
}
declare module 'rules-engine/lib/services/VariableService/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/constants'>;
}
declare module 'rules-engine/lib/services/VariableService/helpers/index' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/helpers'>;
}
declare module 'rules-engine/lib/services/VariableService/helpers/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/helpers'>;
}
declare module 'rules-engine/lib/services/VariableService/helpers/structureEvents.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/helpers/structureEvents'>;
}
declare module 'rules-engine/lib/services/VariableService/index' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService'>;
}
declare module 'rules-engine/lib/services/VariableService/index.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService'>;
}
declare module 'rules-engine/lib/services/VariableService/variablePrefixes.const.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/variablePrefixes.const'>;
}
declare module 'rules-engine/lib/services/VariableService/VariableService.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/VariableService'>;
}
declare module 'rules-engine/lib/services/VariableService/variableService.types.js' {
  declare module.exports: $Exports<'rules-engine/lib/services/VariableService/variableService.types'>;
}
declare module 'rules-engine/src/commonUtils/index' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils'>;
}
declare module 'rules-engine/src/commonUtils/index.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils'>;
}
declare module 'rules-engine/src/commonUtils/normalizeRuleVariable.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils/normalizeRuleVariable'>;
}
declare module 'rules-engine/src/commonUtils/numberToString.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils/numberToString'>;
}
declare module 'rules-engine/src/commonUtils/trimQuotes.js' {
  declare module.exports: $Exports<'rules-engine/src/commonUtils/trimQuotes'>;
}
declare module 'rules-engine/src/constants/effectActions.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/effectActions.const'>;
}
declare module 'rules-engine/src/constants/environmentTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/environmentTypes.const'>;
}
declare module 'rules-engine/src/constants/idNames.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/idNames.const'>;
}
declare module 'rules-engine/src/constants/index' {
  declare module.exports: $Exports<'rules-engine/src/constants'>;
}
declare module 'rules-engine/src/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/src/constants'>;
}
declare module 'rules-engine/src/constants/targetDataTypes.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/targetDataTypes.const'>;
}
declare module 'rules-engine/src/constants/typeKeys.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/typeKeys.const'>;
}
declare module 'rules-engine/src/constants/typeToInterfaceFnName.const.js' {
  declare module.exports: $Exports<'rules-engine/src/constants/typeToInterfaceFnName.const'>;
}
declare module 'rules-engine/src/d2Functions/getD2Functions.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/getD2Functions'>;
}
declare module 'rules-engine/src/d2Functions/getD2Functions.types.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/getD2Functions.types'>;
}
declare module 'rules-engine/src/d2Functions/gs1DataMatrixFuntions.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/gs1DataMatrixFuntions'>;
}
declare module 'rules-engine/src/d2Functions/index' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions'>;
}
declare module 'rules-engine/src/d2Functions/index.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions'>;
}
declare module 'rules-engine/src/d2Functions/zScoreFunctions.js' {
  declare module.exports: $Exports<'rules-engine/src/d2Functions/zScoreFunctions'>;
}
declare module 'rules-engine/src/errorCreator/errorCreator.js' {
  declare module.exports: $Exports<'rules-engine/src/errorCreator/errorCreator'>;
}
declare module 'rules-engine/src/errorCreator/index' {
  declare module.exports: $Exports<'rules-engine/src/errorCreator'>;
}
declare module 'rules-engine/src/errorCreator/index.js' {
  declare module.exports: $Exports<'rules-engine/src/errorCreator'>;
}
declare module 'rules-engine/src/helpers/OptionSetHelper.js' {
  declare module.exports: $Exports<'rules-engine/src/helpers/OptionSetHelper'>;
}
declare module 'rules-engine/src/index' {
  declare module.exports: $Exports<'rules-engine/src'>;
}
declare module 'rules-engine/src/index.js' {
  declare module.exports: $Exports<'rules-engine/src'>;
}
declare module 'rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor.js' {
  declare module.exports: $Exports<'rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor'>;
}
declare module 'rules-engine/src/processors/ValueProcessor.js' {
  declare module.exports: $Exports<'rules-engine/src/processors/ValueProcessor'>;
}
declare module 'rules-engine/src/RulesEngine.js' {
  declare module.exports: $Exports<'rules-engine/src/RulesEngine'>;
}
declare module 'rules-engine/src/rulesEngine.types.js' {
  declare module.exports: $Exports<'rules-engine/src/rulesEngine.types'>;
}
declare module 'rules-engine/src/services/expressionService/common/getInjectionValue.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/common/getInjectionValue'>;
}
declare module 'rules-engine/src/services/expressionService/common/index' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/common'>;
}
declare module 'rules-engine/src/services/expressionService/common/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/common'>;
}
declare module 'rules-engine/src/services/expressionService/executeExpression.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/executeExpression'>;
}
declare module 'rules-engine/src/services/expressionService/executeExpression.types.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/executeExpression.types'>;
}
declare module 'rules-engine/src/services/expressionService/index' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService'>;
}
declare module 'rules-engine/src/services/expressionService/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService'>;
}
declare module 'rules-engine/src/services/expressionService/injectVariableValues.js' {
  declare module.exports: $Exports<'rules-engine/src/services/expressionService/injectVariableValues'>;
}
declare module 'rules-engine/src/services/VariableService/constants/eventStatuses.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/constants/eventStatuses'>;
}
declare module 'rules-engine/src/services/VariableService/constants/index' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/constants'>;
}
declare module 'rules-engine/src/services/VariableService/constants/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/constants'>;
}
declare module 'rules-engine/src/services/VariableService/helpers/index' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/helpers'>;
}
declare module 'rules-engine/src/services/VariableService/helpers/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/helpers'>;
}
declare module 'rules-engine/src/services/VariableService/helpers/structureEvents.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/helpers/structureEvents'>;
}
declare module 'rules-engine/src/services/VariableService/index' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService'>;
}
declare module 'rules-engine/src/services/VariableService/index.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService'>;
}
declare module 'rules-engine/src/services/VariableService/variablePrefixes.const.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/variablePrefixes.const'>;
}
declare module 'rules-engine/src/services/VariableService/VariableService.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/VariableService'>;
}
declare module 'rules-engine/src/services/VariableService/variableService.types.js' {
  declare module.exports: $Exports<'rules-engine/src/services/VariableService/variableService.types'>;
}
