// @flow
import type { FetchError, QueryRefetchFunction } from '@dhis2/app-runtime';

export type Props = {|
    teiId: string,
    enrollmentId: string,
    programId: string,
    readOnlyMode?: boolean,
    onDelete: () => void,
    onAddNew: () => void,
    onUpdateEnrollmentDate?: (enrollmentDate: string) => void,
    onUpdateIncidentDate?: (enrollmentDate: string) => void,
    onError?: (message: string) => void,
    onSuccess?: () => void,
    onAccessLostFromTransfer?: () => void,
|};

export type PlainProps = {|
    enrollment: Object,
    program: Object,
    ownerOrgUnit: Object,
    locale: string,
    refetchEnrollment: QueryRefetchFunction,
    refetchTEI: QueryRefetchFunction,
    initError?: FetchError,
    loading: boolean,
    canAddNew: boolean,
    editDateEnabled: boolean,
    displayAutoGeneratedEventWarning: boolean,
    updateEnrollmentDate: (enrollmentDate: string) => void,
    updateIncidentDate: (incidentDate: string) => void,
    onDelete: () => void,
    onAddNew: () => void,
    onError?: (message: string) => void,
    onSuccess?: () => void,
    onAccessLostFromTransfer?: () => void,
    ...CssClasses,
|};
