import type { QueryRefetchFunction } from 'capture-core-utils/types/app-runtime';
import type { ApiEnrollmentEvent } from 'capture-core-utils/types/api-types';

export type EventReducerProps = {
    enrollments?: Array<Record<string, unknown>> | null;
    events: Array<ApiEnrollmentEvent>;
};

export type Props = {
    teiId: string;
    enrollmentId: string;
    programId: string;
    readOnlyMode?: boolean;
    externalData: { status: { value: string | null }; events?: Array<Record<string, unknown>> | null };
    onDelete: () => void;
    onAddNew: () => void;
    onUpdateEnrollmentDate?: (enrollmentDate: string) => void;
    onUpdateIncidentDate?: (enrollmentDate: string) => void;
    onError?: (message: string) => void;
    onSuccess?: () => void;
    onUpdateEnrollmentStatus?: (enrollment: Record<string, unknown>) => void;
    onUpdateEnrollmentStatusSuccess?: (params: { redirect?: boolean }) => void;
    onUpdateEnrollmentStatusError?: (message: string) => void;
    onAccessLostFromTransfer?: () => void;
};

export type PlainProps = {
    enrollment: Record<string, unknown>;
    events: Array<{ status: string; event: string; programStage: string }>;
    program: Record<string, unknown>;
    ownerOrgUnit: Record<string, unknown>;
    locale: string;
    refetchEnrollment: QueryRefetchFunction;
    refetchTEI: QueryRefetchFunction;
    initError?: boolean;
    loading: boolean;
    canAddNew: boolean;
    editDateEnabled: boolean;
    displayAutoGeneratedEventWarning: boolean;
    updateEnrollmentDate: (enrollmentDate: string) => void;
    updateIncidentDate: (incidentDate: string) => void;
    onDelete: () => void;
    onAddNew: () => void;
    onError?: (message: string) => void;
    onSuccess?: () => void;
    onUpdateEnrollmentStatus?: (enrollment: Record<string, unknown>) => void;
    onUpdateEnrollmentStatusSuccess?: (params: { redirect?: boolean }) => void;
    onUpdateEnrollmentStatusError?: (message: string) => void;
    onAccessLostFromTransfer?: () => void;
};
