import React, { useState, useCallback } from 'react';
import moment from 'moment';
import {
    IconClock16,
    IconDimensionOrgUnit16,
    colors,
    Tag,
    spacersNum,
    Tooltip,
} from '@dhis2/ui';
import i18n from '@dhis2/d2-i18n';
import { useTimeZoneConversion } from '@dhis2/app-runtime';
import { withStyles, type WithStyles } from '@material-ui/core';
import { LoadingMaskElementCenter } from '../LoadingMasks';
import { Widget } from '../Widget';

import { Status } from './Status';
import { dataElementTypes } from '../../metaData';
import { convertValue } from '../../converters/clientToView';
import { useOrgUnitNameWithAncestors } from '../../metadataRetrieval/orgUnitName';
import { Date } from './Date';
import { Actions } from './Actions';
import { MiniMap } from './MiniMap';
import type { PlainProps } from './enrollment.types';

const styles = {
    enrollment: {
        padding: `0 ${spacersNum.dp16}px ${spacersNum.dp16}px ${spacersNum.dp16}px`,
    },
    row: {
        display: 'flex',
        alignItems: 'center',
        margin: `${spacersNum.dp8}px 0`,
        fontSize: '14px',
        color: colors.grey900,
        gap: `${spacersNum.dp4}px`,
    },
    statuses: {
        display: 'flex',
        gap: `${spacersNum.dp4}px`,
    },
    icon: {},
    followup: {},
};

const getGeometryType = (geometryType: string) =>
    (geometryType === 'Point' ? dataElementTypes.COORDINATE : dataElementTypes.POLYGON);
const getEnrollmentDateLabel = (program: any) => program.displayEnrollmentDateLabel ?? i18n.t('Enrollment date');
const getIncidentDateLabel = (program: any) => program.displayIncidentDateLabel ?? i18n.t('Incident date');

export const WidgetEnrollmentPlain = ({
    classes,
    events,
    enrollment,
    program,
    ownerOrgUnit,
    locale,
    refetchEnrollment,
    refetchTEI,
    initError,
    loading,
    canAddNew,
    editDateEnabled,
    displayAutoGeneratedEventWarning,
    onDelete,
    onAddNew,
    updateEnrollmentDate,
    updateIncidentDate,
    onError,
    onSuccess,
    onUpdateEnrollmentStatus,
    onUpdateEnrollmentStatusError,
    onUpdateEnrollmentStatusSuccess,
    onAccessLostFromTransfer,
}: PlainProps & WithStyles<typeof styles>) => {
    const [open, setOpenStatus] = useState(true);
    const { fromServerDate } = useTimeZoneConversion();
    const localDateTime: string = convertValue(enrollment.updatedAt, dataElementTypes.DATETIME) as string;
    const geometryType = getGeometryType((enrollment.geometry as any)?.type);
    const { displayName: orgUnitName, ancestors } = useOrgUnitNameWithAncestors(enrollment.orgUnit);
    const { displayName: ownerOrgUnitName, ancestors: ownerAncestors } = useOrgUnitNameWithAncestors(ownerOrgUnit.id);

    const orgUnitClientValue = { id: enrollment.orgUnit, name: orgUnitName, ancestors };
    const ownerOrgUnitClientValue = { id: ownerOrgUnit.id, name: ownerOrgUnitName, ancestors: ownerAncestors };

    return (
        <div data-test="widget-enrollment">
            <Widget
                header={i18n.t('Enrollment')}
                onOpen={useCallback(() => setOpenStatus(true), [setOpenStatus])}
                onClose={useCallback(() => setOpenStatus(false), [setOpenStatus])}
                open={open}
            >
                {initError && (
                    <div className={classes.enrollment}>
                        {i18n.t('Enrollment widget could not be loaded. Please try again later')}
                    </div>
                )}
                {loading && <LoadingMaskElementCenter />}
                {!initError && !loading && (
                    <div className={classes.enrollment} data-test="widget-enrollment-contents">
                        <div className={classes.statuses} data-test="widget-enrollment-status">
                            {(enrollment.followUp as boolean) && (
                                <Tag className={classes.followup} negative>
                                    {i18n.t('Follow-up')}
                                </Tag>
                            )}
                            <Status status={enrollment.status} />
                        </div>

                        <span data-test="widget-enrollment-enrollment-date">
                            <Date
                                date={enrollment.enrolledAt}
                                dateLabel={getEnrollmentDateLabel(program)}
                                locale={locale}
                                editEnabled={editDateEnabled}
                                displayAutoGeneratedEventWarning={displayAutoGeneratedEventWarning}
                                onSave={updateEnrollmentDate}
                                allowFutureDate={program.selectEnrollmentDatesInFuture}
                            />
                        </span>

                        {(program.displayIncidentDate as boolean) && (
                            <span data-test="widget-enrollment-incident-date">
                                <Date
                                    date={enrollment.occurredAt}
                                    dateLabel={getIncidentDateLabel(program)}
                                    locale={locale}
                                    editEnabled={editDateEnabled}
                                    displayAutoGeneratedEventWarning={displayAutoGeneratedEventWarning}
                                    onSave={updateIncidentDate}
                                    allowFutureDate={program.selectIncidentDatesInFuture}
                                />
                            </span>
                        )}

                        <div className={classes.row} data-test="widget-enrollment-orgunit">
                            <span className={classes.icon} data-test="widget-enrollment-icon-orgunit">
                                <IconDimensionOrgUnit16 color={colors.grey600} />
                            </span>
                            {i18n.t('Started at{{escape}}', {
                                escape: ':',
                            })}
                            {convertValue(orgUnitClientValue, dataElementTypes.ORGANISATION_UNIT)}
                        </div>

                        <div className={classes.row} data-test="widget-enrollment-owner-orgunit">
                            <span className={classes.icon} data-test="widget-enrollment-icon-owner-orgunit">
                                <IconDimensionOrgUnit16 color={colors.grey600} />
                            </span>
                            {i18n.t('Owned by{{escape}}', {
                                escape: ':',
                            })}
                            {convertValue(ownerOrgUnitClientValue, dataElementTypes.ORGANISATION_UNIT)}
                        </div>

                        <div className={classes.row} data-test="widget-enrollment-last-update">
                            <span className={classes.icon} data-test="widget-enrollment-icon-clock">
                                <IconClock16 color={colors.grey600} />
                            </span>
                            {i18n.t('Last updated')}
                            <Tooltip content={localDateTime}>
                                {moment(fromServerDate(enrollment.updatedAt as string)).fromNow()}
                            </Tooltip>
                        </div>

                        {(enrollment.geometry as any) && (
                            <div className={classes.row}>
                                <MiniMap
                                    coordinates={(enrollment.geometry as any).coordinates}
                                    geometryType={geometryType}
                                    enrollment={enrollment}
                                    refetchEnrollment={refetchEnrollment}
                                    refetchTEI={refetchTEI}
                                    onError={onError}
                                />
                            </div>
                        )}
                        <Actions
                            tetName={(program.trackedEntityType as any).displayName}
                            onlyEnrollOnce={program.onlyEnrollOnce as boolean}
                            programStages={program.programStages as any}
                            enrollment={enrollment}
                            events={events}
                            ownerOrgUnitId={ownerOrgUnit.id as string}
                            refetchEnrollment={refetchEnrollment}
                            refetchTEI={refetchTEI}
                            onDelete={onDelete}
                            onAddNew={onAddNew}
                            canAddNew={canAddNew}
                            onError={onError}
                            onSuccess={onSuccess}
                            onUpdateEnrollmentStatus={onUpdateEnrollmentStatus}
                            onUpdateEnrollmentStatusSuccess={onUpdateEnrollmentStatusSuccess as any}
                            onUpdateEnrollmentStatusError={onUpdateEnrollmentStatusError}
                            onAccessLostFromTransfer={onAccessLostFromTransfer}
                        />
                    </div>
                )}
            </Widget>
        </div>
    );
};

export const WidgetEnrollment = withStyles(styles)(WidgetEnrollmentPlain);
