//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import i18n from '@dhis2/d2-i18n';
import moment from 'moment';
import 'moment/locale/ar';
import 'moment/locale/bn';
import 'moment/locale/es';
import 'moment/locale/fr';
import 'moment/locale/lo';
import 'moment/locale/nb';
import 'moment/locale/pt';
import 'moment/locale/ru';
import 'moment/locale/sv';
import 'moment/locale/tg';
import 'moment/locale/uk';
import 'moment/locale/ur';
import 'moment/locale/vi';
import 'moment/locale/zh-cn';

import arTranslations from './ar/translations.json';
import ar_IQTranslations from './ar_IQ/translations.json';
import bnTranslations from './bn/translations.json';
import ckbTranslations from './ckb/translations.json';
import csTranslations from './cs/translations.json';
import daTranslations from './da/translations.json';
import enTranslations from './en/translations.json';
import esTranslations from './es/translations.json';
import frTranslations from './fr/translations.json';
import idTranslations from './id/translations.json';
import kmTranslations from './km/translations.json';
import loTranslations from './lo/translations.json';
import myTranslations from './my/translations.json';
import nbTranslations from './nb/translations.json';
import prsTranslations from './prs/translations.json';
import psTranslations from './ps/translations.json';
import ptTranslations from './pt/translations.json';
import pt_BRTranslations from './pt_BR/translations.json';
import ruTranslations from './ru/translations.json';
import svTranslations from './sv/translations.json';
import tetTranslations from './tet/translations.json';
import tgTranslations from './tg/translations.json';
import ukTranslations from './uk/translations.json';
import urTranslations from './ur/translations.json';
import uzTranslations from './uz/translations.json';
import uz_CyrlTranslations from './uz_Cyrl/translations.json';
import uz_LatnTranslations from './uz_Latn/translations.json';
import viTranslations from './vi/translations.json';
import zhTranslations from './zh/translations.json';
import zh_CNTranslations from './zh_CN/translations.json';

const namespace = 'default';
moment.locale('en');

i18n.addResources('ar', namespace, arTranslations);
i18n.addResources('ar_IQ', namespace, ar_IQTranslations);
i18n.addResources('bn', namespace, bnTranslations);
i18n.addResources('ckb', namespace, ckbTranslations);
i18n.addResources('cs', namespace, csTranslations);
i18n.addResources('da', namespace, daTranslations);
i18n.addResources('en', namespace, enTranslations);
i18n.addResources('es', namespace, esTranslations);
i18n.addResources('fr', namespace, frTranslations);
i18n.addResources('id', namespace, idTranslations);
i18n.addResources('km', namespace, kmTranslations);
i18n.addResources('lo', namespace, loTranslations);
i18n.addResources('my', namespace, myTranslations);
i18n.addResources('nb', namespace, nbTranslations);
i18n.addResources('prs', namespace, prsTranslations);
i18n.addResources('ps', namespace, psTranslations);
i18n.addResources('pt', namespace, ptTranslations);
i18n.addResources('pt_BR', namespace, pt_BRTranslations);
i18n.addResources('ru', namespace, ruTranslations);
i18n.addResources('sv', namespace, svTranslations);
i18n.addResources('tet', namespace, tetTranslations);
i18n.addResources('tg', namespace, tgTranslations);
i18n.addResources('uk', namespace, ukTranslations);
i18n.addResources('ur', namespace, urTranslations);
i18n.addResources('uz', namespace, uzTranslations);
i18n.addResources('uz_Cyrl', namespace, uz_CyrlTranslations);
i18n.addResources('uz_Latn', namespace, uz_LatnTranslations);
i18n.addResources('vi', namespace, viTranslations);
i18n.addResources('zh', namespace, zhTranslations);
i18n.addResources('zh_CN', namespace, zh_CNTranslations);

i18n.setDefaultNamespace(namespace);
i18n.changeLanguage('en');

export default i18n;
