// flow-typed signature: 277470e22bbe1b4af1c7cb1a01233edc
// flow-typed version: <<STUB>>/gen-flow-files_v^0.5.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gen-flow-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gen-flow-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gen-flow-files/bin/gen-flow-files' {
  declare module.exports: any;
}

declare module 'gen-flow-files/dist/cli' {
  declare module.exports: any;
}

declare module 'gen-flow-files/dist/plugin' {
  declare module.exports: any;
}

declare module 'gen-flow-files/dist/traverse' {
  declare module.exports: any;
}

declare module 'gen-flow-files/dist/visitior' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gen-flow-files/bin/gen-flow-files.js' {
  declare module.exports: $Exports<'gen-flow-files/bin/gen-flow-files'>;
}
declare module 'gen-flow-files/dist/cli.js' {
  declare module.exports: $Exports<'gen-flow-files/dist/cli'>;
}
declare module 'gen-flow-files/dist/plugin.js' {
  declare module.exports: $Exports<'gen-flow-files/dist/plugin'>;
}
declare module 'gen-flow-files/dist/traverse.js' {
  declare module.exports: $Exports<'gen-flow-files/dist/traverse'>;
}
declare module 'gen-flow-files/dist/visitior.js' {
  declare module.exports: $Exports<'gen-flow-files/dist/visitior'>;
}
declare module 'gen-flow-files/index' {
  declare module.exports: $Exports<'gen-flow-files'>;
}
declare module 'gen-flow-files/index.js' {
  declare module.exports: $Exports<'gen-flow-files'>;
}
