export const PERIODS = {
    TODAY: 'TODAY',
    THIS_WEEK: 'THIS_WEEK',
    THIS_MONTH: 'THIS_MONTH',
    THIS_YEAR: 'THIS_YEAR',
    LAST_WEEK: 'LAST_WEEK',
    LAST_MONTH: 'LAST_MONTH',
    LAST_3_MONTHS: 'LAST_3_MONTHS',
    CUSTOM_RANGE: 'CUSTOM_RANGE',
};

export const DATE_TYPES = {
    ABSOLUTE: 'ABSOLUTE',
    RELATIVE: 'RELATIVE',
};
