export const RELATIONSHIP_ENTITIES: {
    readonly PROGRAM_STAGE_INSTANCE: 'PROGRAM_STAGE_INSTANCE';
    readonly TRACKED_ENTITY_INSTANCE: 'TRACKED_ENTITY_INSTANCE';
    readonly PROGRAM_INSTANCE: 'PROGRAM_INSTANCE';
} = Object.freeze({
    PROGRAM_STAGE_INSTANCE: 'PROGRAM_STAGE_INSTANCE',
    TRACKED_ENTITY_INSTANCE: 'TRACKED_ENTITY_INSTANCE',
    PROGRAM_INSTANCE: 'PROGRAM_INSTANCE',
});
