// @flow
import { theme as dhis2Theme, colors } from '@dhis2/ui';

const HTMLFONTSIZE = 16;

export const theme = {
    direction: 'ltr',
    breakpoints: {
        values: {
            xs: 0, // phone
            sm: 600, // tablet
            md: 960, // small laptop
            lg: 1280, // desktop
            xl: 1920, // large screen
        },
    },
    palette: {
        type: 'light',
        primary: {
            main: '#1976D2',
            dark: '#004BA0',
            light: colors.blue600,
            lightest: '#EAF4FF',
            /*   50: dhis2Theme.primary050,
            100: dhis2Theme.primary100,
            200: dhis2Theme.primary200,
            300: dhis2Theme.primary300,
            400: dhis2Theme.primary400,
            500: dhis2Theme.primary500,
            600: dhis2Theme.primary600,
            700: dhis2Theme.primary700,
            800: dhis2Theme.primary800,
            900: dhis2Theme.primary900, */
            contrastText: '#fff',
        },
        secondary: {
            main: colors.teal600,
            dark: '#004C40',
            light: '#48A999',
            lightest: colors.teal200,
            /*    50: dhis2Theme.secondary050,
            100: dhis2Theme.secondary100,
            200: dhis2Theme.secondary200,
            300: dhis2Theme.secondary300,
            400: dhis2Theme.secondary400,
            500: dhis2Theme.secondary500,
            600: dhis2Theme.secondary600,
            700: dhis2Theme.secondary700,
            800: dhis2Theme.secondary800,
            900: dhis2Theme.secondary900, */
            contrastText: '#fff',
        },
        success: {
            main: '#3D9305',
            green600: colors.green600,
        },
        warning: {
            lighter: '#FFF9C4',
            light: '#FFF176',
            main: '#F19C02',
            dark: '#F57F17',
        },
        error: {
            lighter: '#FBEAE5',
            light: colors.red300,
            main: '#E53935',
            dark: colors.red500,
            contrastText: '#fff',
            red200: colors.red200,
        },
        red: {
            /*   50: colors.red050,
            100: colors.red100,
            200: colors.red200,
            300: colors.red300,
            400: colors.red400,
            500: colors.red500,
            600: colors.red600,
            700: colors.red700,
            800: colors.red800,
            900: colors.red900, */
        },
        grey: {
            /*  50: colors.grey050,
            100: colors.grey100,
            200: colors.grey200,
            300: colors.grey300,
            400: colors.grey400,
            500: colors.grey500,
            600: colors.grey600,
            700: colors.grey700,
            800: colors.grey800,
            900: colors.grey900, */
            A100: '#d5d5d5',
            A200: '#aaaaaa',
            A400: '#303030',
            A700: '#616161',
            main: '#9E9E9E',
            light: '#E0E0E0',
            lighter: '#F6F6F6',
            lightest: '#FBFBFB',
            dark: '#494949',
            blueGrey: '#ECEFF1',
            snow: '#F4F6F8',
            black: '#000000',
        },
        text: {
            primary: 'rgba(0, 0, 0, 0.87)',
            secondary: 'rgba(0, 0, 0, 0.54)',
            disabled: 'rgba(0, 0, 0, 0.38)',
            hint: 'rgba(0, 0, 0, 0.38)',
        },
        contrastThreshold: 3,
        tonalOffset: 0.2,
        action: {
            active: 'rgba(0, 0, 0, 0.54)',
            hover: 'rgba(0, 0, 0, 0.08)',
            hoverOpacity: 0.08,
            selected: 'rgba(0, 0, 0, 0.14)',
            disabled: 'rgba(0, 0, 0, 0.26)',
            disabledBackground: 'rgba(0, 0, 0, 0.12)',
        },
        info: {
            main: '#EAF4FF',
        },
        accent: {
            lighter: colors.blue100,
            light: '#BBDEFB',
            main: '#64b5F6',
            dark: colors.blue500,
            contrastText: '#000000',
        },
        input: {
            bottomLine: 'rgba(0, 0, 0, 0.42)',
        },
        divider: 'rgba(0, 0, 0, 0.12)',
        dividerForm: '#f2f4f5',
        dividerDarker: 'rgba(0, 0, 0, 1)',
        dividerLighter: 'rgba(224, 224, 224, 1)',
        default: dhis2Theme.default,
        disabled: dhis2Theme.disabled,
        required: colors.red400,
        focus: dhis2Theme.focus,
    },
    typography: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontSize: 14,
        fontWeightLight: 300,
        fontWeightRegular: 400,
        fontWeightMedium: 500,
        pxToRem(size: number) {
            const coef = this.fontSize / 14;
            return `${(size / HTMLFONTSIZE) * coef}rem`;
        },
        display4: {
            fontSize: '7rem',
            fontWeight: 300,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            letterSpacing: '-.04em',
            lineHeight: '1.14286em',
            marginLeft: '-.04em',
            color: 'rgba(0, 0, 0, 0.54)',
        },
        display3: {
            fontSize: '3.5rem',
            fontWeight: 400,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            letterSpacing: '-.02em',
            lineHeight: '1.30357em',
            marginLeft: '-.02em',
            color: 'rgba(0, 0, 0, 0.54)',
        },
        display2: {
            fontSize: '2.8125rem',
            fontWeight: 400,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            lineHeight: '1.13333em',
            marginLeft: '-.02em',
            color: 'rgba(0, 0, 0, 0.54)',
        },
        display1: {
            fontSize: '2.125rem',
            fontWeight: 400,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            lineHeight: '1.20588em',
            color: 'rgba(0, 0, 0, 0.54)',
        },
        headline: {
            fontSize: '1.5rem',
            fontWeight: 400,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            lineHeight: '1.35417em',
            color: 'rgba(0, 0, 0, 0.87)',
        },
        title: {
            fontSize: '1.3125rem',
            fontWeight: 500,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            lineHeight: '1.16667em',
            color: 'rgba(0, 0, 0, 0.87)',
        },
        subheading: {
            fontSize: '1rem',
            fontWeight: 400,
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            lineHeight: '1.5em',
            color: 'rgba(0, 0, 0, 0.87)',
        },
        body2: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '0.875rem',
            lineHeight: 1.5,
            letterSpacing: '0.01071em',
        },
        body1: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '1rem',
            lineHeight: 1.5,
            letterSpacing: '0.00938em',
        },
        caption: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '0.75rem',
            lineHeight: 1.66,
            letterSpacing: '0.03333em',
        },
        button: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 500,
            fontSize: '0.875rem',
            lineHeight: 1.75,
            letterSpacing: '0.02857em',
            textTransform: 'uppercase',
        },
        h1: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 300,
            fontSize: '6rem',
            lineHeight: 1,
            letterSpacing: '-0.01562em',
        },
        h2: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 300,
            fontSize: '3.75rem',
            lineHeight: 1,
            letterSpacing: '-0.00833em',
        },
        h3: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '3rem',
            lineHeight: 1.04,
            letterSpacing: '0em',
        },
        h4: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '2.125rem',
            lineHeight: 1.17,
            letterSpacing: '0.00735em',
        },
        h5: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '1.5rem',
            lineHeight: 1.33,
            letterSpacing: '0em',
        },
        h6: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 500,
            fontSize: '1.25rem',
            lineHeight: 1.6,
            letterSpacing: '0.0075em',
        },
        subtitle1: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '1rem',
            lineHeight: 1.75,
            letterSpacing: '0.00938em',
        },
        subtitle2: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 500,
            fontSize: '0.875rem',
            lineHeight: 1.57,
            letterSpacing: '0.00714em',
        },
        body1Next: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '1rem',
            lineHeight: 1.5,
            letterSpacing: '0.00938em',
        },
        body2Next: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '0.875rem',
            lineHeight: 1.5,
            letterSpacing: '0.01071em',
        },
        buttonNext: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 500,
            fontSize: '0.875rem',
            lineHeight: 1.75,
            letterSpacing: '0.02857em',
            textTransform: 'uppercase',
        },
        captionNext: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '0.75rem',
            lineHeight: 1.66,
            letterSpacing: '0.03333em',
        },
        overline: {
            color: 'rgba(0, 0, 0, 0.87)',
            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
            fontWeight: 400,
            fontSize: '0.75rem',
            lineHeight: 2.66,
            letterSpacing: '0.08333em',
            textTransform: 'uppercase',
        },
        useNextVariants: true,
        formFieldTitle: {
            fontSize: '0.75rem',
        },
    },
    mixins: {
        toolbar: {
            minHeight: 56,
            '@media (min-width:0px) and (orientation: landscape)': {
                minHeight: 48,
            },
            '@media (min-width:600px)': {
                minHeight: 64,
            },
        },
    },
    overrides: {
        MuiDialog: {
            paperWidthLg: {
                width: 800,
            },
        },
        MuiSvgIcon: {
            colorAction: {
                color: '#494949',
            },
        },
        MuiCircularProgress: {
            colorPrimary: {
                color: '#147cd7',
            },
        },
    },
    shape: {
        borderRadius: 4,
    },
    spacing: {
        unit: 8,
    },
    transitions: {
        easing: {
            easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
            easeOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
            easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
            sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
        },
        duration: {
            shortest: 150,
            shorter: 200,
            short: 250,
            standard: 300,
            complex: 375,
            enteringScreen: 225,
            leavingScreen: 195,
        },
    },
    zIndex: {
        mobileStepper: 1000,
        appBar: 1100,
        drawer: 1200,
        modal: 1300,
        snackbar: 1400,
        tooltip: 1500,
    },
};
