// flow-typed signature: 89e3b61f3bed4cf5052eca0d8dee3d95
// flow-typed version: <<STUB>>/@dhis2/app-runtime_v^2.3.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/app-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/app-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/app-runtime/build/cjs/lib' {
  declare module.exports: any;
}

declare module '@dhis2/app-runtime/build/es/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/app-runtime/build/cjs/lib.js' {
  declare module.exports: $Exports<'@dhis2/app-runtime/build/cjs/lib'>;
}
declare module '@dhis2/app-runtime/build/es/lib.js' {
  declare module.exports: $Exports<'@dhis2/app-runtime/build/es/lib'>;
}
