// flow-typed signature: 6b7a44e4abb9853a2939e68e6e1e2d32
// flow-typed version: <<STUB>>/@dhis2/cli-helpers-engine_v^2.1.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/cli-helpers-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/cli-helpers-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/cli-helpers-engine/lib/cache/Cache' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/cache/fetchAndExtract' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/cache' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/cache/middleware' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/configDefaults' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/exec' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/groupGlobalOptions' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/makeEntryPoint' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/namespace' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/notifyOfUpdates' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/prompt' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/reporter' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/tryCatchAsync' {
  declare module.exports: any;
}

declare module '@dhis2/cli-helpers-engine/lib/utils/strings' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/cli-helpers-engine/index' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine'>;
}
declare module '@dhis2/cli-helpers-engine/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine'>;
}
declare module '@dhis2/cli-helpers-engine/lib/cache/Cache.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/cache/Cache'>;
}
declare module '@dhis2/cli-helpers-engine/lib/cache/fetchAndExtract.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/cache/fetchAndExtract'>;
}
declare module '@dhis2/cli-helpers-engine/lib/cache/index' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/cache'>;
}
declare module '@dhis2/cli-helpers-engine/lib/cache/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/cache'>;
}
declare module '@dhis2/cli-helpers-engine/lib/cache/middleware.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/cache/middleware'>;
}
declare module '@dhis2/cli-helpers-engine/lib/configDefaults.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/configDefaults'>;
}
declare module '@dhis2/cli-helpers-engine/lib/exec.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/exec'>;
}
declare module '@dhis2/cli-helpers-engine/lib/groupGlobalOptions.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/groupGlobalOptions'>;
}
declare module '@dhis2/cli-helpers-engine/lib/makeEntryPoint.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/makeEntryPoint'>;
}
declare module '@dhis2/cli-helpers-engine/lib/namespace.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/namespace'>;
}
declare module '@dhis2/cli-helpers-engine/lib/notifyOfUpdates.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/notifyOfUpdates'>;
}
declare module '@dhis2/cli-helpers-engine/lib/prompt.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/prompt'>;
}
declare module '@dhis2/cli-helpers-engine/lib/reporter.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/reporter'>;
}
declare module '@dhis2/cli-helpers-engine/lib/tryCatchAsync.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/tryCatchAsync'>;
}
declare module '@dhis2/cli-helpers-engine/lib/utils/strings.js' {
  declare module.exports: $Exports<'@dhis2/cli-helpers-engine/lib/utils/strings'>;
}
