// flow-typed signature: ff3abc0b05f164061005f127255817e2
// flow-typed version: <<STUB>>/@dhis2/cli-utils-cypress_v^2.2.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/cli-utils-cypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/cli-utils-cypress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/cli-utils-cypress/cucumber' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/plugins' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/common/sharedCLIOptions' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/install' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/install/createCucumberConfigs' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/install/createCypressConfig' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/install/createCypressEnvConfig' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/install/createCypressSupportFile' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/install/ensureDirectories' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/open' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/commands/run' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/tools/execCypress' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/tools/getCypressCommand' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/tools/waitOnAndCypress' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/utils/fs' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/utils/paths' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/src/utils/run' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/steps' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/support' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/templates/cucumber-config' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/templates/plugins' {
  declare module.exports: any;
}

declare module '@dhis2/cli-utils-cypress/templates/support' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/cli-utils-cypress/cucumber.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/cucumber'>;
}
declare module '@dhis2/cli-utils-cypress/plugins.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/plugins'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/common/sharedCLIOptions.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/common/sharedCLIOptions'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/install.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/install'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/install/createCucumberConfigs.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/install/createCucumberConfigs'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/install/createCypressConfig.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/install/createCypressConfig'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/install/createCypressEnvConfig.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/install/createCypressEnvConfig'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/install/createCypressSupportFile.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/install/createCypressSupportFile'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/install/ensureDirectories.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/install/ensureDirectories'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/open.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/open'>;
}
declare module '@dhis2/cli-utils-cypress/src/commands/run.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/commands/run'>;
}
declare module '@dhis2/cli-utils-cypress/src/index' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src'>;
}
declare module '@dhis2/cli-utils-cypress/src/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src'>;
}
declare module '@dhis2/cli-utils-cypress/src/tools/execCypress.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/tools/execCypress'>;
}
declare module '@dhis2/cli-utils-cypress/src/tools/getCypressCommand.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/tools/getCypressCommand'>;
}
declare module '@dhis2/cli-utils-cypress/src/tools/waitOnAndCypress.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/tools/waitOnAndCypress'>;
}
declare module '@dhis2/cli-utils-cypress/src/utils/fs.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/utils/fs'>;
}
declare module '@dhis2/cli-utils-cypress/src/utils/paths.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/utils/paths'>;
}
declare module '@dhis2/cli-utils-cypress/src/utils/run.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/src/utils/run'>;
}
declare module '@dhis2/cli-utils-cypress/steps.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/steps'>;
}
declare module '@dhis2/cli-utils-cypress/support.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/support'>;
}
declare module '@dhis2/cli-utils-cypress/templates/cucumber-config.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/templates/cucumber-config'>;
}
declare module '@dhis2/cli-utils-cypress/templates/plugins.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/templates/plugins'>;
}
declare module '@dhis2/cli-utils-cypress/templates/support.js' {
  declare module.exports: $Exports<'@dhis2/cli-utils-cypress/templates/support'>;
}
