// flow-typed signature: 522c3cdf2366afe55a40a93d66b99a9e
// flow-typed version: <<STUB>>/@dhis2/cli-app-scripts_v^4.0.9/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/cli-app-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/cli-app-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/cli-app-scripts/config/app.babel.config' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/babel.config' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/d2.config.app' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/d2.config.lib' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/init.App.test' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/init.entrypoint' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/jest.config' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/jest.file.mock' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/jest.identity.mock' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/jest.styled-jsx-css.mock' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/jest.transform' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/config/rollup.config' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/commands/build' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/commands/clean' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/commands/i18n' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/commands/init' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/commands/start' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/commands/test' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/bundleApp' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/compiler/compile' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/compiler/compileApp' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/compiler/compileLibrary' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/compiler' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/exitOnCatch' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/generateManifest' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/i18n/extract' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/i18n/generate' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/i18n/helpers' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/i18n' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/i18n/locales' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/i18n/validate' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/loadEnvFiles' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/parseConfig' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/paths' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/shell/bootstrap' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/shell/env' {
  declare module.exports: any;
}

declare module '@dhis2/cli-app-scripts/src/lib/shell' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/cli-app-scripts/config/app.babel.config.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/app.babel.config'>;
}
declare module '@dhis2/cli-app-scripts/config/babel.config.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/babel.config'>;
}
declare module '@dhis2/cli-app-scripts/config/d2.config.app.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/d2.config.app'>;
}
declare module '@dhis2/cli-app-scripts/config/d2.config.lib.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/d2.config.lib'>;
}
declare module '@dhis2/cli-app-scripts/config/init.App.test.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/init.App.test'>;
}
declare module '@dhis2/cli-app-scripts/config/init.entrypoint.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/init.entrypoint'>;
}
declare module '@dhis2/cli-app-scripts/config/jest.config.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/jest.config'>;
}
declare module '@dhis2/cli-app-scripts/config/jest.file.mock.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/jest.file.mock'>;
}
declare module '@dhis2/cli-app-scripts/config/jest.identity.mock.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/jest.identity.mock'>;
}
declare module '@dhis2/cli-app-scripts/config/jest.styled-jsx-css.mock.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/jest.styled-jsx-css.mock'>;
}
declare module '@dhis2/cli-app-scripts/config/jest.transform.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/jest.transform'>;
}
declare module '@dhis2/cli-app-scripts/config/rollup.config.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/config/rollup.config'>;
}
declare module '@dhis2/cli-app-scripts/src/commands/build.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/commands/build'>;
}
declare module '@dhis2/cli-app-scripts/src/commands/clean.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/commands/clean'>;
}
declare module '@dhis2/cli-app-scripts/src/commands/i18n.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/commands/i18n'>;
}
declare module '@dhis2/cli-app-scripts/src/commands/init.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/commands/init'>;
}
declare module '@dhis2/cli-app-scripts/src/commands/start.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/commands/start'>;
}
declare module '@dhis2/cli-app-scripts/src/commands/test.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/commands/test'>;
}
declare module '@dhis2/cli-app-scripts/src/index' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src'>;
}
declare module '@dhis2/cli-app-scripts/src/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/bundleApp.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/bundleApp'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/compiler/compile.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/compiler/compile'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/compiler/compileApp.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/compiler/compileApp'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/compiler/compileLibrary.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/compiler/compileLibrary'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/compiler/index' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/compiler'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/compiler/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/compiler'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/exitOnCatch.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/exitOnCatch'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/generateManifest.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/generateManifest'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/extract.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n/extract'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/generate.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n/generate'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/helpers.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n/helpers'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/index' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/locales.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n/locales'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/i18n/validate.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/i18n/validate'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/loadEnvFiles.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/loadEnvFiles'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/parseConfig.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/parseConfig'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/paths.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/paths'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/shell/bootstrap.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/shell/bootstrap'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/shell/env.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/shell/env'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/shell/index' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/shell'>;
}
declare module '@dhis2/cli-app-scripts/src/lib/shell/index.js' {
  declare module.exports: $Exports<'@dhis2/cli-app-scripts/src/lib/shell'>;
}
