// flow-typed signature: f0a864d820f7108ecce7ab2df6d5956a
// flow-typed version: <<STUB>>/@dhis2/cypress-commands_v^5.0.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/cypress-commands'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/cypress-commands' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/cypress-commands/babel.jest.config' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/build/cjs/lib' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/build/es/lib' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest.test' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-expected' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-source' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/codemods/replace-get-find-with-xxxxGetWithDataTest' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/d2.config' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/jest.config' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src/commands/find' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src/commands/get' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src/commands/login' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src/helper/dataTestNameToSelector' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src/helper/parseSelectorWithDataTest' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src' {
  declare module.exports: any;
}

declare module '@dhis2/cypress-commands/src/setups/enableAutoLogin' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/cypress-commands/babel.jest.config.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/babel.jest.config'>;
}
declare module '@dhis2/cypress-commands/build/cjs/lib.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/build/cjs/lib'>;
}
declare module '@dhis2/cypress-commands/build/es/lib.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/build/es/lib'>;
}
declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest.test.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest.test'>;
}
declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-expected/index' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-expected'>;
}
declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-expected/index.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-expected'>;
}
declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-source/index' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-source'>;
}
declare module '@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-source/index.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/codemods/__test__/replace-get-find-with-xxxxGetWithDataTest/get-find-source'>;
}
declare module '@dhis2/cypress-commands/codemods/replace-get-find-with-xxxxGetWithDataTest.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/codemods/replace-get-find-with-xxxxGetWithDataTest'>;
}
declare module '@dhis2/cypress-commands/d2.config.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/d2.config'>;
}
declare module '@dhis2/cypress-commands/jest.config.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/jest.config'>;
}
declare module '@dhis2/cypress-commands/src/commands/find.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src/commands/find'>;
}
declare module '@dhis2/cypress-commands/src/commands/get.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src/commands/get'>;
}
declare module '@dhis2/cypress-commands/src/commands/login.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src/commands/login'>;
}
declare module '@dhis2/cypress-commands/src/helper/dataTestNameToSelector.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src/helper/dataTestNameToSelector'>;
}
declare module '@dhis2/cypress-commands/src/helper/parseSelectorWithDataTest.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src/helper/parseSelectorWithDataTest'>;
}
declare module '@dhis2/cypress-commands/src/index' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src'>;
}
declare module '@dhis2/cypress-commands/src/index.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src'>;
}
declare module '@dhis2/cypress-commands/src/setups/enableAutoLogin.js' {
  declare module.exports: $Exports<'@dhis2/cypress-commands/src/setups/enableAutoLogin'>;
}
