// flow-typed signature: a83365bf2ab638dc6050799466423876
// flow-typed version: <<STUB>>/@dhis2/d2-i18n_v^1.0.6/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@dhis2/d2-i18n/index' {
  declare module.exports: $Exports<'@dhis2/d2-i18n'>;
}
declare module '@dhis2/d2-i18n/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-i18n'>;
}
