// flow-typed signature: a98a3a3eefd3e6fcc026ac4dd9099601
// flow-typed version: <<STUB>>/@dhis2/d2-i18n-extract_v^1.0.8/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-i18n-extract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-i18n-extract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/d2-i18n-extract/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/d2-i18n-extract/helpers.js' {
  declare module.exports: $Exports<'@dhis2/d2-i18n-extract/helpers'>;
}
declare module '@dhis2/d2-i18n-extract/index' {
  declare module.exports: $Exports<'@dhis2/d2-i18n-extract'>;
}
declare module '@dhis2/d2-i18n-extract/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-i18n-extract'>;
}
