// flow-typed signature: 8eaddf809fa646337ea0247878cc24f6
// flow-typed version: <<STUB>>/@dhis2/d2-icons_v^1.0.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-icons' {
  declare module.exports: any;
}
