// flow-typed signature: ea7684ed063ab008f97fe36fbf50e745
// flow-typed version: <<STUB>>/@dhis2/d2-i18n-generate_v^1.1.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-i18n-generate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-i18n-generate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@dhis2/d2-i18n-generate/index' {
  declare module.exports: $Exports<'@dhis2/d2-i18n-generate'>;
}
declare module '@dhis2/d2-i18n-generate/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-i18n-generate'>;
}
