// flow-typed signature: 05dd6f608d04036854eab5b7872cdc6d
// flow-typed version: <<STUB>>/@dhis2/d2-ui-app_v^2.0.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-ui-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-ui-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/d2-ui-app/build/cjs' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-app/build/es' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-app/build' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/d2-ui-app/build/cjs/index' {
  declare module.exports: $Exports<'@dhis2/d2-ui-app/build/cjs'>;
}
declare module '@dhis2/d2-ui-app/build/cjs/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-app/build/cjs'>;
}
declare module '@dhis2/d2-ui-app/build/es/index' {
  declare module.exports: $Exports<'@dhis2/d2-ui-app/build/es'>;
}
declare module '@dhis2/d2-ui-app/build/es/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-app/build/es'>;
}
declare module '@dhis2/d2-ui-app/build/index' {
  declare module.exports: $Exports<'@dhis2/d2-ui-app/build'>;
}
declare module '@dhis2/d2-ui-app/build/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-app/build'>;
}
