// flow-typed signature: fa54c748434bc072a4615719adbdd4c6
// flow-typed version: <<STUB>>/@dhis2/d2-ui-sharing-dialog_v^6.5.10/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-ui-sharing-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-ui-sharing-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/d2-ui-sharing-dialog/Access.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/AutoComplete.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/CreatedBy.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/PermissionOption.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/PermissionPicker.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/Sharing.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/SharingDialog.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/UserSearch.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-sharing-dialog/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/d2-ui-sharing-dialog/Access.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/Access.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/AutoComplete.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/AutoComplete.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/CreatedBy.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/CreatedBy.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/index' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/PermissionOption.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/PermissionOption.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/PermissionPicker.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/PermissionPicker.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/Sharing.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/Sharing.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/SharingDialog.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/SharingDialog.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/UserSearch.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/UserSearch.component'>;
}
declare module '@dhis2/d2-ui-sharing-dialog/utils.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-sharing-dialog/utils'>;
}
