// flow-typed signature: 96f29057f0cd84fdd2c3ab3948897c2e
// flow-typed version: <<STUB>>/@dhis2/d2-ui-rich-text_v^6.1.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-ui-rich-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-ui-rich-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/d2-ui-rich-text/editor/convertCtrlKey' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-rich-text/editor/Editor' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-rich-text/parser/MdParser' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-rich-text/parser/Parser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/d2-ui-rich-text/editor/convertCtrlKey.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-rich-text/editor/convertCtrlKey'>;
}
declare module '@dhis2/d2-ui-rich-text/editor/Editor.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-rich-text/editor/Editor'>;
}
declare module '@dhis2/d2-ui-rich-text/index' {
  declare module.exports: $Exports<'@dhis2/d2-ui-rich-text'>;
}
declare module '@dhis2/d2-ui-rich-text/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-rich-text'>;
}
declare module '@dhis2/d2-ui-rich-text/parser/MdParser.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-rich-text/parser/MdParser'>;
}
declare module '@dhis2/d2-ui-rich-text/parser/Parser.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-rich-text/parser/Parser'>;
}
