// flow-typed signature: 086c9c19e0ee2440046edffd71b4c875
// flow-typed version: <<STUB>>/@dhis2/d2-ui-org-unit-tree_v^6.1.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/d2-ui-org-unit-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/d2-ui-org-unit-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/d2-ui-org-unit-tree/OrgUnitTree.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-org-unit-tree/OrgUnitTreeMultipleRoots.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-org-unit-tree/OUCheckbox.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-org-unit-tree/OUFolderIcon.component' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-org-unit-tree/styles/OrgUnitTree.component.styles' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-org-unit-tree/styles/OUCheckbox.component.styles' {
  declare module.exports: any;
}

declare module '@dhis2/d2-ui-org-unit-tree/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/d2-ui-org-unit-tree/index' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/index.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/OrgUnitTree.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/OrgUnitTree.component'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/OrgUnitTreeMultipleRoots.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/OrgUnitTreeMultipleRoots.component'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/OUCheckbox.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/OUCheckbox.component'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/OUFolderIcon.component.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/OUFolderIcon.component'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/styles/OrgUnitTree.component.styles.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/styles/OrgUnitTree.component.styles'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/styles/OUCheckbox.component.styles.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/styles/OUCheckbox.component.styles'>;
}
declare module '@dhis2/d2-ui-org-unit-tree/utils.js' {
  declare module.exports: $Exports<'@dhis2/d2-ui-org-unit-tree/utils'>;
}
