// flow-typed signature: a117c4cbb8278497874e855b576b13dd
// flow-typed version: <<STUB>>/@dhis2/ui-core_v^4.21.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/ui-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/ui-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/ui-core/build/cjs/lib' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/ui-core/build/cjs/lib.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/lib'>;
}
declare module '@dhis2/ui-core/build/es/lib.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/lib'>;
}
