// flow-typed signature: 8c849acc1e105b29b3b0ecd1cd428152
// flow-typed version: <<STUB>>/@dhis2/ui-core_v^4.21.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/ui-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/ui-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/ui-core/build/cjs/AlertBar/Action' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertBar/Actions' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertBar/Dismiss' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertBar/Icon' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertBar' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertBar/Message' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertBar/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertStack' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/AlertStack/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Button' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Button/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/ButtonStrip' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/ButtonStrip/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Card' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Checkbox/Icon' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Checkbox' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Checkbox/Input' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Checkbox/Label' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Chip/Content' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Chip/Icon' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Chip' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Chip/Remove' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/CircularLoader' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/CircularLoader/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/common-prop-types' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/ComponentCover' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/CssReset' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/CssVariables' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Divider' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/DropdownButton' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/DropMenu/getPosition' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/DropMenu' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/constants' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled/InputContainer' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled/Label' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined/InputContainer' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined/Label' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/FormControl' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Help' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Arrow' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Cancel' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Checkbox' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Chevron' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Close' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Radio' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Status' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/icons/Switch' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/InputField' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/InputField/Input' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/LinearLoader' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Logo' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Logo/LogoIconSvg' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Logo/LogoSvg' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Menu' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/MenuItem' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/MenuItem/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/MenuList' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Modal/Actions' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Modal/Content' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Modal' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Modal/ModalCard' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Modal/Title' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Node' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Radio' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Radio/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/RadioGroup' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/ScreenCover' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/SelectField' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/SelectField/Select' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/SplitButton' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Switch' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Switch/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/Table' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableBody' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableCell' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableCellHead' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableFoot' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableHead' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableRow' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Table/TableRowHead' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Tabs/animatedSideScroll' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Tabs/detectHorizontalScrollbarHeight' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Tabs' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Tabs/ScrollBar' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Tabs/Tab' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/Tabs/TabBar' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/cjs/theme' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/main.0f2cd20e9377143cd72a.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/main.10c0b7ce2300b42d9c33.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/runtime~main.0f2cd20e9377143cd72a.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/runtime~main.bc5736b348b208430f61.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/sb_dll/storybook_ui_dll' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/vendors~main.0f2cd20e9377143cd72a.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/docs/vendors~main.6424bb15994139fff484.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar/Action' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar/Actions' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar/Dismiss' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar/Icon' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar/Message' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertBar/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertStack' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/AlertStack/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Button' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Button/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/ButtonStrip' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/ButtonStrip/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Card' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Checkbox/Icon' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Checkbox' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Checkbox/Input' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Checkbox/Label' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Chip/Content' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Chip/Icon' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Chip' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Chip/Remove' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/CircularLoader' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/CircularLoader/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/common-prop-types' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/ComponentCover' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/CssReset' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/CssVariables' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Divider' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/DropdownButton' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/DropMenu/getPosition' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/DropMenu' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/constants' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/Filled' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/Filled/InputContainer' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/Filled/Label' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined/InputContainer' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined/Label' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/FormControl' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Help' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Arrow' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Cancel' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Checkbox' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Chevron' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Close' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Radio' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Status' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/icons/Switch' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/InputField' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/InputField/Input' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/LinearLoader' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Logo' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Logo/LogoIconSvg' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Logo/LogoSvg' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Menu' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/MenuItem' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/MenuItem/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/MenuList' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Modal/Actions' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Modal/Content' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Modal' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Modal/ModalCard' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Modal/Title' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Node' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Radio' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Radio/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/RadioGroup' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/ScreenCover' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/SelectField' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/SelectField/Select' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/SplitButton' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Switch' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Switch/styles' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/Table' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableBody' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableCell' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableCellHead' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableFoot' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableHead' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableRow' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Table/TableRowHead' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Tabs/animatedSideScroll' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Tabs/detectHorizontalScrollbarHeight' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Tabs' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Tabs/ScrollBar' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Tabs/Tab' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/Tabs/TabBar' {
  declare module.exports: any;
}

declare module '@dhis2/ui-core/build/es/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/ui-core/build/cjs/AlertBar/Action.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar/Action'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/Actions.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar/Actions'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/Dismiss.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar/Dismiss'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/Icon.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar/Icon'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/Message.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar/Message'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertBar/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertBar/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertStack/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertStack'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertStack/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertStack'>;
}
declare module '@dhis2/ui-core/build/cjs/AlertStack/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/AlertStack/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/Button/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Button'>;
}
declare module '@dhis2/ui-core/build/cjs/Button/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Button'>;
}
declare module '@dhis2/ui-core/build/cjs/Button/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Button/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/ButtonStrip/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ButtonStrip'>;
}
declare module '@dhis2/ui-core/build/cjs/ButtonStrip/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ButtonStrip'>;
}
declare module '@dhis2/ui-core/build/cjs/ButtonStrip/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ButtonStrip/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/Card/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Card'>;
}
declare module '@dhis2/ui-core/build/cjs/Card/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Card'>;
}
declare module '@dhis2/ui-core/build/cjs/Checkbox/Icon.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Checkbox/Icon'>;
}
declare module '@dhis2/ui-core/build/cjs/Checkbox/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Checkbox'>;
}
declare module '@dhis2/ui-core/build/cjs/Checkbox/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Checkbox'>;
}
declare module '@dhis2/ui-core/build/cjs/Checkbox/Input.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Checkbox/Input'>;
}
declare module '@dhis2/ui-core/build/cjs/Checkbox/Label.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Checkbox/Label'>;
}
declare module '@dhis2/ui-core/build/cjs/Chip/Content.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Chip/Content'>;
}
declare module '@dhis2/ui-core/build/cjs/Chip/Icon.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Chip/Icon'>;
}
declare module '@dhis2/ui-core/build/cjs/Chip/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Chip'>;
}
declare module '@dhis2/ui-core/build/cjs/Chip/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Chip'>;
}
declare module '@dhis2/ui-core/build/cjs/Chip/Remove.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Chip/Remove'>;
}
declare module '@dhis2/ui-core/build/cjs/CircularLoader/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/CircularLoader'>;
}
declare module '@dhis2/ui-core/build/cjs/CircularLoader/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/CircularLoader'>;
}
declare module '@dhis2/ui-core/build/cjs/CircularLoader/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/CircularLoader/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/common-prop-types/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/common-prop-types'>;
}
declare module '@dhis2/ui-core/build/cjs/common-prop-types/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/common-prop-types'>;
}
declare module '@dhis2/ui-core/build/cjs/ComponentCover/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ComponentCover'>;
}
declare module '@dhis2/ui-core/build/cjs/ComponentCover/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ComponentCover'>;
}
declare module '@dhis2/ui-core/build/cjs/CssReset/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/CssReset'>;
}
declare module '@dhis2/ui-core/build/cjs/CssReset/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/CssReset'>;
}
declare module '@dhis2/ui-core/build/cjs/CssVariables.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/CssVariables'>;
}
declare module '@dhis2/ui-core/build/cjs/Divider/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Divider'>;
}
declare module '@dhis2/ui-core/build/cjs/Divider/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Divider'>;
}
declare module '@dhis2/ui-core/build/cjs/DropdownButton/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/DropdownButton'>;
}
declare module '@dhis2/ui-core/build/cjs/DropdownButton/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/DropdownButton'>;
}
declare module '@dhis2/ui-core/build/cjs/DropMenu/getPosition.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/DropMenu/getPosition'>;
}
declare module '@dhis2/ui-core/build/cjs/DropMenu/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/DropMenu'>;
}
declare module '@dhis2/ui-core/build/cjs/DropMenu/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/DropMenu'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/constants.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/constants'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Filled'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Filled'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled/InputContainer.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Filled/InputContainer'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Filled/Label.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Filled/Label'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Outlined'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Outlined'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined/InputContainer.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Outlined/InputContainer'>;
}
declare module '@dhis2/ui-core/build/cjs/FieldLabel/Outlined/Label.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FieldLabel/Outlined/Label'>;
}
declare module '@dhis2/ui-core/build/cjs/FormControl/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FormControl'>;
}
declare module '@dhis2/ui-core/build/cjs/FormControl/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/FormControl'>;
}
declare module '@dhis2/ui-core/build/cjs/Help/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Help'>;
}
declare module '@dhis2/ui-core/build/cjs/Help/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Help'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Arrow.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Arrow'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Cancel.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Cancel'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Checkbox.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Checkbox'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Chevron.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Chevron'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Close.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Close'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Radio.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Radio'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Status.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Status'>;
}
declare module '@dhis2/ui-core/build/cjs/icons/Switch.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/icons/Switch'>;
}
declare module '@dhis2/ui-core/build/cjs/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs'>;
}
declare module '@dhis2/ui-core/build/cjs/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs'>;
}
declare module '@dhis2/ui-core/build/cjs/InputField/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/InputField'>;
}
declare module '@dhis2/ui-core/build/cjs/InputField/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/InputField'>;
}
declare module '@dhis2/ui-core/build/cjs/InputField/Input.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/InputField/Input'>;
}
declare module '@dhis2/ui-core/build/cjs/LinearLoader/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/LinearLoader'>;
}
declare module '@dhis2/ui-core/build/cjs/LinearLoader/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/LinearLoader'>;
}
declare module '@dhis2/ui-core/build/cjs/Logo/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Logo'>;
}
declare module '@dhis2/ui-core/build/cjs/Logo/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Logo'>;
}
declare module '@dhis2/ui-core/build/cjs/Logo/LogoIconSvg.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Logo/LogoIconSvg'>;
}
declare module '@dhis2/ui-core/build/cjs/Logo/LogoSvg.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Logo/LogoSvg'>;
}
declare module '@dhis2/ui-core/build/cjs/Menu/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Menu'>;
}
declare module '@dhis2/ui-core/build/cjs/Menu/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Menu'>;
}
declare module '@dhis2/ui-core/build/cjs/MenuItem/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/MenuItem'>;
}
declare module '@dhis2/ui-core/build/cjs/MenuItem/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/MenuItem'>;
}
declare module '@dhis2/ui-core/build/cjs/MenuItem/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/MenuItem/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/MenuList/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/MenuList'>;
}
declare module '@dhis2/ui-core/build/cjs/MenuList/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/MenuList'>;
}
declare module '@dhis2/ui-core/build/cjs/Modal/Actions.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Modal/Actions'>;
}
declare module '@dhis2/ui-core/build/cjs/Modal/Content.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Modal/Content'>;
}
declare module '@dhis2/ui-core/build/cjs/Modal/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Modal'>;
}
declare module '@dhis2/ui-core/build/cjs/Modal/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Modal'>;
}
declare module '@dhis2/ui-core/build/cjs/Modal/ModalCard.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Modal/ModalCard'>;
}
declare module '@dhis2/ui-core/build/cjs/Modal/Title.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Modal/Title'>;
}
declare module '@dhis2/ui-core/build/cjs/Node/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Node'>;
}
declare module '@dhis2/ui-core/build/cjs/Node/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Node'>;
}
declare module '@dhis2/ui-core/build/cjs/Radio/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Radio'>;
}
declare module '@dhis2/ui-core/build/cjs/Radio/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Radio'>;
}
declare module '@dhis2/ui-core/build/cjs/Radio/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Radio/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/RadioGroup/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/RadioGroup'>;
}
declare module '@dhis2/ui-core/build/cjs/RadioGroup/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/RadioGroup'>;
}
declare module '@dhis2/ui-core/build/cjs/ScreenCover/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ScreenCover'>;
}
declare module '@dhis2/ui-core/build/cjs/ScreenCover/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/ScreenCover'>;
}
declare module '@dhis2/ui-core/build/cjs/SelectField/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/SelectField'>;
}
declare module '@dhis2/ui-core/build/cjs/SelectField/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/SelectField'>;
}
declare module '@dhis2/ui-core/build/cjs/SelectField/Select.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/SelectField/Select'>;
}
declare module '@dhis2/ui-core/build/cjs/SplitButton/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/SplitButton'>;
}
declare module '@dhis2/ui-core/build/cjs/SplitButton/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/SplitButton'>;
}
declare module '@dhis2/ui-core/build/cjs/Switch/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Switch'>;
}
declare module '@dhis2/ui-core/build/cjs/Switch/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Switch'>;
}
declare module '@dhis2/ui-core/build/cjs/Switch/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Switch/styles'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/Table.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/Table'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableBody.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableBody'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableCell.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableCell'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableCellHead.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableCellHead'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableFoot.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableFoot'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableHead.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableHead'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableRow.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableRow'>;
}
declare module '@dhis2/ui-core/build/cjs/Table/TableRowHead.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Table/TableRowHead'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/animatedSideScroll.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs/animatedSideScroll'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/detectHorizontalScrollbarHeight.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs/detectHorizontalScrollbarHeight'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/ScrollBar.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs/ScrollBar'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/Tab.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs/Tab'>;
}
declare module '@dhis2/ui-core/build/cjs/Tabs/TabBar.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/Tabs/TabBar'>;
}
declare module '@dhis2/ui-core/build/cjs/theme.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/cjs/theme'>;
}
declare module '@dhis2/ui-core/build/docs/main.0f2cd20e9377143cd72a.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/main.0f2cd20e9377143cd72a.bundle'>;
}
declare module '@dhis2/ui-core/build/docs/main.10c0b7ce2300b42d9c33.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/main.10c0b7ce2300b42d9c33.bundle'>;
}
declare module '@dhis2/ui-core/build/docs/runtime~main.0f2cd20e9377143cd72a.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/runtime~main.0f2cd20e9377143cd72a.bundle'>;
}
declare module '@dhis2/ui-core/build/docs/runtime~main.bc5736b348b208430f61.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/runtime~main.bc5736b348b208430f61.bundle'>;
}
declare module '@dhis2/ui-core/build/docs/sb_dll/storybook_ui_dll.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/sb_dll/storybook_ui_dll'>;
}
declare module '@dhis2/ui-core/build/docs/vendors~main.0f2cd20e9377143cd72a.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/vendors~main.0f2cd20e9377143cd72a.bundle'>;
}
declare module '@dhis2/ui-core/build/docs/vendors~main.6424bb15994139fff484.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/docs/vendors~main.6424bb15994139fff484.bundle'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/Action.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar/Action'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/Actions.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar/Actions'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/Dismiss.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar/Dismiss'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/Icon.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar/Icon'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/Message.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar/Message'>;
}
declare module '@dhis2/ui-core/build/es/AlertBar/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertBar/styles'>;
}
declare module '@dhis2/ui-core/build/es/AlertStack/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertStack'>;
}
declare module '@dhis2/ui-core/build/es/AlertStack/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertStack'>;
}
declare module '@dhis2/ui-core/build/es/AlertStack/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/AlertStack/styles'>;
}
declare module '@dhis2/ui-core/build/es/Button/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Button'>;
}
declare module '@dhis2/ui-core/build/es/Button/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Button'>;
}
declare module '@dhis2/ui-core/build/es/Button/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Button/styles'>;
}
declare module '@dhis2/ui-core/build/es/ButtonStrip/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ButtonStrip'>;
}
declare module '@dhis2/ui-core/build/es/ButtonStrip/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ButtonStrip'>;
}
declare module '@dhis2/ui-core/build/es/ButtonStrip/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ButtonStrip/styles'>;
}
declare module '@dhis2/ui-core/build/es/Card/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Card'>;
}
declare module '@dhis2/ui-core/build/es/Card/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Card'>;
}
declare module '@dhis2/ui-core/build/es/Checkbox/Icon.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Checkbox/Icon'>;
}
declare module '@dhis2/ui-core/build/es/Checkbox/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Checkbox'>;
}
declare module '@dhis2/ui-core/build/es/Checkbox/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Checkbox'>;
}
declare module '@dhis2/ui-core/build/es/Checkbox/Input.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Checkbox/Input'>;
}
declare module '@dhis2/ui-core/build/es/Checkbox/Label.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Checkbox/Label'>;
}
declare module '@dhis2/ui-core/build/es/Chip/Content.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Chip/Content'>;
}
declare module '@dhis2/ui-core/build/es/Chip/Icon.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Chip/Icon'>;
}
declare module '@dhis2/ui-core/build/es/Chip/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Chip'>;
}
declare module '@dhis2/ui-core/build/es/Chip/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Chip'>;
}
declare module '@dhis2/ui-core/build/es/Chip/Remove.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Chip/Remove'>;
}
declare module '@dhis2/ui-core/build/es/CircularLoader/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/CircularLoader'>;
}
declare module '@dhis2/ui-core/build/es/CircularLoader/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/CircularLoader'>;
}
declare module '@dhis2/ui-core/build/es/CircularLoader/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/CircularLoader/styles'>;
}
declare module '@dhis2/ui-core/build/es/common-prop-types/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/common-prop-types'>;
}
declare module '@dhis2/ui-core/build/es/common-prop-types/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/common-prop-types'>;
}
declare module '@dhis2/ui-core/build/es/ComponentCover/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ComponentCover'>;
}
declare module '@dhis2/ui-core/build/es/ComponentCover/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ComponentCover'>;
}
declare module '@dhis2/ui-core/build/es/CssReset/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/CssReset'>;
}
declare module '@dhis2/ui-core/build/es/CssReset/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/CssReset'>;
}
declare module '@dhis2/ui-core/build/es/CssVariables.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/CssVariables'>;
}
declare module '@dhis2/ui-core/build/es/Divider/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Divider'>;
}
declare module '@dhis2/ui-core/build/es/Divider/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Divider'>;
}
declare module '@dhis2/ui-core/build/es/DropdownButton/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/DropdownButton'>;
}
declare module '@dhis2/ui-core/build/es/DropdownButton/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/DropdownButton'>;
}
declare module '@dhis2/ui-core/build/es/DropMenu/getPosition.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/DropMenu/getPosition'>;
}
declare module '@dhis2/ui-core/build/es/DropMenu/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/DropMenu'>;
}
declare module '@dhis2/ui-core/build/es/DropMenu/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/DropMenu'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/constants.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/constants'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Filled/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Filled'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Filled/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Filled'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Filled/InputContainer.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Filled/InputContainer'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Filled/Label.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Filled/Label'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Outlined'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Outlined'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined/InputContainer.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Outlined/InputContainer'>;
}
declare module '@dhis2/ui-core/build/es/FieldLabel/Outlined/Label.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FieldLabel/Outlined/Label'>;
}
declare module '@dhis2/ui-core/build/es/FormControl/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FormControl'>;
}
declare module '@dhis2/ui-core/build/es/FormControl/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/FormControl'>;
}
declare module '@dhis2/ui-core/build/es/Help/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Help'>;
}
declare module '@dhis2/ui-core/build/es/Help/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Help'>;
}
declare module '@dhis2/ui-core/build/es/icons/Arrow.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Arrow'>;
}
declare module '@dhis2/ui-core/build/es/icons/Cancel.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Cancel'>;
}
declare module '@dhis2/ui-core/build/es/icons/Checkbox.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Checkbox'>;
}
declare module '@dhis2/ui-core/build/es/icons/Chevron.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Chevron'>;
}
declare module '@dhis2/ui-core/build/es/icons/Close.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Close'>;
}
declare module '@dhis2/ui-core/build/es/icons/Radio.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Radio'>;
}
declare module '@dhis2/ui-core/build/es/icons/Status.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Status'>;
}
declare module '@dhis2/ui-core/build/es/icons/Switch.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/icons/Switch'>;
}
declare module '@dhis2/ui-core/build/es/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es'>;
}
declare module '@dhis2/ui-core/build/es/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es'>;
}
declare module '@dhis2/ui-core/build/es/InputField/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/InputField'>;
}
declare module '@dhis2/ui-core/build/es/InputField/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/InputField'>;
}
declare module '@dhis2/ui-core/build/es/InputField/Input.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/InputField/Input'>;
}
declare module '@dhis2/ui-core/build/es/LinearLoader/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/LinearLoader'>;
}
declare module '@dhis2/ui-core/build/es/LinearLoader/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/LinearLoader'>;
}
declare module '@dhis2/ui-core/build/es/Logo/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Logo'>;
}
declare module '@dhis2/ui-core/build/es/Logo/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Logo'>;
}
declare module '@dhis2/ui-core/build/es/Logo/LogoIconSvg.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Logo/LogoIconSvg'>;
}
declare module '@dhis2/ui-core/build/es/Logo/LogoSvg.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Logo/LogoSvg'>;
}
declare module '@dhis2/ui-core/build/es/Menu/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Menu'>;
}
declare module '@dhis2/ui-core/build/es/Menu/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Menu'>;
}
declare module '@dhis2/ui-core/build/es/MenuItem/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/MenuItem'>;
}
declare module '@dhis2/ui-core/build/es/MenuItem/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/MenuItem'>;
}
declare module '@dhis2/ui-core/build/es/MenuItem/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/MenuItem/styles'>;
}
declare module '@dhis2/ui-core/build/es/MenuList/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/MenuList'>;
}
declare module '@dhis2/ui-core/build/es/MenuList/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/MenuList'>;
}
declare module '@dhis2/ui-core/build/es/Modal/Actions.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Modal/Actions'>;
}
declare module '@dhis2/ui-core/build/es/Modal/Content.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Modal/Content'>;
}
declare module '@dhis2/ui-core/build/es/Modal/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Modal'>;
}
declare module '@dhis2/ui-core/build/es/Modal/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Modal'>;
}
declare module '@dhis2/ui-core/build/es/Modal/ModalCard.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Modal/ModalCard'>;
}
declare module '@dhis2/ui-core/build/es/Modal/Title.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Modal/Title'>;
}
declare module '@dhis2/ui-core/build/es/Node/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Node'>;
}
declare module '@dhis2/ui-core/build/es/Node/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Node'>;
}
declare module '@dhis2/ui-core/build/es/Radio/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Radio'>;
}
declare module '@dhis2/ui-core/build/es/Radio/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Radio'>;
}
declare module '@dhis2/ui-core/build/es/Radio/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Radio/styles'>;
}
declare module '@dhis2/ui-core/build/es/RadioGroup/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/RadioGroup'>;
}
declare module '@dhis2/ui-core/build/es/RadioGroup/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/RadioGroup'>;
}
declare module '@dhis2/ui-core/build/es/ScreenCover/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ScreenCover'>;
}
declare module '@dhis2/ui-core/build/es/ScreenCover/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/ScreenCover'>;
}
declare module '@dhis2/ui-core/build/es/SelectField/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/SelectField'>;
}
declare module '@dhis2/ui-core/build/es/SelectField/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/SelectField'>;
}
declare module '@dhis2/ui-core/build/es/SelectField/Select.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/SelectField/Select'>;
}
declare module '@dhis2/ui-core/build/es/SplitButton/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/SplitButton'>;
}
declare module '@dhis2/ui-core/build/es/SplitButton/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/SplitButton'>;
}
declare module '@dhis2/ui-core/build/es/Switch/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Switch'>;
}
declare module '@dhis2/ui-core/build/es/Switch/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Switch'>;
}
declare module '@dhis2/ui-core/build/es/Switch/styles.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Switch/styles'>;
}
declare module '@dhis2/ui-core/build/es/Table/Table.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/Table'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableBody.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableBody'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableCell.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableCell'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableCellHead.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableCellHead'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableFoot.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableFoot'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableHead.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableHead'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableRow.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableRow'>;
}
declare module '@dhis2/ui-core/build/es/Table/TableRowHead.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Table/TableRowHead'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/animatedSideScroll.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs/animatedSideScroll'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/detectHorizontalScrollbarHeight.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs/detectHorizontalScrollbarHeight'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/index' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/index.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/ScrollBar.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs/ScrollBar'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/Tab.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs/Tab'>;
}
declare module '@dhis2/ui-core/build/es/Tabs/TabBar.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/Tabs/TabBar'>;
}
declare module '@dhis2/ui-core/build/es/theme.js' {
  declare module.exports: $Exports<'@dhis2/ui-core/build/es/theme'>;
}
