// flow-typed signature: 591553bf8aad49d4d9911513100f03ea
// flow-typed version: <<STUB>>/@dhis2/ui-widgets_v^2.0.3/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/ui-widgets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/ui-widgets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/ui-widgets/build/cjs/lib' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/main.16c27494b5840c9e457b.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/main.1e11b83ef734cf811c21.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/precache-manifest.292cca89d870e936e99a7f6e74f915ba' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/runtime~main.1e11b83ef734cf811c21.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/runtime~main.3e80324d580cf3681712.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/sb_dll/storybook_ui_dll' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/service-worker' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/vendors~main.1e11b83ef734cf811c21.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/docs/vendors~main.a23e29d582cdff4715fe.bundle' {
  declare module.exports: any;
}

declare module '@dhis2/ui-widgets/build/es/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/ui-widgets/build/cjs/lib.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/cjs/lib'>;
}
declare module '@dhis2/ui-widgets/build/docs/main.16c27494b5840c9e457b.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/main.16c27494b5840c9e457b.bundle'>;
}
declare module '@dhis2/ui-widgets/build/docs/main.1e11b83ef734cf811c21.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/main.1e11b83ef734cf811c21.bundle'>;
}
declare module '@dhis2/ui-widgets/build/docs/precache-manifest.292cca89d870e936e99a7f6e74f915ba.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/precache-manifest.292cca89d870e936e99a7f6e74f915ba'>;
}
declare module '@dhis2/ui-widgets/build/docs/runtime~main.1e11b83ef734cf811c21.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/runtime~main.1e11b83ef734cf811c21.bundle'>;
}
declare module '@dhis2/ui-widgets/build/docs/runtime~main.3e80324d580cf3681712.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/runtime~main.3e80324d580cf3681712.bundle'>;
}
declare module '@dhis2/ui-widgets/build/docs/sb_dll/storybook_ui_dll.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/sb_dll/storybook_ui_dll'>;
}
declare module '@dhis2/ui-widgets/build/docs/service-worker.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/service-worker'>;
}
declare module '@dhis2/ui-widgets/build/docs/vendors~main.1e11b83ef734cf811c21.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/vendors~main.1e11b83ef734cf811c21.bundle'>;
}
declare module '@dhis2/ui-widgets/build/docs/vendors~main.a23e29d582cdff4715fe.bundle.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/docs/vendors~main.a23e29d582cdff4715fe.bundle'>;
}
declare module '@dhis2/ui-widgets/build/es/lib.js' {
  declare module.exports: $Exports<'@dhis2/ui-widgets/build/es/lib'>;
}
