// flow-typed signature: c6feccb0af432a25a3ab1270f8309035
// flow-typed version: <<STUB>>/@dhis2/ui_v^6.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dhis2/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dhis2/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dhis2/ui/build/cjs/lib' {
  declare module.exports: any;
}

declare module '@dhis2/ui/build/es/lib' {
  declare module.exports: any;
}

declare module '@dhis2/ui/d2.config' {
  declare module.exports: any;
}

declare module '@dhis2/ui/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dhis2/ui/build/cjs/lib.js' {
  declare module.exports: $Exports<'@dhis2/ui/build/cjs/lib'>;
}
declare module '@dhis2/ui/build/es/lib.js' {
  declare module.exports: $Exports<'@dhis2/ui/build/es/lib'>;
}
declare module '@dhis2/ui/d2.config.js' {
  declare module.exports: $Exports<'@dhis2/ui/d2.config'>;
}
declare module '@dhis2/ui/src/index' {
  declare module.exports: $Exports<'@dhis2/ui/src'>;
}
declare module '@dhis2/ui/src/index.js' {
  declare module.exports: $Exports<'@dhis2/ui/src'>;
}
