import React, { useState, useCallback } from 'react';
import moment from 'moment';
import { DateField } from 'capture-core/components/FormFields/New';
import {
    Button,
    IconCalendar16,
    IconEdit16,
    colors,
    spacersNum,
} from '@dhis2/ui';
import i18n from '@dhis2/d2-i18n';
import { withStyles, type WithStyles } from 'capture-core-utils/styles';
import { isValidDate, isValidNonFutureDate } from 'capture-core/utils/validation/validators/form';
import { hasValue } from 'capture-core-utils/validators/form';
import { convertDateObjectToDateFormatString } from 'capture-core/utils/converters/date';
import { systemSettingsStore } from '../../../metaDataMemoryStores';
import { convertValue as convertValueClientToView } from '../../../converters/clientToView';
import { convertValue as convertValueFormToClient } from '../../../converters/formToClient';
import { convertValue as convertValueClientToServer } from '../../../converters/clientToServer';
import { dataElementTypes } from '../../../metaData';

type OwnProps = {
    date: string;
    dateLabel: string;
    locale: string;
    editEnabled: boolean;
    displayAutoGeneratedEventWarning: boolean;
    onSave: (date: string) => void;
    allowFutureDate?: boolean;
};

const styles = (theme: any) => ({
    dateContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: `${spacersNum.dp4}px`,
        fontSize: '14px',
        color: colors.grey900,
    },
    editButton: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'flex-start',
        flexShrink: 0,
        cursor: 'pointer',
        border: 'none',
        borderRadius: '3px',
        background: 'transparent',
        color: colors.grey600,
        padding: '1px',
        marginLeft: '2px',
        '&:focus': {
            outline: 'none',
            background: colors.grey200,
            color: colors.grey800,
        },
        '&:hover': {
            background: colors.grey200,
            color: colors.grey800,
        },
    },
    dateInputLabel: {
        display: 'flex',
        alignItems: 'center',
        gap: `${spacersNum.dp4}px`,
        fontSize: '14px',
        color: colors.grey900,
    },
    inputField: {
        maxWidth: '200px',
    },
    buttonStrip: {
        display: 'flex',
        gap: `${spacersNum.dp4}px`,
        margin: `${spacersNum.dp4}px 0`,
    },
    note: {
        fontSize: '12px',
        color: colors.grey700,
    },
    error: {
        ...theme.typography.caption,
        color: theme.palette.error.main,
    },
});

type Props = OwnProps & WithStyles<typeof styles>;

const DateComponentPlain = ({
    date,
    dateLabel,
    locale,
    editEnabled,
    displayAutoGeneratedEventWarning,
    onSave,
    classes,
    allowFutureDate,
}: Props) => {
    const [editMode, setEditMode] = useState(false);
    const [selectedDate, setSelectedDate] = useState<string>();
    const [validation, setValidation] = useState<{ error: boolean; validationText: string }>();

    const validateDate = useCallback((dateString: string, internalComponentError: any) => {
        if (!hasValue(dateString)) {
            return {
                error: true,
                validationText: i18n.t('A value is required'),
            };
        }

        const dateValidation = isValidDate(dateString, internalComponentError);
        if (!dateValidation.valid) {
            return {
                error: true,
                validationText: dateValidation.errorMessage ?? i18n.t('Please provide a valid date'),
            };
        }

        if (!allowFutureDate) {
            const futureValidation = isValidNonFutureDate(dateString, internalComponentError);
            if (futureValidation !== true) {
                return {
                    error: true,
                    validationText: futureValidation.errorMessage ?? i18n.t('A date in the future is not allowed'),
                };
            }
        }
        return {
            error: false,
            validationText: '',
        };
    }, [allowFutureDate]);

    const dateChangeHandler = useCallback((dateString: string, internalComponentError: any) => {
        setSelectedDate(dateString);
        setValidation(validateDate(dateString, internalComponentError));
    }, [setSelectedDate, validateDate]);
    const displayDate = String(convertValueClientToView(date, dataElementTypes.DATE));

    const onOpenEdit = () => {
        setSelectedDate(String(convertValueClientToView(date, dataElementTypes.DATE)));
        setEditMode(true);
    };
    const saveHandler = () => {
        if (selectedDate) {
            const newClientDate = convertValueFormToClient(selectedDate, dataElementTypes.DATE);
            const newDate = convertValueClientToServer(newClientDate, dataElementTypes.DATE);
            if (typeof newDate === 'string' && newDate !== date) {
                onSave(newDate);
            }
        }
        setEditMode(false);
    };

    return editMode ? (
        <div data-test="widget-enrollment-date">
            <span className={classes.dateInputLabel}>
                <span data-test="widget-enrollment-icon-calendar">
                    <IconCalendar16 color={colors.grey600} />
                </span>
                {dateLabel}
            </span>
            <div className={classes.inputField}>
                <DateField
                    width={200}
                    value={selectedDate}
                    onBlur={dateChangeHandler}
                    label={dateLabel}
                    dense
                    locale={locale}
                    calendarType={systemSettingsStore.get().calendar}
                    dateFormat={systemSettingsStore.get().dateFormat}
                    validation={validation}
                    calendarMax={!allowFutureDate ? convertDateObjectToDateFormatString(moment()) : undefined}
                />
            </div>
            <div className={classes.buttonStrip}>
                <Button
                    primary
                    small
                    onClick={saveHandler}
                    disabled={!!validation?.error}
                >
                    {i18n.t('Save')}
                </Button>
                <Button
                    secondary
                    small
                    onClick={() => { setEditMode(false); setValidation(undefined); }}
                >
                    {i18n.t('Cancel')}
                </Button>
            </div>
            {displayAutoGeneratedEventWarning && (
                <div className={classes.note}>
                    {i18n.t('Existing dates for auto-generated events will not be updated.')}
                </div>
            )}
        </div>
    ) : (
        <div className={classes.dateContainer} data-test="widget-enrollment-date">
            <span data-test="widget-enrollment-icon-calendar">
                <IconCalendar16 color={colors.grey600} />
            </span>
            <span>
                {dateLabel}{': '}
                {displayDate}
            </span>
            {editEnabled &&
                <button
                    className={classes.editButton}
                    data-test="widget-enrollment-icon-edit-date"
                    onClick={onOpenEdit}
                >
                    <IconEdit16 />
                </button>
            }
        </div>
    );
};

export const Date = withStyles(styles)(DateComponentPlain);
