// @flow

export const newEventSaveTypes = {
    SAVEANDADDANOTHER: 'SAVEANDADDANOTHER',
    SAVEANDEXIT: 'SAVEANDEXIT',
    FINISH: 'FINISH',
    SAVEWITHOUTCOMPLETING: 'SAVEWITHOUTCOMPLETING',
    SAVEANDCOMPLETE: 'SAVEANDCOMPLETE',
};
