// @flow

export default {
    ASSIGN_VALUE: 'ASSIGN',
    HIDE_FIELD: 'HIDEFIELD',
    SHOW_ERROR: 'SHOWERROR',
    SHOW_WARNING: 'SHOWWARNING',
    SHOW_ERROR_ONCOMPLETE: 'ERRORONCOMPLETE',
    SHOW_WARNING_ONCOMPLETE: 'WARNINGONCOMPLETE',
    HIDE_SECTION: 'HIDESECTION',
    MAKE_COMPULSORY: 'SETMANDATORYFIELD',
};
