// @flow
export const typeKeys = {
    TEXT: 'TEXT',
    MULTI_TEXT: 'MULTI_TEXT',
    LONG_TEXT: 'LONG_TEXT',
    LETTER: 'LETTER',
    PHONE_NUMBER: 'PHONE_NUMBER',
    EMAIL: 'EMAIL',
    BOOLEAN: 'BOOLEAN',     // Yes/No
    TRUE_ONLY: 'TRUE_ONLY', // Yes Only
    DATE: 'DATE',
    DATETIME: 'DATETIME',
    TIME: 'TIME',
    NUMBER: 'NUMBER',
    PERCENTAGE: 'PERCENTAGE',
    INTEGER: 'INTEGER',
    INTEGER_POSITIVE: 'INTEGER_POSITIVE',
    INTEGER_NEGATIVE: 'INTEGER_NEGATIVE',
    INTEGER_ZERO_OR_POSITIVE: 'INTEGER_ZERO_OR_POSITIVE',
    USERNAME: 'USERNAME',
    COORDINATE: 'COORDINATE',
    ORGANISATION_UNIT: 'ORGANISATION_UNIT',
    AGE: 'AGE',
    URL: 'URL',
    FILE_RESOURCE: 'FILE_RESOURCE',
    IMAGE: 'IMAGE',
};
