// @flow
import type {
    DataSource,
    SelectRow,
    Sort,
    SetColumnOrder,
    CustomRowMenuContents,
    UpdateFilter,
    ClearFilter,
    RemoveFilter,
    SelectRestMenuItem,
    ChangePage,
    ChangeRowsPerPage,
    StickyFilters,
} from '../../../../ListView';

export type Props = $ReadOnly<{|
    updating: boolean,
    updatingWithDialog: boolean,
    dataSource?: DataSource,
    onClickListRow: SelectRow,
    onSortList: Sort,
    onSetListColumnOrder: SetColumnOrder,
    customRowMenuContents?: CustomRowMenuContents,
    onUpdateFilter: UpdateFilter,
    onClearFilter: ClearFilter,
    onRemoveFilter: RemoveFilter,
    onSelectRestMenuItem: SelectRestMenuItem,
    onChangePage: ChangePage,
    onChangeRowsPerPage: ChangeRowsPerPage,
    stickyFilters?: StickyFilters,
    programStageId?: string,
    onRowSelect: (id: string) => void,
    onSelectAll: (rows: Array<string>) => void,
    selectedRows: { [key: string]: boolean },
    allRowsAreSelected: ?boolean,
    selectionInProgress: ?boolean,
    children: React$Node,
|}>;
