// @flow
import React from 'react';
import 'capture-core-utils/extensions/asyncForEachArray';
import 'capture-core-utils/extensions/arrayToHashMap';
// $FlowFixMe autogenerated content
import './locales'; //eslint-disable-line
import { AppStart } from './components/AppStart';

export default () => <AppStart />;
