name: 'Applicable released versions'
description: 'Get the released versions the app should run on'
inputs:
  dev-version:
    description: 'The version for the current dev instance'
outputs:
  versions:
    description: 'The released versions'
runs:
  using: 'node16'
  main: 'dist/index.js'