export const WIDGET_RELATED_STAGES_CONSTANTS = {
    LINKABLE: 'LINKABLE',
    NOT_LINKABLE: 'NOT_LINKABLE',
    AMBIGUOUS_RELATIONSHIPS: 'AMBIGUOUS_RELATIONSHIPS',
};

export const RELATIONSHIP_ENTITIES: {
    PROGRAM_STAGE_INSTANCE: 'PROGRAM_STAGE_INSTANCE',
    TRACKED_ENTITY_INSTANCE: 'TRACKED_ENTITY_INSTANCE',
    PROGRAM_INSTANCE: 'PROGRAM_INSTANCE',
} = Object.freeze({
    PROGRAM_STAGE_INSTANCE: 'PROGRAM_STAGE_INSTANCE',
    TRACKED_ENTITY_INSTANCE: 'TRACKED_ENTITY_INSTANCE',
    PROGRAM_INSTANCE: 'PROGRAM_INSTANCE',
});
