name: 'dhis2: skip e2e tests'

on:
    pull_request_target:
        types: [labeled]

jobs:
    call-e2e-tests-result:
        if: github.event.label.name == 'skip-e2e-tests'
        uses: ./.github/workflows/e2e-tests-result.yml
        with:
            result: true
