name: 'dhis2: e2e tests exceptions'

on:
    push:

jobs:
    call-e2e-tests-result:
        if: github.actor == 'dhis2-bot' || contains(github.event.head_commit.message, '[skip ci]')
        uses: ./.github/workflows/e2e-tests-result.yml
        with:
            result: true
