import { dataElementTypes } from '../../../../../metaData';
import { searchOperators } from './searchOperator.const';

export const defaultSearchOperators = {
    [dataElementTypes.TEXT]: [searchOperators.LIKE, searchOperators.SW, searchOperators.EQ],
    [dataElementTypes.MULTI_TEXT]: [searchOperators.LIKE, searchOperators.SW, searchOperators.EQ],
    [dataElementTypes.LONG_TEXT]: [searchOperators.LIKE, searchOperators.SW, searchOperators.EQ],
    [dataElementTypes.NUMBER]: [searchOperators.RANGE],
    [dataElementTypes.NUMBER_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_POSITIVE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_POSITIVE_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_NEGATIVE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_NEGATIVE_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_ZERO_OR_POSITIVE]: [searchOperators.RANGE],
    [dataElementTypes.INTEGER_ZERO_OR_POSITIVE_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.PERCENTAGE]: [searchOperators.LIKE, searchOperators.SW, searchOperators.EQ],
    [dataElementTypes.DATE]: [searchOperators.RANGE],
    [dataElementTypes.DATE_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.DATETIME]: [searchOperators.RANGE],
    [dataElementTypes.DATETIME_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.TIME]: [searchOperators.RANGE],
    [dataElementTypes.TIME_RANGE]: [searchOperators.RANGE],
    [dataElementTypes.TRUE_ONLY]: [searchOperators.EQ],
    [dataElementTypes.BOOLEAN]: [searchOperators.EQ],
    [dataElementTypes.PHONE_NUMBER]: [searchOperators.LIKE, searchOperators.SW, searchOperators.EQ],
    [dataElementTypes.EMAIL]: [searchOperators.LIKE, searchOperators.SW, searchOperators.EQ],
    [dataElementTypes.ORGANISATION_UNIT]: [searchOperators.EQ],
    [dataElementTypes.AGE]: [searchOperators.EQ],
    [dataElementTypes.USERNAME]: [searchOperators.EQ],
};
